<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CitizenshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('citizenships')->delete();
        $citizenship = array(
            array("name_ka"=>"საქართველო","name_ru"=>"Грузия","name_en"=>"Georgia"),
            array("name_ka"=>"რუსეთი","name_ru"=>"Россия","name_en"=>"Russia"),
            array("name_ka"=>"აშშ","name_ru"=>"США","name_en"=>"USA"),
            array("name_ka"=>"თურქეთი","name_ru"=>"Турция","name_en"=>"Turkey"),
            array("name_ka"=>"იტალია","name_ru"=>"Италия","name_en"=>"Italy"),
            array("name_ka"=>"გერმანია","name_ru"=>"Германия","name_en"=>"Germany"),
            array("name_ka"=>"საბერძნეთი","name_ru"=>"Греция","name_en"=>"Greece"),
            array("name_ka"=>"საფრანგეთი","name_ru"=>"Франция","name_en"=>"France"),
            array("name_ka"=>"სომხეთი","name_ru"=>"Армения","name_en"=>"Armenia"),
            array("name_ka"=>"აზერბაიჯანი","name_ru"=>"Азербайджан","name_en"=>"Azerbaijan"),
            array("name_ka"=>"ავსტრალია","name_ru"=>"Австралия","name_en"=>"Australia"),
            array("name_ka"=>"ავსტრია","name_ru"=>"Австрия","name_en"=>"Austria"),
            array("name_ka"=>"ავღანეთი","name_ru"=>"Афганистан","name_en"=>"Afghanistan"),
            array("name_ka"=>"ალბანეთი","name_ru"=>"Албания","name_en"=>"Albania"),
            array("name_ka"=>"ალჟირი","name_ru"=>"Алжир","name_en"=>"Algeria"),
            array("name_ka"=>"ანგოლა","name_ru"=>"Ангола","name_en"=>"Angola"),
            array("name_ka"=>"ანდორა","name_ru"=>"Андорра","name_en"=>"Andorra"),
            array("name_ka"=>"ანტიგუა და ბარბუდა","name_ru"=>"Антигуа и Барбуда","name_en"=>"Antigua and Barbuda"),
            array("name_ka"=>"არგენტინა","name_ru"=>"Аргентина","name_en"=>"Argentina"),
            array("name_ka"=>"ახალი ზელანდია","name_ru"=>"Новая Зеландия","name_en"=>"New Zealand"),
            array("name_ka"=>"ბანგლადეში","name_ru"=>"в Бангладеш","name_en"=>"in Bangladesh"),
            array("name_ka"=>"ბარბადოსი","name_ru"=>"Барбадос","name_en"=>"Barbados"),
            array("name_ka"=>"ბაჰამის კუნძულები","name_ru"=>"Багамские острова","name_en"=>"Bahamas Islands"),
            array("name_ka"=>"ბაჰრეინი","name_ru"=>"Бахрейн","name_en"=>"Bahrain"),
            array("name_ka"=>"ბელგია","name_ru"=>"Бельгия","name_en"=>"Belgium"),
            array("name_ka"=>"ბელიზი","name_ru"=>"Белиз","name_en"=>"Belize"),
            array("name_ka"=>"ბელორუსია","name_ru"=>"Беларусь","name_en"=>"Belarus"),
            array("name_ka"=>"ბენინი","name_ru"=>"Бенин","name_en"=>"Benin"),
            array("name_ka"=>"ბოლივია","name_ru"=>"Боливия","name_en"=>"Bolivia"),
            array("name_ka"=>"ბოსნია-ჰერცეგოვინა","name_ru"=>"Босния и Герцеговина","name_en"=>"Bosnia-Herzegovina"),
            array("name_ka"=>"ბოტსვანა","name_ru"=>"Ботсвана","name_en"=>"Botswana"),
            array("name_ka"=>"ბრაზილია","name_ru"=>"Бразилия","name_en"=>"Brasil"),
            array("name_ka"=>"ბრუნეი","name_ru"=>"Бруней","name_en"=>"Brunei"),
            array("name_ka"=>"ბულგარეთი","name_ru"=>"Болгария","name_en"=>"Bulgaria"),
            array("name_ka"=>"ბურკინა ფასო","name_ru"=>"Буркина-Фасо","name_en"=>"Burkina Faso"),
            array("name_ka"=>"ბურუნდი","name_ru"=>"Бурунди","name_en"=>"Burundi"),
            array("name_ka"=>"ბუტანი","name_ru"=>"Бутан","name_en"=>"Bhutan"),
            array("name_ka"=>"გაბონი","name_ru"=>"Габон","name_en"=>"Gabon"),
            array("name_ka"=>"გაიანა","name_ru"=>"Гайана","name_en"=>"Guyana"),
            array("name_ka"=>"გამბია","name_ru"=>"Гамбия","name_en"=>"The Gambia"),
            array("name_ka"=>"განა","name_ru"=>"Гана","name_en"=>"Ghana"),
            array("name_ka"=>"გვატემალა","name_ru"=>"Гватемала","name_en"=>"Guatemala"),
            array("name_ka"=>"გვინეა","name_ru"=>"Гвинея","name_en"=>"Guinea"),
            array("name_ka"=>"გვინეას ბისავა","name_ru"=>"Гвинея-Бисау","name_en"=>"Guinea-Bissau"),
            array("name_ka"=>"გრენადა","name_ru"=>"Гренада","name_en"=>"Grenada"),
            array("name_ka"=>"დანია","name_ru"=>"Дания","name_en"=>"Denmark"),
            array("name_ka"=>"დიდი ბრიტანეთი","name_ru"=>"Великобритания","name_en"=>"Great Britain"),
            array("name_ka"=>"დომინიკე","name_ru"=>"Доминик","name_en"=>"Dominic"),
            array("name_ka"=>"დომინიკის რესპუბლიკა","name_ru"=>"Доминиканская Республика","name_en"=>"Dominican Republic"),
            array("name_ka"=>"ეგვიპტე","name_ru"=>"Египет","name_en"=>"Egypt"),
            array("name_ka"=>"ეთიოპია","name_ru"=>"Эфиопия","name_en"=>"Ethiopia"),
            array("name_ka"=>"ეკვადორი","name_ru"=>"Эквадор","name_en"=>"Ecuador"),
            array("name_ka"=>"ეკვატორული გვინეა","name_ru"=>"Экваториальная Гвинея","name_en"=>"Equatorial Guinea"),
            array("name_ka"=>"ერაყი","name_ru"=>"Ирак","name_en"=>"Iraq"),
            array("name_ka"=>"ერითრეა","name_ru"=>"Эритрея","name_en"=>"Eritrea"),
            array("name_ka"=>"ესვატინი","name_ru"=>"Эсватини","name_en"=>"Eswatini"),
            array("name_ka"=>"ესპანეთი","name_ru"=>"Испания","name_en"=>"Spain"),
            array("name_ka"=>"ესტონეთი","name_ru"=>"Эстония","name_en"=>"Estonia"),
            array("name_ka"=>"ვანუატუ","name_ru"=>"Вануату","name_en"=>"Vanuatu"),
            array("name_ka"=>"ვატიკანი","name_ru"=>"Ватикан","name_en"=>"The Vatican"),
            array("name_ka"=>"ვენესუელა","name_ru"=>"Венесуэла","name_en"=>"Venezuela"),
            array("name_ka"=>"ვიეტნამი","name_ru"=>"Вьетнам","name_en"=>"Vietnam"),
            array("name_ka"=>"ზამბია","name_ru"=>"Замбия","name_en"=>"Zambia"),
            array("name_ka"=>"ზიმბაბვე","name_ru"=>"Зимбабве","name_en"=>"Zimbabwe"),
            array("name_ka"=>"თურქმენეთი","name_ru"=>"Туркменистан","name_en"=>"Turkmenistan"),
            array("name_ka"=>"იამაიკა","name_ru"=>"Ямайка","name_en"=>"Jamaica"),
            array("name_ka"=>"იაპონია","name_ru"=>"Япония","name_en"=>"Japan"),
            array("name_ka"=>"იემენი","name_ru"=>"Йемен","name_en"=>"Yemen"),
            array("name_ka"=>"ინდოეთი","name_ru"=>"Индия","name_en"=>"India"),
            array("name_ka"=>"ინდონეზია","name_ru"=>"Индонезия","name_en"=>"Indonesia"),
            array("name_ka"=>"იორდანია","name_ru"=>"Иордания","name_en"=>"Jordan"),
            array("name_ka"=>"ირანი","name_ru"=>"Иран","name_en"=>"Iran"),
            array("name_ka"=>"ირლანდია","name_ru"=>"Ирландия","name_en"=>"Ireland"),
            array("name_ka"=>"ისლანდია","name_ru"=>"Исландия","name_en"=>"Iceland"),
            array("name_ka"=>"ისრაელი","name_ru"=>"Израиль","name_en"=>"Israel"),
            array("name_ka"=>"კამბოჯა","name_ru"=>"Камбоджа","name_en"=>"Cambodia"),
            array("name_ka"=>"კამერუნი","name_ru"=>"Камерун","name_en"=>"Cameroon"),
            array("name_ka"=>"კანადა","name_ru"=>"Канада","name_en"=>"Canada"),
            array("name_ka"=>"კენია","name_ru"=>"Кения","name_en"=>"Kenya"),
            array("name_ka"=>"კვიპროსი","name_ru"=>"Кипр","name_en"=>"Cyprus"),
            array("name_ka"=>"კირიბატი","name_ru"=>"Кирибати","name_en"=>"Kiribati"),
            array("name_ka"=>"კოლუმბია","name_ru"=>"Колумбия","name_en"=>"Colombia"),
            array("name_ka"=>"კომორის კუნძულები","name_ru"=>"Коморские острова","name_en"=>"Comoros Islands"),
            array("name_ka"=>"კონგო","name_ru"=>"Конго","name_en"=>"Congo"),
            array("name_ka"=>"კონგოს რესპუბლიკა","name_ru"=>"Республика Конго","name_en"=>"Republic of the Congo"),
            array("name_ka"=>"კონცხი ვერდე","name_ru"=>"Кабо-Верде","name_en"=>"Cape Verde"),
            array("name_ka"=>"კორეის რესპუბლიკა","name_ru"=>"Республика Корея","name_en"=>"Republic of Korea"),
            array("name_ka"=>"კოსტა რიკა","name_ru"=>"Коста-Рика","name_en"=>"Costa Rica"),
            array("name_ka"=>"კოტ დე იუარი","name_ru"=>"Берег Слоновой Кости","name_en"=>"Côte d'Ivoire"),
            array("name_ka"=>"კუბა","name_ru"=>"Куба","name_en"=>"Cuba"),
            array("name_ka"=>"ლაოსი","name_ru"=>"Лаос","name_en"=>"Laos"),
            array("name_ka"=>"ლატვია","name_ru"=>"Латвия","name_en"=>"Latvia"),
            array("name_ka"=>"ლესოტო","name_ru"=>"Лесото","name_en"=>"Lesotho"),
            array("name_ka"=>"ლიბანი","name_ru"=>"Ливан","name_en"=>"Lebanon"),
            array("name_ka"=>"ლიბერია","name_ru"=>"Либерия","name_en"=>"Liberia"),
            array("name_ka"=>"ლიბია","name_ru"=>"Ливия","name_en"=>"Libya"),
            array("name_ka"=>"ლიტვა","name_ru"=>"Литва","name_en"=>"Lithuania"),
            array("name_ka"=>"ლიხტენშტეინი","name_ru"=>"Лихтенштейн","name_en"=>"Liechtenstein"),
            array("name_ka"=>"ლუქსემბურგი","name_ru"=>"Люксембург","name_en"=>"Luxembourg"),
            array("name_ka"=>"მადაგასკარი","name_ru"=>"Мадагаскар","name_en"=>"Madagascar"),
            array("name_ka"=>"მავრიკი","name_ru"=>"Маврикий","name_en"=>"Mauritius"),
            array("name_ka"=>"მავრიტანია","name_ru"=>"Мавритания","name_en"=>"Mauritania"),
            array("name_ka"=>"მალავი","name_ru"=>"Малави","name_en"=>"Malawi"),
            array("name_ka"=>"მალაიზია","name_ru"=>"Малайзия","name_en"=>"Malaysia"),
            array("name_ka"=>"მალდივის კუნძულები","name_ru"=>"Мальдивские острова","name_en"=>"Maldives Islands"),
            array("name_ka"=>"მალი","name_ru"=>"Мали","name_en"=>"Mali"),
            array("name_ka"=>"მალტა","name_ru"=>"Мальта","name_en"=>"Malta"),
            array("name_ka"=>"მაროკო","name_ru"=>"Марокко","name_en"=>"Morocco"),
            array("name_ka"=>"მარშალის კუნძულები","name_ru"=>"Маршалловы острова","name_en"=>"Marshall Islands"),
            array("name_ka"=>"მექსიკა","name_ru"=>"Мексика","name_en"=>"Mexico"),
            array("name_ka"=>"მიანმარა","name_ru"=>"Мьянма","name_en"=>"Myanmar"),
            array("name_ka"=>"მიკრონეზიის ფედერალური შტატები","name_ru"=>"Федеративные Штаты Микронезии","name_en"=>"Federated States of Micronesia"),
            array("name_ka"=>"მოზამბიკი","name_ru"=>"Мозамбик","name_en"=>"Mozambique"),
            array("name_ka"=>"მოლდოვა","name_ru"=>"Молдова","name_en"=>"Moldova"),
            array("name_ka"=>"მონაკო","name_ru"=>"Монако","name_en"=>"Monaco"),
            array("name_ka"=>"მონღოლეთი","name_ru"=>"Монголия","name_en"=>"Mongolia"),
            array("name_ka"=>"ნამიბია","name_ru"=>"Намибия","name_en"=>"Namibia"),
            array("name_ka"=>"ნაურუ","name_ru"=>"Науру","name_en"=>"Nauru"),
            array("name_ka"=>"ნეპალი","name_ru"=>"Непал","name_en"=>"Nepal"),
            array("name_ka"=>"ნიგერია","name_ru"=>"Нигерия","name_en"=>"Nigeria"),
            array("name_ka"=>"ნიდერლანდი","name_ru"=>"Нидерланды","name_en"=>"Netherlands"),
            array("name_ka"=>"ნიკარაგუა","name_ru"=>"Никарагуа","name_en"=>"Nicaragua"),
            array("name_ka"=>"ნორვეგია","name_ru"=>"Норвегия","name_en"=>"Norway"),
            array("name_ka"=>"ომანი","name_ru"=>"Оман","name_en"=>"Oman"),
            array("name_ka"=>"პაკისტანი","name_ru"=>"Пакистан","name_en"=>"Pakistan"),
            array("name_ka"=>"პალესტინა","name_ru"=>"Палестина","name_en"=>"Palestine"),
            array("name_ka"=>"პალუა","name_ru"=>"Палуа","name_en"=>"Palua"),
            array("name_ka"=>"პანამა","name_ru"=>"Панама","name_en"=>"Panama"),
            array("name_ka"=>"პაპუა-ახალი გვინეა","name_ru"=>"Папуа - Новая Гвинея","name_en"=>"Papua New Guinea"),
            array("name_ka"=>"პარაგვაი","name_ru"=>"Парагвай","name_en"=>"Paraguay"),
            array("name_ka"=>"პერუ","name_ru"=>"Перу","name_en"=>"Peru"),
            array("name_ka"=>"პოლონეთი","name_ru"=>"Польша","name_en"=>"Poland"),
            array("name_ka"=>"პორტუგალია","name_ru"=>"Португалия","name_en"=>"Portugal"),
            array("name_ka"=>"რუანდა","name_ru"=>"Руанда","name_en"=>"Rwanda"),
            array("name_ka"=>"რუმინეთი","name_ru"=>"Румыния","name_en"=>"Romania"),
            array("name_ka"=>"სალვადორი","name_ru"=>"Сальвадор","name_en"=>"Salvador"),
            array("name_ka"=>"სამოა","name_ru"=>"Это Самоа","name_en"=>"It's Samoa"),
            array("name_ka"=>"სამხრეთ აფრიკა","name_ru"=>"Южная Африка","name_en"=>"South Africa"),
            array("name_ka"=>"სამხრეთ ოსეთი","name_ru"=>"Южная Осетия","name_en"=>"South Osetia"),
            array("name_ka"=>"სამხრეთ სუდანი","name_ru"=>"южный Судан","name_en"=>"South Sudan"),
            array("name_ka"=>"სან მარინო","name_ru"=>"Сан-Марино","name_en"=>"San Marino"),
            array("name_ka"=>"სანო ტომე და პრინსიპი","name_ru"=>"Сано-Томе и Принсипи","name_en"=>"Sano Tome and Principe"),
            array("name_ka"=>"საუდის არაბეთი","name_ru"=>"Саудовская Аравия","name_en"=>"Saudi Arabia"),
            array("name_ka"=>"სეიშელის კუნძულები","name_ru"=>"Сейшельские острова","name_en"=>"Seychelles Islands"),
            array("name_ka"=>"სენეგალი","name_ru"=>"Сенегал","name_en"=>"Senegal"),
            array("name_ka"=>"სენტ ვინსენტი და გრენადინები","name_ru"=>"Святой Винсент и Гренадины","name_en"=>"Saint Vincent and the Grenadines"),
            array("name_ka"=>"სენტ კიტსი და ნევისი","name_ru"=>"Сент-Китс и Невис","name_en"=>"Saint Kitts and Nevis"),
            array("name_ka"=>"სერბეთი","name_ru"=>"Сербия","name_en"=>"Serbia"),
            array("name_ka"=>"სიერა ლეონე","name_ru"=>"Сьерра-Леоне","name_en"=>"Sierra Leone"),
            array("name_ka"=>"სინგაპური","name_ru"=>"Сингапур","name_en"=>"Singapore"),
            array("name_ka"=>"სირია","name_ru"=>"Сирия","name_en"=>"Syria"),
            array("name_ka"=>"სლოვაკეთი","name_ru"=>"Словакия","name_en"=>"Slovakia"),
            array("name_ka"=>"სლოვენია","name_ru"=>"Словения","name_en"=>"Slovenia"),
            array("name_ka"=>"სოლომონის კუნძულები","name_ru"=>"Соломоновы острова","name_en"=>"Solomon Islands"),
            array("name_ka"=>"სომალი","name_ru"=>"Сомали","name_en"=>"Somalia"),
            array("name_ka"=>"სუდანი","name_ru"=>"Судан","name_en"=>"Sudan"),
            array("name_ka"=>"სურინამი","name_ru"=>"Суринам","name_en"=>"Suriname"),
            array("name_ka"=>"ტაილანდი","name_ru"=>"Таиланд","name_en"=>"Thailand"),
            array("name_ka"=>"ტანზანია","name_ru"=>"Танзания","name_en"=>"Tanzania"),
            array("name_ka"=>"ტაჯიკეთი","name_ru"=>"Таджикистан","name_en"=>"Tajikistan"),
            array("name_ka"=>"ტიმორი ლესტე","name_ru"=>"Восточный Тимор","name_en"=>"Timor Leste"),
            array("name_ka"=>"ტოგო","name_ru"=>"Идти","name_en"=>"Togo"),
            array("name_ka"=>"ტონგა","name_ru"=>"Тонга","name_en"=>"Tonga"),
            array("name_ka"=>"ტრინიდადი და ტობაგო","name_ru"=>"Тринидад и Тобаго","name_en"=>"Trinidad and Tobago"),
            array("name_ka"=>"ტუვალუ","name_ru"=>"Тувалу","name_en"=>"Tuvalu"),
            array("name_ka"=>"ტუნისი","name_ru"=>"Тунис","name_en"=>"Tunisia"),
            array("name_ka"=>"უგანდა","name_ru"=>"Уганда","name_en"=>"Uganda"),
            array("name_ka"=>"უზბეკეთი","name_ru"=>"Узбекистан","name_en"=>"Uzbekistan"),
            array("name_ka"=>"უკრაინა","name_ru"=>"Украина","name_en"=>"Ukraine"),
            array("name_ka"=>"უნგრეთი","name_ru"=>"Венгрия","name_en"=>"Hungary"),
            array("name_ka"=>"ურუგვაი","name_ru"=>"Уругвай","name_en"=>"Uruguay"),
            array("name_ka"=>"ფილიპინები","name_ru"=>"Филиппины","name_en"=>"Philippines"),
            array("name_ka"=>"ფინეთი","name_ru"=>"Финляндия","name_en"=>"Finland"),
            array("name_ka"=>"ფიჯი","name_ru"=>"Фиджи","name_en"=>"Fiji"),
            array("name_ka"=>"ქუვეითი","name_ru"=>"Кувейт","name_en"=>"Kuwait"),
            array("name_ka"=>"ყაზახეთი","name_ru"=>"Казахстан","name_en"=>"Kazakhstan"),
            array("name_ka"=>"ყატარი","name_ru"=>"Катар","name_en"=>"Qatar"),
            array("name_ka"=>"ყირგიზეთი","name_ru"=>"Кыргызстан","name_en"=>"Kyrgyzstan"),
            array("name_ka"=>"შვედეთი","name_ru"=>"Швеция","name_en"=>"Sweden"),
            array("name_ka"=>"შვეიცარია","name_ru"=>"Швейцария","name_en"=>"Switzerland"),
            array("name_ka"=>"შრი-ლანკა","name_ru"=>"Шри-Ланка","name_en"=>"Sri Lanka"),
            array("name_ka"=>"ჩადი","name_ru"=>"опускаться","name_en"=>"go down"),
            array("name_ka"=>"ჩერნოგორია","name_ru"=>"Черногория","name_en"=>"Montenegro"),
            array("name_ka"=>"ჩეხეთის რესპუბლიკა","name_ru"=>"Чешская Республика","name_en"=>"Czech republic"),
            array("name_ka"=>"ჩილე","name_ru"=>"Чили","name_en"=>"Chile"),
            array("name_ka"=>"ჩინეთი","name_ru"=>"Китай","name_en"=>"China"),
            array("name_ka"=>"ჩრდილოეთ მაკედონია","name_ru"=>"Северная Македония","name_en"=>"North Macedonia"),
            array("name_ka"=>"წმინდა ლუსია","name_ru"=>"Санкт-Люсия","name_en"=>"Saint Lucia"),
            array("name_ka"=>"ხორვატია","name_ru"=>"Хорватия","name_en"=>"Croatia"),
            array("name_ka"=>"ჯიბუტი","name_ru"=>"Джибути","name_en"=>"Djibouti"),
            array("name_ka"=>"ჰაიტი","name_ru"=>"Гаити","name_en"=>"Haiti"),
            array("name_ka"=>"ჰონდურასი","name_ru"=>"Гондурас","name_en"=>"Honduras"),
        );
        DB::table('citizenships')->insert($citizenship);
    }
}
