<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DutySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('duties')->delete();
        $data = array(
            array("name_ka"=>"ბავშვის განვითარებაზე ზრუნვა","name_ru"=>"Забота о развитии ребенка","name_en"=>"Taking care of the child's development","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ოთახის დალაგება","name_ru"=>"Уборка детской комнаты","name_en"=>"Tidying up the child's room","category_id"=>"1"),
            array("name_ka"=>"ბავშვის საბავშვო ბაღისთვის ან სკოლისთვის მომზადება","name_ru"=>"Подготовка ребенка к детскому саду или школе","name_en"=>"Preparing a child for kindergarten or school","category_id"=>"1"),
            array("name_ka"=>"ბავშვის სადილის მომზადება","name_ru"=>"Приготовление детского обеда","name_en"=>"Preparing the child's dinner","category_id"=>"1"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_ru"=>"Отвезти ребенка в школу/детский сад","name_en"=>"Taking the child to school/kindergarten","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ტანსაცმლების გარეცხვა","name_ru"=>"Стирка детской одежды","name_en"=>"Washing baby clothes","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ჰიგიენური პროცედურების ჩატარება","name_ru"=>"Проведение детских гигиенических процедур","name_en"=>"Conducting child hygiene procedures","category_id"=>"1"),
            array("name_ka"=>"ბავშვისათვის თვითმომსახურეობის უნარების შესწავლა","name_ru"=>"Обучение детей навыкам самообслуживания.","name_en"=>"Learning self-service skills for children","category_id"=>"1"),
            array("name_ka"=>"ბავშვისათვის უცხო ენის შესწავლა","name_ru"=>"Изучение ребенку иностранного языка","name_en"=>"Learning a foreign language for a child","category_id"=>"1"),
            array("name_ka"=>"დაუთავება","name_ru"=>"глажка","name_en"=>"ironing","category_id"=>"1"),
            array("name_ka"=>"სადილი","name_ru"=>"семейный ужин","name_en"=>"family dinner","category_id"=>"1"),
            array("name_ka"=>"სარეცხი","name_ru"=>"Стирка","name_en"=>"laundry","category_id"=>"1"),
            array("name_ka"=>"ბავშვის განვითარებაზე ზრუნვა","name_ru"=>"Забота о развитии ребенка","name_en"=>"Taking care of the child's development","category_id"=>"2"),
            array("name_ka"=>"ბავშვის ოთახის დალაგება","name_ru"=>"Уборка детской комнаты","name_en"=>"Tidying up the child's room","category_id"=>"2"),
            array("name_ka"=>"ბავშვის სადილის მომზადება","name_ru"=>"Приготовление детского обеда","name_en"=>"Preparing the child's dinner","category_id"=>"2"),
            array("name_ka"=>"ბავშვის ტანსაცმლების გარეცხვა","name_ru"=>"Стирка детской одежды","name_en"=>"Washing baby clothes","category_id"=>"2"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_ru"=>"Отвезти ребенка в школу/детский сад","name_en"=>"Taking the child to school/kindergarten","category_id"=>"2"),
            array("name_ka"=>"ბავშვის საბავშვო ბაღისთვის ან სკოლისთვის მომზადება","name_ru"=>"Подготовка ребенка к детскому саду или школе","name_en"=>"Preparing a child for kindergarten or school","category_id"=>"2"),
            array("name_ka"=>"ბავშვისათვის თვითმომსახურეობის უნარების შესწავლა","name_ru"=>"Обучение детей навыкам самообслуживания.","name_en"=>"Learning self-service skills for children","category_id"=>"2"),
            array("name_ka"=>"ბავშვის ჰიგიენური პროცედურების ჩატარება","name_ru"=>"Проведение детских гигиенических процедур","name_en"=>"Conducting child hygiene procedures","category_id"=>"2"),
            array("name_ka"=>"ბავშვისათვის უცხო ენის შესწავლა","name_ru"=>"Изучение ребенку иностранного языка","name_en"=>"Learning a foreign language for a child","category_id"=>"2"),
            array("name_ka"=>"სასკოლო დავალებების მომზადებაში დახმარება","name_ru"=>"Помощь в подготовке школьных заданий","name_en"=>"Help in preparing school assignments","category_id"=>"2"),
            array("name_ka"=>"კინო-თეატრებში ბავშვის ტარება","name_ru"=>"водить ребенка в кинотеатрах","name_en"=>"Carrying a child in cinemas","category_id"=>"2"),
            array("name_ka"=>"დაწყებითების რეპეტიტორი","name_ru"=>"Elementary tutor","name_en"=>"репетитор Начальных классов","category_id"=>"3"),
            array("name_ka"=>"მე-VII-XI კლასის ჩათვლით საგნების რეპეტიტორი","name_ru"=>"Tutor of subjects including VII-XI classes","name_en"=>"Репетитор предметов VII-XI классов","category_id"=>"3"),
            array("name_ka"=>"ქიმიის რეპეტიტორი","name_ru"=>"Chemistry tutor","name_en"=>"Репетитор по химии","category_id"=>"3"),
            array("name_ka"=>"ფიზიკის რეპეტიტორი","name_ru"=>"Physics tutor","name_en"=>"Репетитор по физике","category_id"=>"3"),
            array("name_ka"=>"მათემატიკის რეპეტიტორი","name_ru"=>"Mathematics tutor","name_en"=>"Репетитор по математике","category_id"=>"3"),
            array("name_ka"=>"ისტორიის რეპეტიტორი","name_ru"=>"History tutor","name_en"=>"Репетитор по истории","category_id"=>"3"),
            array("name_ka"=>"გეოგრაფიის რეპეტიტორი","name_ru"=>"Geography tutor","name_en"=>"Репетитор по географии","category_id"=>"3"),
            array("name_ka"=>"ინგლისური ენის რეპეტიტორი","name_ru"=>"English tutor","name_en"=>"репетитор по английскому","category_id"=>"3"),
            array("name_ka"=>"რუსული ენის რეპეტიტორი","name_ru"=>"Russian language tutor","name_en"=>"репетитор по русскому языку","category_id"=>"3"),
            array("name_ka"=>"გერმანული ენის რეპეტიტორი","name_ru"=>"German language tutor","name_en"=>"репетитор немецкого языка","category_id"=>"3"),
            array("name_ka"=>"ფრანგული ენის რეპეტიტორი","name_ru"=>"French language tutor","name_en"=>"репетитор французского языка","category_id"=>"3"),
            array("name_ka"=>"თურქული ენის რეპეტიტორი","name_ru"=>"Turkish language tutor","name_en"=>"репетитор по турецкому языку","category_id"=>"3"),
            array("name_ka"=>"ქართული ენის რეპეტიტორი","name_ru"=>"Georgian language tutor","name_en"=>"репетитор грузинского языка","category_id"=>"3"),
            array("name_ka"=>"აბიტურიენტების რეპეტიტორი","name_ru"=>"Tutor of entrants","name_en"=>"репетитор абитуриентов","category_id"=>"3"),
            array("name_ka"=>"უნარების რეპეტიტორი","name_ru"=>"Skills Tutor","name_en"=>"Репетитор по навыкам","category_id"=>"3"),
            array("name_ka"=>"ბინის/სახლის დალაგება","name_ru"=>"Tidying up the apartment/house","name_en"=>"Уборка квартиры/дома","category_id"=>"4"),
            array("name_ka"=>"სარეცხი","name_ru"=>"washing","name_en"=>"стирка","category_id"=>"4"),
            array("name_ka"=>"სადილი","name_ru"=>"dinner","name_en"=>"ужин","category_id"=>"4"),
            array("name_ka"=>"უთო","name_ru"=>"ironing","name_en"=>"глажка","category_id"=>"4"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_ru"=>"Taking the child to school/kindergarten","name_en"=>"Отвезти ребенка в школу/детский сад","category_id"=>"4"),
            array("name_ka"=>"ძაღლის გასეირნება","name_ru"=>"dog walking","name_en"=>"выгул собак","category_id"=>"4"),
            array("name_ka"=>"შინაური ცხოველების/ფრინველების მოვლა","name_ru"=>"Pet/bird care","name_en"=>"Уход за домашними животными/птицами","category_id"=>"4"),
            array("name_ka"=>"ეზოს დალაგება","name_ru"=>"Cleaning the yard","name_en"=>"Уборка двора","category_id"=>"4"),
            array("name_ka"=>"მაღაზიიდან პროდუქტების მოტანა","name_ru"=>"Bringing products from the store","name_en"=>"Привоз продуктов из магазина","category_id"=>"4"),
            array("name_ka"=>"ზონდიანი პაციენტის მოვლა","name_ru"=>"Уход за пациентом с зондом","name_en"=>"Care of the probe patient","category_id"=>"5"),
            array("name_ka"=>"ტრახეასტომიანი პაციენტის მოვლა","name_ru"=>"Уход за больным с трахеостомой","name_en"=>"Care of the patient with a tracheostomy","category_id"=>"5"),
            array("name_ka"=>"მოტეხილობებით პაციენტის მოვლა","name_ru"=>"Уход за больными с переломами","name_en"=>"Care of patients with fractures","category_id"=>"5"),
            array("name_ka"=>"ავტოსაგზაო შემთხვევით დაზიანებული პაციენტის მოვლა","name_ru"=>"Уход за больным, пострадавшим в дорожно-транспортном происшествии","name_en"=>"Caring for a patient injured in a traffic accident","category_id"=>"5"),
            array("name_ka"=>"კათეტერიან პაციენტის მოვლა","name_ru"=>"с пациентом с катетером","name_en"=>"with a patient with a catheter","category_id"=>"5"),
            array("name_ka"=>"მენჯ-ბარძაყ ენდოპროტეზირებული პაციენტის მოვლა","name_ru"=>"Уход за пациентом с эндопротезом тазобедренного сустава","name_en"=>"Care of the hip endoprosthesis patient","category_id"=>"5"),
            array("name_ka"=>"ალცჰაიმერიანი პაციენტის მოვლა","name_ru"=>"уход за пациентами с болезнью Альцгеймера","name_en"=>"Alzheimer's patient care","category_id"=>"5"),
            array("name_ka"=>"ფსიქიური აშლილობის ნიშნების მქონე პაციენტის მოვლა","name_ru"=>"Уход за больным с признаками психического расстройства","name_en"=>"Care of the patient with signs of mental disorder","category_id"=>"5"),
            array("name_ka"=>"მძიმეწონიანი პაციენტის მოვლა","name_ru"=>"Уход за пациентом с тяжелым весом","name_en"=>"Care of the heavy patient","category_id"=>"5"),
            array("name_ka"=>"სანიტარულ-ჰიგიენური პროცედურები","name_ru"=>"санитарно-гигиенические процедуры","name_en"=>"sanitary-hygienic procedures","category_id"=>"5"),
            array("name_ka"=>"ბანაობაში დახმარება","name_ru"=>"Помощь в купании","name_en"=>"Help with bathing","category_id"=>"5"),
            array("name_ka"=>"სუდნოზე დასმა","name_ru"=>"Посадка на судне","name_en"=>"Putting on the boat","category_id"=>"5"),
            array("name_ka"=>"საპირფარეშომდე მიცილება","name_ru"=>"Сопровождение в туалет","name_en"=>"Escorting to the restroom","category_id"=>"5"),
            array("name_ka"=>"პამპერსების გამოცვლა","name_ru"=>"Смена подгузников","name_en"=>"Changing diapers","category_id"=>"5"),
            array("name_ka"=>"პაციენტის კვება, მისთვის საკვების მომზადება","name_ru"=>"Кормление больного, приготовление ему пищи","name_en"=>"Feeding the patient, preparing food for him","category_id"=>"5"),
            array("name_ka"=>"მაღაზიაში პროდუქტების შეძენა","name_ru"=>"Покупка продуктов в магазине","name_en"=>"Purchase products in the store","category_id"=>"5"),
            array("name_ka"=>"ექიმის დანიშნული წამლების მიღებაზე კონტროლი","name_ru"=>"Контроль за приемом препаратов, назначенных врачом","name_en"=>"Control over taking drugs prescribed by the doctor","category_id"=>"5"),
            array("name_ka"=>"ნაწოლების დამუშავება და მისი პროფილაქტიკა","name_ru"=>"Лечение пролежней и их профилактика","name_en"=>"Treatment of bedsores and its prevention","category_id"=>"5"),
            array("name_ka"=>"სიცხის გაზომვა","name_ru"=>"Измерение температури","name_en"=>"Heat measurement","category_id"=>"5"),
            array("name_ka"=>"წნევის გაზომვა","name_ru"=>"Измерение давления","name_en"=>"Pressure Measurement","category_id"=>"5"),
            array("name_ka"=>"პაციენტის ჰაერზე გასეირნებები","name_ru"=>"прогулки пациента на чистом воздухе","name_en"=>"Patient air walks","category_id"=>"5"),
            array("name_ka"=>"პაციენტის ფსიქოლოგიური მხარდაჭერა","name_ru"=>"Психологическая поддержка пациента","name_en"=>"Psychological support of the patient","category_id"=>"5"),
            array("name_ka"=>"პაციენტის ოთახის დალაგება","name_ru"=>"Уборка комнаты пациента","name_en"=>"Tidying up the patient's room","category_id"=>"5"),
            array("name_ka"=>"აფთიაქიდან წამლების ამოტანა","name_ru"=>"Привоз лекарств из аптеки","name_en"=>"Taking out medicines from the pharmacy","category_id"=>"5"),
            array("name_ka"=>"სკლეროზიანი პაციენტის მოვლა","name_ru"=>"Уход за больным рассеянным склерозом","name_en"=>"Care of the patient with multiple sclerosis","category_id"=>"5"),
            array("name_ka"=>"პარკინსონიანი პაციენტის მოვლა","name_ru"=>"Уход за больным с болезнью Паркинсона","name_en"=>"Care of the patient with Parkinson's disease","category_id"=>"5"),
            array("name_ka"=>"ასთმიანი პაციენტის მოვლა","name_ru"=>"Уход за больным астмой","name_en"=>"Care of the asthmatic patient","category_id"=>"5"),
            array("name_ka"=>"ინსულინის ნემსის გაკეთება","name_ru"=>"владение укола инсулиновой иглы","name_en"=>"Making an insulin needle","category_id"=>"5"),
            array("name_ka"=>"გადასხმების გაკეთება","name_ru"=>"делать переливания","name_en"=>"make transfusions","category_id"=>"5"),
            array("name_ka"=>"ონკოლგიური პაციენტი","name_ru"=>"онкологический больной","name_en"=>"oncological patient","category_id"=>"5"),
            array("name_ka"=>"შშმ პირის სრულყოფილი მოვლა","name_ru"=>"Полный уход за инвалидом","name_en"=>"Complete care of a disabled person","category_id"=>"5"),
            array("name_ka"=>"დიალეზიანი პაციენტი","name_ru"=>"Диализный пациент","name_en"=>"Dialysis patient","category_id"=>"5"),
            array("name_ka"=>"უბრალოდ ხანდაზმული პაციენტის მოვლა","name_ru"=>"уход Просто за пожилым пациентом","name_en"=>"Just caring for an elderly patient","category_id"=>"5"),
            array("name_ka"=>"დიაბეტიანი პაციენტის მოვლა","name_ru"=>"уход за больным сахарным диабетом","name_en"=>"caring for a diabetic patient","category_id"=>"5"),
            array("name_ka"=>"70 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 70 sq.m","name_en"=>"плошад до 70 кв.м","category_id"=>"6"),
            array("name_ka"=>"100 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 100 sq.m","name_en"=>"плошад до 100 кв.м","category_id"=>"6"),
            array("name_ka"=>"150 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 150 sq.m","name_en"=>"плошад до 150 кв.м","category_id"=>"6"),
            array("name_ka"=>"200 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 200 sq.m","name_en"=>"плошад до 200 кв.м","category_id"=>"6"),
            array("name_ka"=>"300 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 300 sq.m","name_en"=>"плошад До 300 кв.м","category_id"=>"6"),
            array("name_ka"=>"400 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 400 sq.m","name_en"=>"плошад До 400 кв.м","category_id"=>"6"),
            array("name_ka"=>"500 კვ.მ-მდე ფართის დალაგება ","name_ru"=>"Arrangement of space up to 500 sq.m","name_en"=>"плошад До 500 кв.м","category_id"=>"6"),
            array("name_ka"=>"სადარბაზოს კიბის უჯრედების დალაგება","name_ru"=>"Sorting the cells of the entrance staircase","name_en"=>"уборка подъезда, лестничных клеток","category_id"=>"6"),
            array("name_ka"=>"საკლასო ოთახებისა და კორიდორის დალაგება","name_ru"=>"Tidying up classrooms and corridors","name_en"=>"Уборка классных комнат и коридоров","category_id"=>"6"),
            array("name_ka"=>"ბაღის ოთახებისა და კორიდორის დალაგება","name_ru"=>"Tidying up the garden rooms and the corridor","name_en"=>"Уборка классных комнат и коридора детского сада","category_id"=>"6"),
            array("name_ka"=>"სპორტდარბაზის დალაგება","name_ru"=>"Tidying up the gym","name_en"=>"Уборка спортзала","category_id"=>"6"),
            array("name_ka"=>"კვების ობიექტების დალაგება","name_ru"=>"Arrangement of catering facilities","name_en"=>"Уборка мест общественного питания","category_id"=>"6"),
            array("name_ka"=>"შუშების გაწმენდა","name_ru"=>"Cleaning the windows","name_en"=>"Мойка окон","category_id"=>"6"),
            array("name_ka"=>"ფარდების ჩამოხსნა/გარეცხვა/დაკიდება","name_ru"=>"Removing/washing/hanging curtains","name_en"=>"Снятие/стирка/развешивание штор","category_id"=>"6"),
            array("name_ka"=>"ნარჩენების შეგროვება გადაყრა","name_ru"=>"Waste collection and disposal","name_en"=>"Сбор и утилизация отходов","category_id"=>"6"),
            array("name_ka"=>"ოფისების დალაგება","name_ru"=>"Tidying up offices","name_en"=>"Уборка офисов","category_id"=>"6"),
            array("name_ka"=>"სარემონტო სამუშაოების შემდგომი დალაგება","name_ru"=>"cleaning after repair","name_en"=>"уборка после ремонта","category_id"=>"6"),
            array("name_ka"=>"ბინის გენერალური დალაგება","name_ru"=>"general cleaning of the apartment","name_en"=>"генеральная уборка квартиры","category_id"=>"6"),
            array("name_ka"=>"მგზავრთა გადაყვანა","name_ru"=>"Перевозка пассажиров","name_en"=>"Transportation of passengers","category_id"=>"7"),
            array("name_ka"=>"დამკვეთის მიერ დათქმულ დროს მანქანის დროული მიყვანა ადგილზე","name_ru"=>"Своевременная подача автомобиля на место в согласованное с заказчиком время","name_en"=>"Timely delivery of the car to the place at the time agreed by the customer","category_id"=>"7"),
            array("name_ka"=>"ავტომობილის მუდამ სუფთა და გამართულ მდგომარეობაში შენახვა","name_ru"=>"Поддержание автомобиля всегда в чистоте и исправном состоянии","name_en"=>"Keeping the vehicle always clean and in good condition","category_id"=>"7"),
            array("name_ka"=>"ავტომობილის ტექნიკური მომსახურეობა (გარეცხვა, საწვავითა და ზეთით გამართვა და სხვა),","name_ru"=>"Техническое обслуживание автомобиля (мойка, смазка и т.д.),","name_en"=>"Vehicle maintenance (washing, oiling, etc.),","category_id"=>"7"),
            array("name_ka"=>"ელემენტარული სარემონტო სამუშაოების ჩატარება (თვლების გამოცვლა, აკუმულატორის გამოცვლა დ.ა.შ),","name_ru"=>"Проведение элементарных ремонтных работ (замена колеса, замена аккумулятора и т.д.),","name_en"=>"Carrying out elementary repair work (wheel replacement, battery replacement, etc.),","category_id"=>"7"),
            array("name_ka"=>"გადადგილებისას მგზავრთა უსაფრთხოებასა და კომფორტულობაზე ზრუნვა","name_ru"=>"Забота о безопасности и комфорте пассажиров во время перевозки","name_en"=>"Taking care of the safety and comfort of the passengers during the transfer","category_id"=>"7"),
            array("name_ka"=>"დამქირავებლის დავალებების შესრულება, დაკავშირებული მის ოჯახის წევრთან მიმართებაში, ან სხვა პირადი თხოვნებიდან გამომდინარე.","name_ru"=>"Выполнение задач арендатора, связанных с членом его семьи, или на основании других личных пожеланий.","name_en"=>"Fulfilling the tasks of the tenant, related to his family member, or based on other personal requests.","category_id"=>"7"),
            array("name_ka"=>"არასამუშაო საათებში (ღამით), ავტომობილის დამკვეთის მიერ მითითებულ ადგილას შენახვა.","name_ru"=>"Хранение автомобиля в нерабочее время (ночью), в месте, указанном заказчиком.","name_en"=>"Storage of the vehicle in non-working hours (at night), in the place specified by the customer.","category_id"=>"7"),
            array("name_ka"=>"დისტრიბუციის წარმოება","name_ru"=>"Производство дистрибуции","name_en"=>"Production of distribution","category_id"=>"7"),
            array("name_ka"=>"დამქირავებლის სამსახურში მიყვანა და წამოყვანა","name_ru"=>"Доставка и встреча арендатора с работы","name_en"=>"Bringing and picking up the tenant to work","category_id"=>"7"),
            array("name_ka"=>"კომპანიის თანამშრომლების სამსახურში მიყვანა/წამოყვანა","name_ru"=>"отвоз сотрудников компании на работу","name_en"=>"Bringing company employees to work","category_id"=>"7"),
            array("name_ka"=>"ბავშვების სკოლა/ბაღში წაყვანა/წამოყვანა","name_ru"=>"Отвоз детей в школу/детский сад","name_en"=>"Taking children to school/kindergarten","category_id"=>"7"),
            array("name_ka"=>"კონტროლი ბავშვების სიცოცხლესა და ჯანმრთელობაზე;","name_ru"=>"exercise control over the life and health of children during their stay in the kindergarten;","name_en"=>"осуществлять контроль за жизнью и здоровьем детей во все время их пребывания в саду; ","category_id"=>"8"),
            array("name_ka"=>"სხვადასხვა სახის აქტივობების ჩატარება, განვითარება, სპორტი, არდადეგებისთვის მომზადება და ა.შ.","name_ru"=>"conducting various types of activities, developing, sports, preparing for holidays, etc .;","name_en"=>"проведение различных видов занятий, развивающих, спортивных, подготовку к праздникам и пр.; ","category_id"=>"8"),
            array("name_ka"=>"ბავშვებს შორის უკონფლიქტო კომუნიკაციის ხელშემწყობი ატმოსფეროს შექმნა;","name_ru"=>"create a favorable atmosphere conducive to conflict-free communication between kids;","name_en"=>"создавать благоприятную атмосферу, способствующего бесконфликтному общению между малышами; ","category_id"=>"8"),
            array("name_ka"=>"თვითმომსახურების უნარების შესწავლა;","name_ru"=>"to instill in pupils self-service skills;","name_en"=>"прививать воспитанникам навыки самообслуживания; ","category_id"=>"8"),
            array("name_ka"=>"კონფლიქტების მოგვარება, თავშეკავება და ტაქტი ბავშვებთან და მათ მშობლებთან ურთიერთობისას;","name_ru"=>"resolve conflicts, show restraint and tact with children and their parents;","name_en"=>"разрешать конфликты, проявлять выдержку и тактичность с детьми и их родителями; ","category_id"=>"8"),
            array("name_ka"=>"მოსწავლეთა ჯანმრთელობის მდგომარეობის მონიტორინგი;","name_ru"=>"monitor the health status of pupils;","name_en"=>"контролировать состояние здоровья воспитанников; ","category_id"=>"8"),
            array("name_ka"=>"საფრთხისა და ფორსმაჟორული სიტუაციების დაუყოვნებლივ შეტყობინებები უშუალო ხელმძღვანელისათვის;","name_ru"=>"immediate reporting of danger and force majeure situations to the immediate superiors;","name_en"=>"немедленное сообщение об опасности и форс-мажорных ситуациях непосредственному начальству; ","category_id"=>"8"),
            array("name_ka"=>"სანიტარულ-ჰიგიენური ნორმების დაცვა: სამუშაო ადგილის, სამზარეულო მოწყობილობების სუფთა მდგომარეობაში შენახვა.","name_ru"=>"Observance of sanitary-hygienic norms: keeping the workplace, kitchen equipment in a clean condition.","name_en"=>"Соблюдение санитарно-гигиенических норм: содержание рабочего места, кухонного инвентаря в чистоте.","category_id"=>"9"),
            array("name_ka"=>"საჭირო პროდუქტების რეგულარულად შეძენა.","name_ru"=>"Regular purchase of necessary products.","name_en"=>"Регулярная закупка необходимых продуктов.","category_id"=>"9"),
            array("name_ka"=>"კალკულაცია.","name_ru"=>"calculation.","name_en"=>"расчет/калькулация","category_id"=>"9"),
            array("name_ka"=>"ოჯახის წევრებისა და მათი ხშირი სტუმრების გემოვნების გათვალისწინება, ინდივიდუალური მიდგომა ამ საკითხისადმი.","name_ru"=>"Taking into account the tastes of family members and their frequent guests, an individual approach to this issue.","name_en"=>"Учет вкусов членов семьи и их частых гостей, индивидуальный подход к этому вопросу.","category_id"=>"9"),
            array("name_ka"=>"სუფრასთან მიტანამდე კერძის გაფორმება, ასევე სუფრის გაფორმება.","name_ru"=>"Decoration of the dish before serving, as well as decoration of the table.","name_en"=>"Украшение блюда перед подачей, а также украшение стола.","category_id"=>"9"),
            array("name_ka"=>"თევზეული კერძების მომზადება","name_ru"=>"Preparation of fish dishes","name_en"=>"Приготовление рыбных блюд","category_id"=>"9"),
            array("name_ka"=>"მან-ბურღულეულისაგან კერძების მომზადება","name_ru"=>"Preparation of dishes from man-cereals","name_en"=>"Приготовление блюд из манных круп","category_id"=>"9"),
            array("name_ka"=>"მაკარონის კერძების მომზადება","name_ru"=>"Preparation of pasta dishes","name_en"=>"Приготовление блюд из макарон","category_id"=>"9"),
            array("name_ka"=>"დიაბეტური საკვების მომზადება","name_ru"=>"Preparation of diabetic food","name_en"=>"Приготовление диабетической пищи","category_id"=>"9"),
            array("name_ka"=>"ქართული ცივი და ცხელი კერძების მომზადება","name_ru"=>"Preparation of hot and cold Georgian dishes","name_en"=>"Приготовление горячих и холодных грузинских блюд","category_id"=>"9"),
            array("name_ka"=>"ევროპული კერძების მომზადება","name_ru"=>"Cooking European dishes","name_en"=>"европейские блюда","category_id"=>"9"),
            array("name_ka"=>"აზიური კერძების მომზადება","name_ru"=>"Cooking Asian dishes","name_en"=>"Приготовление азиатских блюд","category_id"=>"9"),
            array("name_ka"=>"აღმოსავლური სამზარეულო","name_ru"=>"Oriental cuisine","name_en"=>"Восточная кухня","category_id"=>"9"),
            array("name_ka"=>"სალათები","name_ru"=>"Salads","name_en"=>"Салаты","category_id"=>"9"),
        );
        DB::table('duties')->insert($data);
    }
}
