<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nationalities')->delete();

        $nationality = array(
            array("id"=>"1","name_ka"=>"აბაზი","name_en"=>"Bath","name_ru"=>"Ванна"),
            array("id"=>"2","name_ka"=>"აგულელი","name_en"=>"Aguleli","name_ru"=>"Агулели"),
            array("id"=>"3","name_ka"=>"ადიღეელი","name_en"=>"Adygeli","name_ru"=>"Адыгели"),
            array("id"=>"4","name_ka"=>"ავარიელი","name_en"=>"accident","name_ru"=>"несчастный случай"),
            array("id"=>"5","name_ka"=>"ავღანელი","name_en"=>"Afghan","name_ru"=>"афганский"),
            array("id"=>"6","name_ka"=>"აზერბაიჯანელი","name_en"=>"Azerbaijani","name_ru"=>"Азербайджанский"),
            array("id"=>"7","name_ka"=>"აინი","name_en"=>"Ain","name_ru"=>"Айн"),
            array("id"=>"8","name_ka"=>"აისორი","name_en"=>"Aisor","name_ru"=>"Айсор"),
            array("id"=>"9","name_ka"=>"ალბანელი","name_en"=>"Albanian","name_ru"=>"албанский"),
            array("id"=>"10","name_ka"=>"ალეუტი","name_en"=>"Aleut","name_ru"=>"алеутский"),
            array("id"=>"11","name_ka"=>"ალტაიელი","name_en"=>"Altai","name_ru"=>"Алтай"),
            array("id"=>"12","name_ka"=>"ამერიკელი","name_en"=>"American","name_ru"=>"американский"),
            array("id"=>"13","name_ka"=>"არაბი","name_en"=>"Arab","name_ru"=>"араб"),
            array("id"=>"14","name_ka"=>"აფხაზი","name_en"=>"Abkhaz","name_ru"=>"Абхазский"),
            array("id"=>"15","name_ka"=>"ბალყარელი","name_en"=>"Balkar","name_ru"=>"балкарский"),
            array("id"=>"16","name_ka"=>"ბაშკირი","name_en"=>"Bashkir","name_ru"=>"башкирский"),
            array("id"=>"17","name_ka"=>"ბელორუსი","name_en"=>"Belarus","name_ru"=>"Беларусь"),
            array("id"=>"18","name_ka"=>"ბელუჯი","name_en"=>"Balochi","name_ru"=>"белуджи"),
            array("id"=>"19","name_ka"=>"ბერძენი","name_en"=>"Greek","name_ru"=>"греческий"),
            array("id"=>"20","name_ka"=>"ბოშა","name_en"=>"Gypsy","name_ru"=>"цыган"),
            array("id"=>"21","name_ka"=>"ბრიტანელი","name_en"=>"British","name_ru"=>"британский"),
            array("id"=>"22","name_ka"=>"ბულგარელი","name_en"=>"Bulgarian","name_ru"=>"болгарский"),
            array("id"=>"23","name_ka"=>"ბურიატი","name_en"=>"Buryat","name_ru"=>"бурятский"),
            array("id"=>"24","name_ka"=>"გაგაუზი","name_en"=>"I'll tell you","name_ru"=>"Я вам скажу"),
            array("id"=>"25","name_ka"=>"გერმანელი","name_en"=>"German","name_ru"=>"Немецкий"),
            array("id"=>"26","name_ka"=>"დარგინი","name_en"=>"Dargin","name_ru"=>"Даргин"),
            array("id"=>"27","name_ka"=>"დაღესტანელი","name_en"=>"Dagestani","name_ru"=>"дагестанский"),
            array("id"=>"28","name_ka"=>"დოლგანელი","name_en"=>"of Dolgan","name_ru"=>"долган"),
            array("id"=>"29","name_ka"=>"დუნგანი","name_en"=>"Dungan","name_ru"=>"дунганский"),
            array("id"=>"30","name_ka"=>"ებრაელი","name_en"=>"Jew","name_ru"=>"еврей"),
            array("id"=>"31","name_ka"=>"ევენკი","name_en"=>"Evenki","name_ru"=>"Эвенки"),
            array("id"=>"32","name_ka"=>"ესკიმოსი","name_en"=>"Eskimo","name_ru"=>"эскимо"),
            array("id"=>"33","name_ka"=>"ესპანელი","name_en"=>"Spanish","name_ru"=>"испанский"),
            array("id"=>"34","name_ka"=>"ესტონელი","name_en"=>"Estonian","name_ru"=>"эстонский"),
            array("id"=>"35","name_ka"=>"ვეფსი","name_en"=>"Veps","name_ru"=>"вепсы"),
            array("id"=>"36","name_ka"=>"ვიეტნამელი","name_en"=>"Vietnamese","name_ru"=>"вьетнамский"),
            array("id"=>"37","name_ka"=>"ზვენი","name_en"=>"Zven","name_ru"=>"Звен"),
            array("id"=>"38","name_ka"=>"თათარი","name_en"=>"Tatar","name_ru"=>"татарин"),
            array("id"=>"39","name_ka"=>"თათი","name_en"=>"paw","name_ru"=>"лапа"),
            array("id"=>"40","name_ka"=>"თურქი","name_en"=>"Turkish","name_ru"=>"турецкий"),
            array("id"=>"41","name_ka"=>"თურქმენი","name_en"=>"Turkmen","name_ru"=>"туркменский"),
            array("id"=>"42","name_ka"=>"იაკუტი","name_en"=>"Yakut","name_ru"=>"якутский"),
            array("id"=>"43","name_ka"=>"იაპონელი","name_en"=>"Japanese","name_ru"=>"Японский"),
            array("id"=>"44","name_ka"=>"იეზიდი","name_en"=>"Yezid","name_ru"=>"Езид"),
            array("id"=>"45","name_ka"=>"ინგუში","name_en"=>"Ingush","name_ru"=>"ингуш"),
            array("id"=>"46","name_ka"=>"ინდიელი","name_en"=>"Indian","name_ru"=>"индийский"),
            array("id"=>"47","name_ka"=>"იჟორელი","name_en"=>"Izhorel","name_ru"=>"Ижорель"),
            array("id"=>"48","name_ka"=>"ირანელი (სპარსელი)","name_en"=>"Iranian (Persian)","name_ru"=>"иранский (персидский)"),
            array("id"=>"49","name_ka"=>"იტალიელი","name_en"=>"Italian","name_ru"=>"итальянский"),
            array("id"=>"50","name_ka"=>"იტელმენი","name_en"=>"Itelman","name_ru"=>"Ительман"),
            array("id"=>"51","name_ka"=>"იუგოსლავი","name_en"=>"Yugoslavia","name_ru"=>"Югославия"),
            array("id"=>"52","name_ka"=>"იუკაგირი","name_en"=>"Yukagiri","name_ru"=>"Юкагири"),
            array("id"=>"53","name_ka"=>"კალმიკი","name_en"=>"Kalmyk","name_ru"=>"калмыцкий"),
            array("id"=>"54","name_ka"=>"კარელიელი","name_en"=>"Karelian","name_ru"=>"карельский"),
            array("id"=>"55","name_ka"=>"კომელი","name_en"=>"Comely","name_ru"=>"миловидный"),
            array("id"=>"56","name_ka"=>"კორეელი","name_en"=>"Korean","name_ru"=>"Корейский"),
            array("id"=>"57","name_ka"=>"კორიაკი","name_en"=>"Koryak","name_ru"=>"корякский"),
            array("id"=>"58","name_ka"=>"კრიზი","name_en"=>"crisis","name_ru"=>"кризис"),
            array("id"=>"59","name_ka"=>"კუმიკი","name_en"=>"Kumik","name_ru"=>"Кумик"),
            array("id"=>"60","name_ka"=>"ლატვიელი","name_en"=>"Latvian","name_ru"=>"Латышский"),
            array("id"=>"61","name_ka"=>"ლაქი","name_en"=>"Lacquer","name_ru"=>"лак"),
            array("id"=>"62","name_ka"=>"ლეზგინი","name_en"=>"Lezgin","name_ru"=>"лезгин"),
            array("id"=>"63","name_ka"=>"ლიტველი","name_en"=>"Lithuanian","name_ru"=>"Литовский"),
            array("id"=>"64","name_ka"=>"მანსი","name_en"=>"Mansi","name_ru"=>"манси"),
            array("id"=>"65","name_ka"=>"მარიიელი","name_en"=>"Mariyel","name_ru"=>"Мариэль"),
            array("id"=>"66","name_ka"=>"მთის ებრაელი","name_en"=>"Mountain Jew","name_ru"=>"горский еврей"),
            array("id"=>"67","name_ka"=>"მოლდაველი","name_en"=>"Moldovan","name_ru"=>"Молдавский"),
            array("id"=>"68","name_ka"=>"მონღოლი","name_en"=>"Mongolian","name_ru"=>"монгольский"),
            array("id"=>"69","name_ka"=>"მორდვინი","name_en"=>"Mordvin","name_ru"=>"Мордвин"),
            array("id"=>"70","name_ka"=>"ნანაი","name_en"=>"Nanai","name_ru"=>"нанайцы"),
            array("id"=>"71","name_ka"=>"ნენი","name_en"=>"Nene","name_ru"=>"Нене"),
            array("id"=>"72","name_ka"=>"ნივხი","name_en"=>"Nivkh","name_ru"=>"нивх"),
            array("id"=>"73","name_ka"=>"ნოღაი","name_en"=>"Nogai","name_ru"=>"ногайцы"),
            array("id"=>"74","name_ka"=>"ოროკი","name_en"=>"Orok","name_ru"=>"Орок"),
            array("id"=>"75","name_ka"=>"ოროჩი","name_en"=>"Oroch","name_ru"=>"Ороч"),
            array("id"=>"76","name_ka"=>"ოსი","name_en"=>"Ossetian","name_ru"=>"осетинский"),
            array("id"=>"77","name_ka"=>"პოლონელი","name_en"=>"Polish","name_ru"=>"польский"),
            array("id"=>"78","name_ka"=>"რუთულელი","name_en"=>"Rutulian","name_ru"=>"рутульское"),
            array("id"=>"79","name_ka"=>"რუმინელი","name_en"=>"Romanian","name_ru"=>"румынский"),
            array("id"=>"80","name_ka"=>"რუსი","name_en"=>"Russian","name_ru"=>"Русский"),
            array("id"=>"81","name_ka"=>"საამი","name_en"=>"Saami","name_ru"=>"саамы"),
            array("id"=>"82","name_ka"=>"სელკუპი","name_en"=>"Selkup","name_ru"=>"селькуп"),
            array("id"=>"83","name_ka"=>"სლოვაკი","name_en"=>"Slovakia","name_ru"=>"Словакия"),
            array("id"=>"84","name_ka"=>"სომეხი","name_en"=>"Armenian","name_ru"=>"Армянский"),
            array("id"=>"85","name_ka"=>"ტაბასარანი","name_en"=>"Tabasaran","name_ru"=>"Табасаран"),
            array("id"=>"86","name_ka"=>"ტალიში","name_en"=>"in Tally","name_ru"=>"в счете"),
            array("id"=>"87","name_ka"=>"ტაჯიკი","name_en"=>"Tajik","name_ru"=>"таджикский"),
            array("id"=>"88","name_ka"=>"ტეფტიარი","name_en"=>"Teftyar","name_ru"=>"Тефтяр"),
            array("id"=>"89","name_ka"=>"ტოფალარი","name_en"=>"Tofalar","name_ru"=>"тофалар"),
            array("id"=>"90","name_ka"=>"ტუვინელი","name_en"=>"the Tuvinian","name_ru"=>"тувинский"),
            array("id"=>"91","name_ka"=>"უდეღეი","name_en"=>"Udegei","name_ru"=>"Удэгей"),
            array("id"=>"92","name_ka"=>"უდინი","name_en"=>"Udin","name_ru"=>"Удин"),
            array("id"=>"93","name_ka"=>"უდმურტი","name_en"=>"Udmurt","name_ru"=>"удмуртский"),
            array("id"=>"94","name_ka"=>"უზბეკი","name_en"=>"Uzbek","name_ru"=>"узбекский"),
            array("id"=>"95","name_ka"=>"უიღური","name_en"=>"Uighur","name_ru"=>"уйгурский"),
            array("id"=>"96","name_ka"=>"უკრაინელი","name_en"=>"Ukrainian","name_ru"=>"украинец"),
            array("id"=>"97","name_ka"=>"ულჩი","name_en"=>"Ulchi","name_ru"=>"Ульчи"),
            array("id"=>"98","name_ka"=>"უნგრელი","name_en"=>"Hungarian","name_ru"=>"Венгерский"),
            array("id"=>"99","name_ka"=>"ფინელი","name_en"=>"Finnish","name_ru"=>"финский"),
            array("id"=>"100","name_ka"=>"ფრანგი","name_en"=>"French","name_ru"=>"Французский"),
            array("id"=>"101","name_ka"=>"ქართველი","name_en"=>"Georgian","name_ru"=>"грузинский"),
            array("id"=>"102","name_ka"=>"ქართველი ებრაელი","name_en"=>"Georgian Jew","name_ru"=>"грузинский еврей"),
            array("id"=>"103","name_ka"=>"ქეთი","name_en"=>"Katie","name_ru"=>"Кэти"),
            array("id"=>"104","name_ka"=>"ქურთი","name_en"=>"Kurdish","name_ru"=>"курдский"),
            array("id"=>"105","name_ka"=>"ყაბარდოელი","name_en"=>"Kabardino","name_ru"=>"Кабардино"),
            array("id"=>"106","name_ka"=>"ყაზახი","name_en"=>"Kazakh","name_ru"=>"казахский"),
            array("id"=>"107","name_ka"=>"ყარაიელი","name_en"=>"Karaite","name_ru"=>"караимский"),
            array("id"=>"108","name_ka"=>"ყარაყალაკი","name_en"=>"Karakalak","name_ru"=>"каракалакский"),
            array("id"=>"109","name_ka"=>"ყარაჩაელი","name_en"=>"from Karachay","name_ru"=>"из Карачая"),
            array("id"=>"110","name_ka"=>"ყირგიზი","name_en"=>"Kyrgyz","name_ru"=>"кыргызский"),
            array("id"=>"111","name_ka"=>"ყირიმელი","name_en"=>"Crimean","name_ru"=>"крымский"),
            array("id"=>"112","name_ka"=>"ყირიმელი თათარი","name_en"=>"Crimean Tatar","name_ru"=>"крымскотатарский"),
            array("id"=>"113","name_ka"=>"შუა აზიელი ებრაელი","name_en"=>"Central Asian Jew","name_ru"=>"среднеазиатский еврей"),
            array("id"=>"114","name_ka"=>"ჩერქეზი","name_en"=>"Circassian","name_ru"=>"черкесский"),
            array("id"=>"115","name_ka"=>"ჩეჩენი","name_en"=>"Chechen","name_ru"=>"чеченский"),
            array("id"=>"116","name_ka"=>"ჩეხი","name_en"=>"Czech","name_ru"=>"Чешский"),
            array("id"=>"117","name_ka"=>"ჩინელი","name_en"=>"Chinese","name_ru"=>"Китайский"),
            array("id"=>"118","name_ka"=>"ჩრდილოეთის სხვა ხალხები","name_en"=>"other peoples of the north","name_ru"=>"другие народы севера"),
            array("id"=>"119","name_ka"=>"ჩუვაში","name_en"=>"in Chuva","name_ru"=>"в Чуве"),
            array("id"=>"120","name_ka"=>"ჩუკჩი","name_en"=>"Chukchi","name_ru"=>"Чукотский"),
            array("id"=>"121","name_ka"=>"ცახური","name_en"=>"Chilli","name_ru"=>"Перец чили"),
            array("id"=>"122","name_ka"=>"ხაკასი","name_en"=>"Khakas","name_ru"=>"хакасы"),
            array("id"=>"123","name_ka"=>"ხანტი","name_en"=>"Khanty","name_ru"=>"Ханты"),
            array("id"=>"124","name_ka"=>"ჯემშიდი","name_en"=>"Jamshed","name_ru"=>"Джамшед"),
        );
        DB::table('nationalities')->insert($nationality);
    }
}
