<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProfessionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('professions')->delete();
        $data = array(
            array("name_ru"=>"Рефлексотерапевт","name_ka"=>"რეფლექსოლოგი","name_en"=>"reflexologists"),
            array("name_ru"=>"Врач МСЭК (медико-социальной экспертизы),","name_ka"=>"MSEC ექიმი (სამედიცინო-სოციალური ექსპერტიზა),","name_en"=>"MSEC Doctor (Medical-Social Expertise),"),
            array("name_ru"=>"Агроном","name_ka"=>"აგრონომი","name_en"=>"Agronomist"),
            array("name_ru"=>"Агроном-почвовед","name_ka"=>"აგრონომ-ნიადაგმცოდნე","name_en"=>"Agronomist-soil expert"),
            array("name_ru"=>"Адвокат","name_ka"=>"ადვოკატი","name_en"=>"lawyer"),
            array("name_ru"=>"Сиделка","name_ka"=>"ავადმყოფის/მოხუცის მომვლელი","name_en"=>"Caregiver of the sick/elderly"),
            array("name_ru"=>"Авиационный техник","name_ka"=>"ავიაციის ტექნიკოსი","name_en"=>"Aviation technician"),
            array("name_ru"=>"Автоэлектрик","name_ka"=>"ავტოელეკტრიკი","name_en"=>"Autoelectric"),
            array("name_ru"=>"Автослесарь","name_ka"=>"ავტოზეინკალი","name_en"=>"auto locksmith"),
            array("name_ru"=>"Аккумуляторщик","name_ka"=>"აკუმლიატორისტი","name_en"=>"accumulator"),
            array("name_ru"=>"Инженер-акустик","name_ka"=>"აკუსტიკური ინჟინერი","name_en"=>"Acoustic engineer"),
            array("name_ru"=>"Аллерголог-иммунолог (специалист по аллергическим реакциям и в иммунологии),","name_ka"=>"ალერგოლოგ-იმუნოლოგი","name_en"=>"Allergist-immunologist"),
            array("name_ru"=>"Крановщик","name_ka"=>"ამწე-კრანის ოპერატორი","name_en"=>"crane operator"),
            array("name_ru"=>"Аналитик","name_ka"=>"ანალიტიკოსი","name_en"=>"analyst"),
            array("name_ru"=>"Химик-аналитик","name_ka"=>"ანალიტიკოსი ქიმიკოსი","name_en"=>"Analytical Chemist"),
            array("name_ru"=>"Андролог (специалист по особенностям мужского организма),","name_ka"=>"ანდროლოგი (მამაკაცის ორგანიზმის მახასიათებლების სპეციალისტი),","name_en"=>"Andrologist (specialist in the characteristics of the male body),"),
            array("name_ru"=>"Анестезиолог (специалист по анестезии),","name_ka"=>"ანესთეზიოლოგი","name_en"=>"Anesthesiologist"),
            array("name_ru"=>"Антрополог","name_ka"=>"ანთროპოლოგი (ადამიანის წარმომავლობის, განვითარების შესწავლა),","name_en"=>"Anthropologist (study of human origin and development),"),
            array("name_ru"=>"Наводчик орудия","name_ka"=>"არტილერისტ დამმიზნებელი","name_en"=>"Artillery aimer"),
            array("name_ru"=>"Артиллерист","name_ka"=>"არტილერისტი","name_en"=>"Artilleryman"),
            array("name_ru"=>"Археолог","name_ka"=>"არქეოლოგი","name_en"=>"Archaeologist"),
            array("name_ru"=>"Архивариус","name_ka"=>"არქივარიუსი","name_en"=>"Archivist"),
            array("name_ru"=>"Архитектор","name_ka"=>"არქიტექტორი","name_en"=>"an architect"),
            array("name_ru"=>"Космонавт","name_ka"=>"ასტრონავტი","name_en"=>"Astronaut"),
            array("name_ru"=>"Астроном","name_ka"=>"ასტრონომი","name_en"=>"Astronomer"),
            array("name_ru"=>"Астрофизик","name_ka"=>"ასტროფიზიკოსი","name_en"=>"Astrophysicist"),
            array("name_ru"=>"Астрохимик","name_ka"=>"ასტროქიმიკოსი","name_en"=>"an astrochemist"),
            array("name_ru"=>"Сурдолог ","name_ka"=>"აუდიოლოგი (დაქვეითებული სმენის სპეციალისტი),","name_en"=>"audiologist (hearing impaired specialist),"),
            array("name_ru"=>"Аудитор","name_ka"=>"აუდიტორი","name_en"=>"Auditor"),
            array("name_ru"=>"Инженер-взрывотехник","name_ka"=>"აფეთქების ინჟინერი","name_en"=>"Explosive Engineer"),
            array("name_ru"=>"Таксист","name_ka"=>"Ტაქსის მძღოლი","name_en"=>"Taxi driver"),
            array("name_ru"=>"Актуарий","name_ka"=>"აქტუარი (დაზღვევის საქმის სპეციალისტი, რომელიც დაკავებულია სადაზღვევო შენატანების, პენსიებისა და ა.შ. გაანგარიშებით.),","name_en"=>"Actuary (an insurance specialist who is engaged in the calculation of insurance contributions, pensions, etc.),"),
            array("name_ru"=>"Переплётчик","name_ka"=>"აღმდგენი","name_en"=>"Restorative"),
            array("name_ru"=>"Воспитатель","name_ka"=>"აღმზრდელი","name_en"=>"educator"),
            array("name_ru"=>"Востоковед","name_ka"=>"აღმოსავლეთმცოდნე","name_en"=>"Orientalist"),
            array("name_ru"=>"Авиадиспетчер","name_ka"=>"Საჰაერო მოძრაობის მაკონტროლებელი","name_en"=>"Air traffic controller"),
            array("name_ru"=>"Конвоир","name_ka"=>"ბადრაგი","name_en"=>"Escort"),
            array("name_ru"=>"Балерина","name_ka"=>"ბალერინა","name_en"=>"ballerina"),
            array("name_ru"=>"Хлопокороб","name_ka"=>"ბამბის კომბაინერი","name_en"=>"Cotton harvester"),
            array("name_ru"=>"Банкир","name_ka"=>"ბანკირი","name_en"=>"banker"),
            array("name_ru"=>"Бармен","name_ka"=>"ბარმენი","name_en"=>"Bartender"),
            array("name_ru"=>"Баталер","name_ka"=>"ბატალერი","name_en"=>"Battler"),
            array("name_ru"=>"Бактериолог (специалист по бактериям),","name_ka"=>"ბაქტერიოლოგი","name_en"=>"Bacteriologist"),
            array("name_ru"=>"Бактериолог","name_ka"=>"ბაქტერიოლოგი","name_en"=>"Bacteriologist"),
            array("name_ru"=>"Булочник","name_ka"=>"ბეიკერი","name_en"=>"Baker"),
            array("name_ru"=>"Скорняк","name_ka"=>"ბეწვეულის სპეციალისტი","name_en"=>"fur specialist"),
            array("name_ru"=>"Библиотековед","name_ka"=>"ბიბლიოთეკათმცოდნე","name_en"=>"Librarian"),
            array("name_ru"=>"Биоинженер","name_ka"=>"ბიოინჟინერი","name_en"=>"Bioengineer"),
            array("name_ru"=>"Биолог","name_ka"=>"ბიოლოგი","name_en"=>"Biologist"),
            array("name_ru"=>"Биофизик","name_ka"=>"ბიოფიზიკოსი","name_en"=>"Biophysicist"),
            array("name_ru"=>"Биохимик","name_ka"=>"ბიოქიმიკოსი","name_en"=>"Biochemist"),
            array("name_ru"=>"Блоггер","name_ka"=>"ბლოგერი","name_en"=>"blogger"),
            array("name_ru"=>"Бондарь","name_ka"=>"ბონდარი (ხის კასრების დამამზადებელი),","name_en"=>"cooper (maker of wooden barrels),"),
            array("name_ru"=>"Расточник","name_ka"=>"ბორერი","name_en"=>"Borer"),
            array("name_ru"=>"Бортмеханик","name_ka"=>"ბორტ მექანიკოსი","name_en"=>"Flight mechanic"),
            array("name_ru"=>"Борт-стрелок","name_ka"=>"ბორტ მსროლელი","name_en"=>"On-board gunner"),
            array("name_ru"=>"Бортпроводник/стюард","name_ka"=>"ბორტგამცილებელი/სტიუარდი","name_en"=>"flight attendant/steward"),
            array("name_ru"=>"Борт-инженер","name_ka"=>"ბორტის ინჟინერი","name_en"=>"Flight engineer"),
            array("name_ru"=>"Борт-механик","name_ka"=>"ბორტის მექანიკოსი","name_en"=>"Flight mechanic"),
            array("name_ru"=>"Ботаник (профессия),","name_ka"=>"ბოტანიკოსი","name_en"=>"botanist"),
            array("name_ru"=>"Брейдер","name_ka"=>"ბრეიდერი","name_en"=>"Brader"),
            array("name_ru"=>"Брокер","name_ka"=>"ბროკერი","name_en"=>"broker"),
            array("name_ru"=>"Бульдозерист","name_ka"=>"ბულდოზერის მძღოლი","name_en"=>"Bulldozer driver"),
            array("name_ru"=>"Бухгалтер","name_ka"=>"ბუღალტერი","name_en"=>"Accountant"),
            array("name_ru"=>"Холодильщик","name_ka"=>"გამაგრილებელი სისტემების სპეციალისტი","name_en"=>"Cooling systems specialist"),
            array("name_ru"=>"Сапёр","name_ka"=>"გამნაღმველი","name_en"=>"Miner"),
            array("name_ru"=>"Изобретатель","name_ka"=>"გამომგონებელი","name_en"=>"Inventor"),
            array("name_ru"=>"Издатель","name_ka"=>"გამომცემელი","name_en"=>"Publisher"),
            array("name_ru"=>"Следователь","name_ka"=>"გამომძიებელი","name_en"=>"investigator"),
            array("name_ru"=>"Имиджмейкер","name_ka"=>"გამოსახულების შემქმნელი","name_en"=>"image maker"),
            array("name_ru"=>"Выпускающий редактор","name_ka"=>"გამოცემის რედაქტორი","name_en"=>"Editor of the publication"),
            array("name_ru"=>"Продавец","name_ka"=>"გამყიდველი","name_en"=>"seller"),
            array("name_ru"=>"Продавец","name_ka"=>"გამყიდველი","name_en"=>"seller"),
            array("name_ru"=>"Мусоропроводчик","name_ka"=>"გამწმენდი","name_en"=>"cleaner"),
            array("name_ru"=>"Художник по свету","name_ka"=>"განათების დიზაინერი","name_en"=>"lighting designer"),
            array("name_ru"=>"Верстальщик","name_ka"=>"განლაგების დიზაინერი","name_en"=>"layout designer"),
            array("name_ru"=>"Фортификатор","name_ka"=>"განმამაგრებელი","name_en"=>"fastener"),
            array("name_ru"=>"Особист","name_ka"=>"განსაკუთრებულ საქმეთა თანამშრომელი","name_en"=>"Special Affairs Officer"),
            array("name_ru"=>"Кок","name_ka"=>"გასამხედროებული პირადი შემადგენლობის მზარეული","name_en"=>"A cook of the paramilitary staff"),
            array("name_ru"=>"Гастроэнтеролог (специалист в области ЖКТ человека),","name_ka"=>"გასტროენტეროლოგი (ადამიანის კუჭ-ნაწლავის ტრაქტის დარგის სპეციალისტი),","name_en"=>"Gastroenterologist (specialist in the field of human gastrointestinal tract),"),
            array("name_ru"=>"Торговый представитель","name_ka"=>"გაყიდვების წარმომადგენელი","name_en"=>"sales representative"),
            array("name_ru"=>"Капитан судна","name_ka"=>"გემის კაპიტანი","name_en"=>"Captain of the ship"),
            array("name_ru"=>"Генетик","name_ka"=>"გენეტიკოსი","name_en"=>"geneticist"),
            array("name_ru"=>"Генетик","name_ka"=>"გენეტიკოსი","name_en"=>"geneticist"),
            array("name_ru"=>"Географ","name_ka"=>"გეოგრაფი","name_en"=>"geographer"),
            array("name_ru"=>"Геодезист","name_ka"=>"გეოდეზისტი","name_en"=>"surveyor"),
            array("name_ru"=>"Геолог","name_ka"=>"გეოლოგი","name_en"=>"Geologist"),
            array("name_ru"=>"Гитарист","name_ka"=>"გიტარისტი","name_en"=>"guitarist"),
            array("name_ru"=>"Гляциолог","name_ka"=>"გლაციოლოგი (დედამიწაზე ბუნებრივი გამყინვარებების შემსწავლელი მეცნიერება),","name_en"=>"Glaciologist (science studying natural glaciers on Earth),"),
            array("name_ru"=>"Грейдерист","name_ka"=>"გრეიდზერზე მომუშავე","name_en"=>"Grader worker"),
            array("name_ru"=>"Гренадер","name_ka"=>"გრენადერი","name_en"=>"Grenadier"),
            array("name_ru"=>"Гример","name_ka"=>"გრიმიორი","name_en"=>"Grimoire"),
            array("name_ru"=>"Торакальный хирург","name_ka"=>"გულმკერდის ქირურგი","name_en"=>"Thoracic surgeon"),
            array("name_ru"=>"Задумщик","name_ka"=>"დამგეგმავი","name_en"=>"planner"),
            array("name_ru"=>"Клинер","name_ka"=>"დამლაგებელი","name_en"=>"cleaner"),
            array("name_ru"=>"Заряжающий","name_ka"=>"დამმუხტავი","name_en"=>"charger"),
            array("name_ru"=>"Декан","name_ka"=>"დეკანი","name_en"=>"Dean"),
            array("name_ru"=>"Декоратор","name_ka"=>"დეკორატორი","name_en"=>"decorator"),
            array("name_ru"=>"Дерматолог (специалист по коже и ее придаткам),","name_ka"=>"დერმატოლოგი (კანისა და მისი დანამატების სპეციალისტი),","name_en"=>"Dermatologist (specialist of skin and its appendages),"),
            array("name_ru"=>"Дефектолог","name_ka"=>"დეფექტოლოგი","name_en"=>"defectologist"),
            array("name_ru"=>"Диаконисса","name_ka"=>"დიაკვანი","name_en"=>"Deacon"),
            array("name_ru"=>"Диакон","name_ka"=>"დიაკონი","name_en"=>"Deacon"),
            array("name_ru"=>"Горничная","name_ka"=>"დიასახლისი","name_en"=>"housewife"),
            array("name_ru"=>"Диетолог (специалист по питанию),","name_ka"=>"დიეტოლოგი (კვების სპეციალისტი),","name_en"=>"dietician (nutrition specialist),"),
            array("name_ru"=>"Диверсант","name_ka"=>"დივერსანტი","name_en"=>"saboteur"),
            array("name_ru"=>"Дизайнер","name_ka"=>"დიზაინერი","name_en"=>"designer"),
            array("name_ru"=>"Модельер","name_ka"=>"დიზაინერი","name_en"=>"designer"),
            array("name_ru"=>"Инженер-конструктор","name_ka"=>"დიზაინის ინჟინერი","name_en"=>"Design Engineer"),
            array("name_ru"=>"Дилер","name_ka"=>"დილერი","name_en"=>"dealer"),
            array("name_ru"=>"Дипломат","name_ka"=>"დიპლომატი","name_en"=>"Diplomat"),
            array("name_ru"=>"Дипломат","name_ka"=>"დიპლომატი","name_en"=>"Diplomat"),
            array("name_ru"=>"Дирижёр","name_ka"=>"დირიჟორი","name_en"=>"conductor"),
            array("name_ru"=>"Диспетчер","name_ka"=>"დისპეტჩერი","name_en"=>"Dispatcher"),
            array("name_ru"=>"Диктор","name_ka"=>"დიქტორი","name_en"=>"announcer"),
            array("name_ru"=>"Диджей","name_ka"=>"დიჯეი","name_en"=>"DJ"),
            array("name_ru"=>"Донкерман","name_ka"=>"დონკერმანი","name_en"=>"Donkerman"),
            array("name_ru"=>"Драпировщик","name_ka"=>"დრეპერი (ავეჯის გარსაკრავის სპეციალისტი),","name_en"=>"Draper (Furniture Upholstery Specialist),"),
            array("name_ru"=>"Проходчик","name_ka"=>"დრიფტერი","name_en"=>"drifter"),
            array("name_ru"=>"Доула (профессия),","name_ka"=>"დულა (წინამშობიარობის პერიოდში მელოგინე დედის მხარდაჭერა),","name_en"=>"Doula (support of the expectant mother during the prenatal period),"),
            array("name_ru"=>"Плотник","name_ka"=>"დურგალი","name_en"=>"Carpenter"),
            array("name_ru"=>"Столяр","name_ka"=>"დურგალი","name_en"=>"Carpenter"),
            array("name_ru"=>"Садовник","name_ka"=>"Მებაღე","name_en"=>"Gardener"),
            array("name_ru"=>"Садовод","name_ka"=>"Მებაღე","name_en"=>"Gardener"),
            array("name_ru"=>"Египтолог","name_ka"=>"ეგვიპტოლოგი","name_en"=>"Egyptologist"),
            array("name_ru"=>"Эколог","name_ka"=>"ეკოლოგი","name_en"=>"Ecologist"),
            array("name_ru"=>"Экономист","name_ka"=>"ეკონომისტი","name_en"=>"economist"),
            array("name_ru"=>"Электрик","name_ka"=>"ელექტრიკოსი","name_en"=>"Electrician"),
            array("name_ru"=>"Монтажник радиоэлектронной аппаратуры и приборов","name_ka"=>"ელექტრონული აღჭურვილობის და ინსტრუმენტების მემონტაჟე/ინსტალერი","name_en"=>"Fitter/installer of electronic equipment and instruments"),
            array("name_ru"=>"Эндокринолог (специалист по патологии эндокринной системы),","name_ka"=>"ენდოკრინოლოგი (ენდოკრინული სისტემის პათოლოგიის სპეციალისტი),","name_en"=>"Endocrinologist (endocrine system pathology specialist),"),
            array("name_ru"=>"Эндоскопист","name_ka"=>"ენდოსკოპისტი","name_en"=>"Endoscopist"),
            array("name_ru"=>"Начальник штаба","name_ka"=>"Გენერალური შტაბის უფროსი","name_en"=>"Chief of the General Staff"),
            array("name_ru"=>"Энтомолог","name_ka"=>"ენტომოლოგია (ზოოლოგიაში მწერების შემსწავლელი მეცნიერება),","name_en"=>"Entomology (the science of insects in zoology),"),
            array("name_ru"=>"Эпидемиолог","name_ka"=>"ეპიდემიოლოგი","name_en"=>"Epidemiologist"),
            array("name_ru"=>"Епископ","name_ka"=>"ეპისკოპოსი","name_en"=>"Bishop"),
            array("name_ru"=>"Эфферентолог","name_ka"=>"ეფერენტოლოგი (ორგანიზმის მავნე ნივთიერებებისაგან გაწმენდის სპეციალისტი),","name_en"=>"Efferentologist (specialist in cleaning the body from harmful substances),"),
            array("name_ru"=>"Санитар (работник, выполняющий вспомогательные функции),","name_ka"=>"ექთანი (თანამშრომელი, რომელიც ასრულებს დამხმარე ფუნქციებს),","name_en"=>"Nurse (employee who performs support functions),"),
            array("name_ru"=>"Медицинская сестра","name_ka"=>"ექთანი (მედდა),","name_en"=>"nurse"),
            array("name_ru"=>"Экспедитор","name_ka"=>"ექსპედიტორი","name_en"=>"forwarder"),
            array("name_ru"=>"Эксперт-криминалист","name_ka"=>"ექსპერტი კრიმინალისტი","name_en"=>"Expert criminalist"),
            array("name_ru"=>"Веб-интегратор","name_ka"=>"ვებ – ინტეგრატორი","name_en"=>"Web integrator"),
            array("name_ru"=>"Веб-мастер","name_ka"=>"ვებ – მასტერი","name_en"=>"Webmaster"),
            array("name_ru"=>"Веб-программист","name_ka"=>"ვებ პროგრამისტი","name_en"=>"Web programmer"),
            array("name_ru"=>"Венеролог (специалист по ЗППП),","name_ka"=>"ვენეროლოგი","name_en"=>"venereologist"),
            array("name_ru"=>"Вертебролог","name_ka"=>"ვერტებროლოგი","name_en"=>"Vertebrologist"),
            array("name_ru"=>"Ветеринар","name_ka"=>"ვეტერინარი","name_en"=>"Veterinarian"),
            array("name_ru"=>"Визажист","name_ka"=>"ვიზაჟისტი","name_en"=>"makeup artist"),
            array("name_ru"=>"Вирусолог (специалист по вирусам),","name_ka"=>"ვირუსოლოგი","name_en"=>"Virologist"),
            array("name_ru"=>"Вирусолог","name_ka"=>"ვირუსოლოგი","name_en"=>"Virologist"),
            array("name_ru"=>"Витолье","name_ka"=>"ვიტოლი","name_en"=>"Vitol"),
            array("name_ru"=>"Вокалист","name_ka"=>"ვოკალისტი","name_en"=>"Vocalist"),
            array("name_ru"=>"Слесарь","name_ka"=>"ზეინკალი","name_en"=>"Locksmith"),
            array("name_ru"=>"Слесарь-механик","name_ka"=>"ზეინკალ-მექანიკოსი","name_en"=>"locksmith-mechanic"),
            array("name_ru"=>"Старшина","name_ka"=>"ზემდეგი","name_en"=>"Next"),
            array("name_ru"=>"Зоолог","name_ka"=>"ზოოლოგი","name_en"=>"zoologist"),
            array("name_ru"=>"Тыловик","name_ka"=>"ზურგის თანამშრომელი","name_en"=>"Back office worker"),
            array("name_ru"=>"Геймдизайнер","name_ka"=>"თამაშის დიზაინერი","name_en"=>"Game designer"),
            array("name_ru"=>"Табаковод","name_ka"=>"თამბაქოს მწარმოებელი","name_en"=>"Tobacco manufacturer"),
            array("name_ru"=>"Танатолог","name_ka"=>"თანატოლოგია (სხეულის დაბერებისა და სიკვდილის გამომწვევი მიზეზების შემსწავლელი სპეციალისტი),","name_en"=>"Thanatology (specialist studying the causes of aging and death of the body),"),
            array("name_ru"=>"Переводчик","name_ka"=>"თარჯიმანი","name_en"=>"translator"),
            array("name_ru"=>"Теолог","name_ka"=>"თეოლოგი","name_en"=>"a theologian"),
            array("name_ru"=>"Терапевт","name_ka"=>"თერაპევტი","name_en"=>"therapist"),
            array("name_ru"=>"Авиатехник","name_ka"=>"თვითმფრინავის ტექნიკოსი","name_en"=>"aircraft technician"),
            array("name_ru"=>"Оператор вооружения","name_ka"=>"იარაღის ოპერატორი","name_en"=>"Weapons Operator"),
            array("name_ru"=>"Библиотекарь","name_ka"=>"Ბიბლიოთეკარი","name_en"=>"Librarian"),
            array("name_ru"=>"Иллюстратор","name_ka"=>"ილუსტრატორი","name_en"=>"Illustrator"),
            array("name_ru"=>"Иммунолог","name_ka"=>"იმუნოლოგი","name_en"=>"Immunologist"),
            array("name_ru"=>"Инкассатор","name_ka"=>"ინკასატორი","name_en"=>"collector"),
            array("name_ru"=>"Кинорежиссер","name_ka"=>"Კინორეჟისორი","name_en"=>"Film director"),
            array("name_ru"=>"Инженер-химик","name_ka"=>"ინჟინერ ქიმიკოსი","name_en"=>"Chemical engineer"),
            array("name_ru"=>"Инженер-электрик","name_ka"=>"ინჟინერ-ელექტრიკოსი","name_en"=>"Electrician engineer"),
            array("name_ru"=>"Инженер-энергетик","name_ka"=>"ინჟინერ-ენერგეტიკოსი","name_en"=>"Energy engineer"),
            array("name_ru"=>"Инженер","name_ka"=>"ინჟინერი","name_en"=>"an engineer"),
            array("name_ru"=>"Инженер","name_ka"=>"ინჟინერი","name_en"=>"an engineer"),
            array("name_ru"=>"Инженер-механик","name_ka"=>"ინჟინერ-მექანიკოსი","name_en"=>"Mechanical Engineer"),
            array("name_ru"=>"Инженер-строитель","name_ka"=>"ინჟინერ-მშენებელი","name_en"=>"Engineer-builder"),
            array("name_ru"=>"Инженер-технолог","name_ka"=>"ინჟინერ-ტექნოლოგი","name_en"=>"engineer-technologist"),
            array("name_ru"=>"Инженер-физик","name_ka"=>"ინჟინერ-ფიზიკოსი","name_en"=>"Engineer-physicist"),
            array("name_ru"=>"Инженер КИПиА","name_ka"=>"ინსტრუმენტული ინჟინერი","name_en"=>"Instrumental Engineer"),
            array("name_ru"=>"Инфекционист (специалист по профилактике, диагностике и лечению инфекций),","name_ka"=>"ინფექციონისტი","name_en"=>"Infectious disease"),
            array("name_ru"=>"Историк","name_ka"=>"ისტორიკოსი","name_en"=>"Historian"),
            array("name_ru"=>"Ювелир","name_ka"=>"იუველირი","name_en"=>"Jeweler"),
            array("name_ru"=>"Юрисконсульт","name_ka"=>"იურიდიული მრჩეველი","name_en"=>"Legal advisor"),
            array("name_ru"=>"Юрист","name_ka"=>"იურისტი","name_en"=>"a lawyer"),
            array("name_ru"=>"Ихтиолог","name_ka"=>"იშთოლოგი (თევზებისა და ზღვის სხვა მობინადრეების შემსწავლელი მეცნიერება),","name_en"=>"Ichthologist (the science of studying fish and other inhabitants of the sea),"),
            array("name_ru"=>"Монтажник связи","name_ka"=>"კავშირგაბმულობის მემონტაჟე","name_en"=>"Telecommunication installer"),
            array("name_ru"=>"Каптенармус","name_ka"=>"კაპიტანარმუსი","name_en"=>"Captain Armus"),
            array("name_ru"=>"Шкипер","name_ka"=>"კაპიტანი","name_en"=>"Captain"),
            array("name_ru"=>"Кардиолог (специалист в области сердечно-сосудистой системы человека),","name_ka"=>"კარდიოლოგი","name_en"=>"Cardiologist"),
            array("name_ru"=>"Кардиохирург (хирург, выполняющий хирургические операции на сердце),","name_ka"=>"კარდიო-ქირურგი","name_en"=>"Cardio-surgeon"),
            array("name_ru"=>"Швейцар","name_ka"=>"კარისკაცი","name_en"=>"Door Man"),
            array("name_ru"=>"Каскадёр","name_ka"=>"კასკადიორი","name_en"=>"Stuntman"),
            array("name_ru"=>"Детектив (профессия),","name_ka"=>"კერძო დეტექტივი","name_en"=>"private detective"),
            array("name_ru"=>"Интендант","name_ka"=>"კვარტმაისტერი","name_en"=>"Quartermaster"),
            array("name_ru"=>"Кинезитерапевт","name_ka"=>"კინეზერატოლოგი (კინოზითერაპევტი. სამკურნალო ფიზკულტურა),","name_en"=>"Kineseratologist (kinesitherapist. physical therapy),"),
            array("name_ru"=>"Кинолог","name_ka"=>"კინოლოგი","name_en"=>"Cynologist"),
            array("name_ru"=>"Кинооператор","name_ka"=>"კინოოპერატორი","name_en"=>"Cinematographer"),
            array("name_ru"=>"Оператор кино и телевидения","name_ka"=>"კინოსა და ტელევიზიის ოპერატორი","name_en"=>"Cinema and TV operator"),
            array("name_ru"=>"Преподаватель","name_ka"=>"კლასის დამრიგებელი","name_en"=>"class teacher"),
            array("name_ru"=>"Менеджер по работе с клиентами","name_ka"=>"კლიენტებთან მუშაობის მენეჯერი","name_en"=>"Customer Service Manager"),
            array("name_ru"=>"Врач клинической лабораторной диагностики (специалист лабораторной диагностики),","name_ka"=>"კლინიკურ-ლაბორატორიული დიაგნოსტიკის ექიმი","name_en"=>"Doctor of clinical and laboratory diagnostics"),
            array("name_ru"=>"Кодер","name_ka"=>"კოდირება","name_en"=>"Coding"),
            array("name_ru"=>"Сборщик","name_ka"=>"კოლექტორი","name_en"=>"Collector"),
            array("name_ru"=>"Колхозник","name_ka"=>"კოლმეურნე","name_en"=>"Kolmeurne"),
            array("name_ru"=>"Комбайнер","name_ka"=>"კომბინატორი","name_en"=>"combinator"),
            array("name_ru"=>"Комендант","name_ka"=>"კომენდანტი","name_en"=>"Commandant"),
            array("name_ru"=>"Коммерческий директор","name_ka"=>"კომერციული დირექტორი","name_en"=>"Commercial Director"),
            array("name_ru"=>"Оператор ПК","name_ka"=>"კომპიუტერის ოპერატორი","name_en"=>"computer operator"),
            array("name_ru"=>"Композитор","name_ka"=>"კომპოზიტორი","name_en"=>"composer"),
            array("name_ru"=>"Кондитер","name_ka"=>"კონდიტერი","name_en"=>"Confectioner"),
            array("name_ru"=>"Кондитер","name_ka"=>"კონდიტერი","name_en"=>"Confectioner"),
            array("name_ru"=>"Кондуктор","name_ka"=>"კონდუქტორი","name_en"=>"Conductor"),
            array("name_ru"=>"Киномеханик","name_ka"=>"კონომექანიკოსი/პროექციონისტი","name_en"=>"Conomechanic/Projectionist"),
            array("name_ru"=>"Дизайнер-конструктор","name_ka"=>"კონსტრუქტორ-დიზაინერი","name_en"=>"Constructor-designer"),
            array("name_ru"=>"Контент-менеджер","name_ka"=>"კონტენტის მენეჯერი","name_en"=>"Content Manager"),
            array("name_ru"=>"Корректор","name_ka"=>"კორექტორი","name_en"=>"Corrector"),
            array("name_ru"=>"Косметолог","name_ka"=>"კოსმეტოლოგი","name_en"=>"cosmetologist"),
            array("name_ru"=>"Шифровальщик","name_ka"=>"კრიპტოგრაფი","name_en"=>"Cryptographer"),
            array("name_ru"=>"Криптозоолог","name_ka"=>"კრიპტოზოოლოგი (გადაშენებული და უცნაური წარმომავლობის ცხოველების შემსწავლელი მეცნიერება),","name_en"=>"Cryptozoologist (extinct and exotic animals),"),
            array("name_ru"=>"Критик","name_ka"=>"კრიტიკოსი","name_en"=>"critic"),
            array("name_ru"=>"Крупье","name_ka"=>"კრუპიე","name_en"=>"Croupier"),
            array("name_ru"=>"Культуролог","name_ka"=>"კულტუროლოგი","name_en"=>"culturologist"),
            array("name_ru"=>"Курьер","name_ka"=>"კურიერი","name_en"=>"Courier"),
            array("name_ru"=>"Инженер-лаборант","name_ka"=>"ლაბორატორიის ინჟინერი","name_en"=>"Laboratory engineer"),
            array("name_ru"=>"Инженер-гальваник","name_ka"=>"ლითონის მოპირკეთების ინჟინერია (ლითონის სპეციალური დამცავი ზედაპირით დაფარვა),","name_en"=>"Metal coating engineering (covering metal with a special protective surface),"),
            array("name_ru"=>"Лингвист","name_ka"=>"ლინგვისტი","name_en"=>"linguist"),
            array("name_ru"=>"Лифтёр","name_ka"=>"ლიფტიორი","name_en"=>"elevator"),
            array("name_ru"=>"Логик","name_ka"=>"ლოგიკოსი","name_en"=>"a logician"),
            array("name_ru"=>"Логопед (специалист по нарушениям речи),","name_ka"=>"ლოგოპედი","name_en"=>"Speech therapist"),
            array("name_ru"=>"Машинист локомотива","name_ka"=>"ლოკომოტივის მემანქანე","name_en"=>"Locomotive driver"),
            array("name_ru"=>"Математик","name_ka"=>"მათემატიკოსი","name_en"=>"Mathematician"),
            array("name_ru"=>"Маммолог (специалист по патологии молочных желез человека),","name_ka"=>"მამოლოგი (სარძევე ჯირკვლების პათოლოგიის სპეციალისტი),","name_en"=>"Mammologist (breast gland pathology specialist),"),
            array("name_ru"=>"Манекенщица","name_ka"=>"მანეკენი","name_en"=>"Mannequin"),
            array("name_ru"=>"Мастер маникюра","name_ka"=>"მანიკურისტი","name_en"=>"Manicurist"),
            array("name_ru"=>"Мастер маникюра","name_ka"=>"მანიკურისტი","name_en"=>"Manicurist"),
            array("name_ru"=>"Мануальный терапевт (специалист по лечению позвоночника, суставов, систем мышц и внутренних органов воздействием рук),","name_ka"=>"მანუალური თერაპევტი (ხერხემლის, სახსრების, კუნთების სისტემების და შინაგანი ორგანოების ხელებით სამკურნალო სპეციალისტი),","name_en"=>"Manual therapist (specialist in treating the spine, joints, muscular systems and internal organs with hands),"),
            array("name_ru"=>"Оператор машинного доения","name_ka"=>"მანქანით რძის წველის ოპერატორი","name_en"=>"Milking machine operator"),
            array("name_ru"=>"Механизатор","name_ka"=>"მანქანის ოპერატორი","name_en"=>"car operator"),
            array("name_ru"=>"Маркетолог","name_ka"=>"მარკეტოლოგი","name_en"=>"marketer"),
            array("name_ru"=>"Хлебороб","name_ka"=>"მარცვლეულის მწარმოებელი","name_en"=>"grain producer"),
            array("name_ru"=>"Массажист (специалист по массажу),","name_ka"=>"მასაჟისტი","name_en"=>"massage therapist"),
            array("name_ru"=>"Учитель","name_ka"=>"მასწავლებელი","name_en"=>"teacher"),
            array("name_ru"=>"Проводник (железнодорожный служащий),","name_ka"=>"მატარებლის გამცილებელი","name_en"=>"train conductor"),
            array("name_ru"=>"Маркшейдер","name_ka"=>"მაღაროელი","name_en"=>"miner"),
            array("name_ru"=>"Шахтёр","name_ka"=>"მაღაროელი","name_en"=>"miner"),
            array("name_ru"=>"Печатник (профессия),","name_ka"=>"მბეჭდავი","name_en"=>"Impressive"),
            array("name_ru"=>"Секретчик","name_ka"=>"მდივანი","name_en"=>"Secretary"),
            array("name_ru"=>"Акушер-гинеколог (специалист по женским репродуктивным функциям организма),","name_ka"=>"მეან-გინეკოლოგი","name_en"=>"Obstetrics and Gynecology"),
            array("name_ru"=>"Таможенник","name_ka"=>"მებაჟე","name_en"=>"customs officer"),
            array("name_ru"=>"Квасник","name_ka"=>"მებურახე","name_en"=>"drill"),
            array("name_ru"=>"Десантник","name_ka"=>"მედესანტე","name_en"=>"Paratrooper"),
            array("name_ru"=>"Дворник","name_ka"=>"მეეზოვე","name_en"=>"Meadow"),
            array("name_ru"=>"Виноградарь","name_ka"=>"მევენახე","name_en"=>"see me"),
            array("name_ru"=>"Растениевод","name_ka"=>"მევენახე","name_en"=>"see me"),
            array("name_ru"=>"Звонарь","name_ka"=>"მეზარე","name_en"=>"I'm lazy"),
            array("name_ru"=>"Зенитчик","name_ka"=>"მეზენიტე","name_en"=>"Mezzanine"),
            array("name_ru"=>"Командир","name_ka"=>"მეთაური","name_en"=>"Commander"),
            array("name_ru"=>"Стрелочник (профессия),","name_ka"=>"მეისრე/გადამრთველი","name_en"=>"switch/switch"),
            array("name_ru"=>"Кабельщик","name_ka"=>"მეკაბელე (სადენების სპეციალისტი),","name_en"=>"cable technician"),
            array("name_ru"=>"Связист","name_ka"=>"მეკავშირე","name_en"=>"Contact me"),
            array("name_ru"=>"Мелиоратор","name_ka"=>"მელიორატორი","name_en"=>"reclamation"),
            array("name_ru"=>"Машинистка","name_ka"=>"მემანქანე","name_en"=>"drive me"),
            array("name_ru"=>"Машинист","name_ka"=>"მემანქანე","name_en"=>"drive me"),
            array("name_ru"=>"Монтажник","name_ka"=>"მემონტაჟე/ინსტალერი","name_en"=>"Assembler/installer"),
            array("name_ru"=>"Менеджер","name_ka"=>"მენეჯერი","name_en"=>"manager"),
            array("name_ru"=>"Мерчандайзер","name_ka"=>"მერჩანდაიზერი","name_en"=>"Merchandiser"),
            array("name_ru"=>"Пограничник","name_ka"=>"მესაზღვრე","name_en"=>"border guard"),
            array("name_ru"=>"Скотник","name_ka"=>"მესაქონლე","name_en"=>"Cattle breeder"),
            array("name_ru"=>"Металлург","name_ka"=>"მეტალურგი","name_en"=>"Metallurgist"),
            array("name_ru"=>"Метранпаж (устар),","name_ka"=>"მეტანიკი","name_en"=>"Metanic"),
            array("name_ru"=>"Метеоролог","name_ka"=>"მეტეოროლოგი","name_en"=>"Meteorologist"),
            array("name_ru"=>"Инженер-лесотехник","name_ka"=>"მეტყევე ინჟინერი","name_en"=>"Forestry engineer"),
            array("name_ru"=>"Пулемётчик","name_ka"=>"მეტყვიამფრქვევე","name_en"=>"machine gun"),
            array("name_ru"=>"Медник","name_ka"=>"მეფოლადე","name_en"=>"Lord"),
            array("name_ru"=>"Пчеловод","name_ka"=>"მეფუტკრე","name_en"=>"beekeeper"),
            array("name_ru"=>"Инженер по механизации","name_ka"=>"მექანიზაციის ინჟინერი","name_en"=>"Mechanization Engineer"),
            array("name_ru"=>"Механик","name_ka"=>"მექანიკოსი","name_en"=>"mechanic"),
            array("name_ru"=>"Фальцовщик","name_ka"=>"მექაღალდე","name_en"=>"file holder"),
            array("name_ru"=>"Печник","name_ka"=>"მეღუმელე","name_en"=>"oven"),
            array("name_ru"=>"Флорист","name_ka"=>"მეყვავილე","name_en"=>"florist"),
            array("name_ru"=>"Флорист (дизайнер),","name_ka"=>"მეყვავილე (დიზაინერი),","name_en"=>"florist (designer),"),
            array("name_ru"=>"Штукатур","name_ka"=>"მეჩიკატურე","name_en"=>"mechicature"),
            array("name_ru"=>"Учёный","name_ka"=>"მეცნიერი","name_en"=>"scientist"),
            array("name_ru"=>"Овчар","name_ka"=>"მეცხვარე","name_en"=>"shepherd me"),
            array("name_ru"=>"Зоотехник","name_ka"=>"მეცხოველეობის სპეციალისტი","name_en"=>"Animal husbandry specialist"),
            array("name_ru"=>"Предприниматель","name_ka"=>"მეწარმე","name_en"=>"Entrepreneur"),
            array("name_ru"=>"Предприниматель (прикладывает рабочую потенцию работника),","name_ka"=>"მეწარმე (გამოიყენებს თანამშრომლის სამუშაო პოტენციალს),","name_en"=>"Entrepreneur (uses the work potential of the employee),"),
            array("name_ru"=>"Мельник","name_ka"=>"მეწისქვილე","name_en"=>"miller"),
            array("name_ru"=>"Пожарный","name_ka"=>"მეხანძრე","name_en"=>"fireman"),
            array("name_ru"=>"Мясник","name_ka"=>"მეხორცე","name_en"=>"take care of me"),
            array("name_ru"=>"Повар","name_ka"=>"მზარეული","name_en"=>"cook"),
            array("name_ru"=>"Разведчик","name_ka"=>"მზვერავი","name_en"=>"scout"),
            array("name_ru"=>"Горнострелок","name_ka"=>"მთის მსროლელი","name_en"=>"Mountain shooter"),
            array("name_ru"=>"Горняк","name_ka"=>"მთის რესურსებზე მომუშავე","name_en"=>"Working on mountain resources"),
            array("name_ru"=>"Миколог","name_ka"=>"მიკოლოგი (კანი, ფრჩხილებსა და თმებზე სოკოს დიაგნოსტიკა მკურნალობა ),","name_en"=>"Mycologist (diagnosis and treatment of fungi on skin, nails and hair),"),
            array("name_ru"=>"Микробиолог","name_ka"=>"მიკრობიოლოგი","name_en"=>"microbiologist"),
            array("name_ru"=>"Официант","name_ka"=>"მიმტანი","name_en"=>"waitress"),
            array("name_ru"=>"Портье","name_ka"=>"მიმღები","name_en"=>"recipient"),
            array("name_ru"=>"Министр","name_ka"=>"მინისტრი","name_en"=>"Minister"),
            array("name_ru"=>"Землекоп","name_ka"=>"მიწათმოქმედი","name_en"=>"Farmer"),
            array("name_ru"=>"Швея","name_ka"=>"მკერავი","name_en"=>"tailor"),
            array("name_ru"=>"Портной","name_ka"=>"მკერავი","name_en"=>"tailor"),
            array("name_ru"=>"Фуражир","name_ka"=>"მკვებავი","name_en"=>"nutritious"),
            array("name_ru"=>"Заточник","name_ka"=>"მლესავი","name_en"=>"Mlesavi"),
            array("name_ru"=>"Модель","name_ka"=>"მოდელი","name_en"=>"model"),
            array("name_ru"=>"Жиловщик/Обвальщик","name_ka"=>"მოიჯარე/დებონერი","name_en"=>"Lessee/Deboner"),
            array("name_ru"=>"Кассир","name_ka"=>"მოლარე","name_en"=>"Cashier"),
            array("name_ru"=>"Шлифовщик","name_ka"=>"მომპირკეთებელი","name_en"=>"paver"),
            array("name_ru"=>"Певец (певчий церковного хора),","name_ka"=>"მომღერალი (საეკლესიო გუნდის მომღერალი),","name_en"=>"singer (church choir singer),"),
            array("name_ru"=>"Тренд-вотчер","name_ka"=>"მომხმარებელთა ქცევის შესწავლის საფუძველზე კლიენტში ახალი საჭიროებების გამოვლენის სპეციალისტი Trend Watch","name_en"=>"Trend Watch A specialist in identifying new needs in the client based on the study of consumer behavior"),
            array("name_ru"=>"Администратор базы данных","name_ka"=>"მონაცემთა ბაზის ადმინისტრატორი","name_en"=>"Database Administrator"),
            array("name_ru"=>"Формовщик","name_ka"=>"მორდერი","name_en"=>"Morder"),
            array("name_ru"=>"Мотострелок","name_ka"=>"მოტო მსროლელი","name_en"=>"Moto shooter"),
            array("name_ru"=>"Моторист","name_ka"=>"მოტორისტი","name_en"=>"Motorist"),
            array("name_ru"=>"Моторист","name_ka"=>"მოტორისტი","name_en"=>"Motorist"),
            array("name_ru"=>"Скульптор","name_ka"=>"მოქანდაკე","name_en"=>"Sculptor"),
            array("name_ru"=>"Танцор","name_ka"=>"მოცეკვავე","name_en"=>"a dancer"),
            array("name_ru"=>"Сестра милосердия","name_ka"=>"მოწყალების და","name_en"=>"Sister of mercy"),
            array("name_ru"=>"Стрелок","name_ka"=>"მსროლელი","name_en"=>"shooter"),
            array("name_ru"=>"Музыкант","name_ka"=>"მუსიკოსი","name_en"=>"a musician"),
            array("name_ru"=>"Маляр","name_ka"=>"მღებავი","name_en"=>"Painter"),
            array("name_ru"=>"Водолаз","name_ka"=>"მყვინთავი","name_en"=>"diver"),
            array("name_ru"=>"Строитель","name_ka"=>"მშენებელი","name_en"=>"builder"),
            array("name_ru"=>"Агроном по защите растений","name_ka"=>"მცენარეთა დაცვის აგრონომი","name_en"=>"Plant protection agronomist"),
            array("name_ru"=>"Бахчевод","name_ka"=>"მცენარეთმცოდნე","name_en"=>"herbalist"),
            array("name_ru"=>"Пекарь","name_ka"=>"მცხობელი","name_en"=>"baker"),
            array("name_ru"=>"Водитель","name_ka"=>"მძღოლი","name_en"=>"driver"),
            array("name_ru"=>"Механик-Водитель","name_ka"=>"მძღოლის მექანიკოსი","name_en"=>"Driver mechanic"),
            array("name_ru"=>"Писатель","name_ka"=>"მწერალი","name_en"=>"writer"),
            array("name_ru"=>"Доярка","name_ka"=>"მწველავი","name_en"=>"burning"),
            array("name_ru"=>"Пастух","name_ka"=>"მწყემსი","name_en"=>"Shepherd"),
            array("name_ru"=>"Кузнец","name_ka"=>"მჭედელი","name_en"=>"Blacksmith"),
            array("name_ru"=>"Лекальщик","name_ka"=>"მხაზველი","name_en"=>"ruler"),
            array("name_ru"=>"Художник","name_ka"=>"მხატვარი","name_en"=>"artist"),
            array("name_ru"=>"Кавалерист","name_ka"=>"მხედარი","name_en"=>"rider"),
            array("name_ru"=>"Распиловщик","name_ka"=>"მხერხავი","name_en"=>"plow"),
            array("name_ru"=>"Штурман","name_ka"=>"ნავიგატორი","name_en"=>"navigator"),
            array("name_ru"=>"Нарколог","name_ka"=>"ნარკოლოგი","name_en"=>"Narcologist"),
            array("name_ru"=>"Невролог (специалист по заболеваниям нервной системы),","name_ka"=>"ნევროლოგი","name_en"=>"Neurologist"),
            array("name_ru"=>"Нейрохирург (хирург, выполняющий оперативное лечение заболеваний нервной системы),","name_ka"=>"ნეიროქირურგი","name_en"=>"Neurosurgeon"),
            array("name_ru"=>"Неонатолог","name_ka"=>"ნეონატოლოგი (ახალშობილობიდან 28 დღემდე ჩვილი ბავშვის ექიმი),","name_en"=>"Neonatologist (baby doctor from birth to 28 days),"),
            array("name_ru"=>"Нефролог (специалист по заболеваниям почек),","name_ka"=>"ნეფროლოგი (თირკმელების დაავადებების სპეციალისტი),","name_en"=>"Nephrologist (kidney disease specialist),"),
            array("name_ru"=>"Нотариус","name_ka"=>"ნოტარიუსი","name_en"=>"notary public"),
            array("name_ru"=>"Логопед","name_ka"=>"Ლოგოპედი","name_en"=>"Ლogopedi"),
            array("name_ru"=>"Океанолог","name_ka"=>"ოკეანოლოგი","name_en"=>"Oceanologist"),
            array("name_ru"=>"Полицейский","name_ka"=>"Პოლიციის ოფიცერი","name_en"=>"Police officer"),
            array("name_ru"=>"Онколог (лечит рак и другие онкологические заболевания),","name_ka"=>"ონკოლოგი (კიბოს და სხვა ონკოლოგიური დაავადებების ექიმი),","name_en"=>"Oncologist (doctor of cancer and other oncological diseases),"),
            array("name_ru"=>"Оперативный работник","name_ka"=>"ოპერატიული მუშაკი","name_en"=>"operative worker"),
            array("name_ru"=>"Операционист","name_ka"=>"ოპერაციონისტი (მაგ. საბანკო საქმიანობაში რაიმე სახის ოპერაციების შესრულება..),","name_en"=>"Operator (e.g. performing any kind of operations in banking...),"),
            array("name_ru"=>"Ортодонт (специалист в области зубо-челюстных аномалий),","name_ka"=>"ორთოდონტი (კბილებისა და ზოგადად პირის ღრუს ანომალიების სპეციალისტი),","name_en"=>"Orthodontist (specialist in teeth and oral anomalies in general),"),
            array("name_ru"=>"Ортопед (специалист в области лечения заболеваний костно-мышечной системы),","name_ka"=>"ორთოპედი (სახსრებისა და კუნთოვანი სისტემის დაავადებების სპეციალისტი),","name_en"=>"Orthopedist (specialist in diseases of the joints and musculoskeletal system),"),
            array("name_ru"=>"Орнитолог","name_ka"=>"ორნიტოლოგი (ფრინველების შემსწავლელი მეცნიერება),","name_en"=>"Ornithologist (bird science),"),
            array("name_ru"=>"Судья","name_ka"=>"Მოსამართლე","name_en"=>"The judge"),
            array("name_ru"=>"Оториноларинголог (ЛОР, специалист в области заболеваний уха, горла и носа),","name_ka"=>"ოტორინოლარინგოლოგი (ყელ, ყურ, ცხვირის დაავადებების სპეციალისტი),","name_en"=>"Otorhinolaryngologist (throat, ear, nose disease specialist),"),
            array("name_ru"=>"Офтальмолог (специалист по глазу),","name_ka"=>"ოფთალმოლოგი (თვალის სპეციალისტი),","name_en"=>"Ophthalmologist (eye specialist),"),
            array("name_ru"=>"Златокузнец","name_ka"=>"ოქრომჭედელი","name_en"=>"Goldsmith"),
            array("name_ru"=>"Семейный врач","name_ka"=>"ოჯახის ექიმი","name_en"=>"Family doctor"),
            array("name_ru"=>"домработница","name_ka"=>"ოჯახში დამხმარე","name_en"=>"Helper in the family"),
            array("name_ru"=>"Патологоанатом (специалист в области биопсийной диагностики и аутопсии),","name_ka"=>"პათოლოგოანატომი (ბიოფსიის დიაგნოსტიკისა და აუტოფსიის სპეციალისტი),","name_en"=>"Pathologist (biopsy diagnosis and autopsy specialist),"),
            array("name_ru"=>"Палеонтолог","name_ka"=>"პალეონტოლოგი","name_en"=>"Paleontologist"),
            array("name_ru"=>"Фельдшер","name_ka"=>"პარამედიკოსი/ფერშალი","name_en"=>"Paramedic/Fershal"),
            array("name_ru"=>"Парикмахер","name_ka"=>"პარიკმახერი","name_en"=>"hairdresser"),
            array("name_ru"=>"Парфюмер","name_ka"=>"პარფიუმერი","name_en"=>"perfume"),
            array("name_ru"=>"Педагог","name_ka"=>"პედაგოგი","name_en"=>"teacher"),
            array("name_ru"=>"Педиатр (врач, занимающийся профилактикой, диагностикой и лечением детских болезней),","name_ka"=>"პედიატრი (ბავშვთა დაავადებების პროფილაქტიკა-დიაგნოსტიკის ექიმი),","name_en"=>"Pediatrician (child disease prevention-diagnosis doctor),"),
            array("name_ru"=>"Мастер педикюра","name_ka"=>"პედიკურის ოსტატი","name_en"=>"Pedicure master"),
            array("name_ru"=>"Подолог (врач, занимающийся лечением ногтей),","name_ka"=>"პედიოლოგი (ფრჩხილების ექიმი),","name_en"=>"podiatrist (nail doctor),"),
            array("name_ru"=>"Лётчик","name_ka"=>"პილოტი","name_en"=>"pilot"),
            array("name_ru"=>"Лоцман","name_ka"=>"პილოტი","name_en"=>"pilot"),
            array("name_ru"=>"Лётчик","name_ka"=>"პილოტი","name_en"=>"pilot"),
            array("name_ru"=>"Телохранитель","name_ka"=>"პირადი მცველი","name_en"=>"bodyguard"),
            array("name_ru"=>"Пластический хирург","name_ka"=>"პლასტიკური ქირურგი","name_en"=>"plastic surgeon"),
            array("name_ru"=>"Поэт","name_ka"=>"პოეტი","name_en"=>"poet"),
            array("name_ru"=>"Политолог","name_ka"=>"პოლიტოლოგი","name_en"=>"Political scientist"),
            array("name_ru"=>"Программист","name_ka"=>"პროგრამისტი","name_en"=>"programmer"),
            array("name_ru"=>"Программист","name_ka"=>"პროგრამისტი","name_en"=>"programmer"),
            array("name_ru"=>"Прозектор","name_ka"=>"პროზექტორი (გვამების ექსპერტი),","name_en"=>"corpse examiner"),
            array("name_ru"=>"Прокурор","name_ka"=>"პროკურორი","name_en"=>"prosecutor"),
            array("name_ru"=>"Проректор","name_ka"=>"პრორექტორი","name_en"=>"Vice Chancellor"),
            array("name_ru"=>"Профпатолог","name_ka"=>"პროფ-პათოლოგი (სამსახურეობრივი, პროფესიული დაავადებების მკურნალობა),","name_en"=>"professional pathologist (treatment of occupational diseases),"),
            array("name_ru"=>"Проктолог","name_ka"=>"პროქტოლოგი (გემაროიდისა და სხვა მსგავსი ტიპის დაავადებების სპეციალისტი),","name_en"=>"Proctologist (specialist in hemorrhoids and other similar diseases),"),
            array("name_ru"=>"Пульмонолог (врач, занимающийся диагностикой, лечением и профилактикой болезней дыхательной системы),","name_ka"=>"პულმონოლოგი (სასუნთქი გზების დაავადებების სპეციალისტი),","name_en"=>"Pulmonologist (respiratory tract disease specialist),"),
            array("name_ru"=>"Хлебопёк","name_ka"=>"პურის მცხობელი","name_en"=>"bread baker"),
            array("name_ru"=>"Журналист","name_ka"=>"ჟურნალისტი","name_en"=>"Journalist"),
            array("name_ru"=>"Оператор РЛС","name_ka"=>"რადარის ოპერატორი","name_en"=>"Radar operator"),
            array("name_ru"=>"Радиомеханик","name_ka"=>"რადიო მექანიკი","name_en"=>"radio mechanic"),
            array("name_ru"=>"Радист","name_ka"=>"რადიო ოპერატორი","name_en"=>"radio operator"),
            array("name_ru"=>"Радиолог","name_ka"=>"რადიოლოგი (სხივოთერაპიით მკურნალი),","name_en"=>"Radiologist (radiotherapy),"),
            array("name_ru"=>"Радист","name_ka"=>"რადიოოპერატორი","name_en"=>"radio operator"),
            array("name_ru"=>"Радиотелефонист","name_ka"=>"რადიოტელეფონისტი","name_en"=>"Radio operator"),
            array("name_ru"=>"Ракетчик","name_ka"=>"რაკეტატორი","name_en"=>"Rocketeer"),
            array("name_ru"=>"Реаниматолог","name_ka"=>"რეანიმატოლოგი","name_en"=>"Reanimatologist"),
            array("name_ru"=>"Регент","name_ka"=>"რეგენტი","name_en"=>"regent"),
            array("name_ru"=>"Редактор (профессия),","name_ka"=>"რედაქტორი","name_en"=>"editor"),
            array("name_ru"=>"Работник органов ЗАГСа","name_ka"=>"რეესტრის ოფისის თანამშრომელი","name_en"=>"An employee of the registry office"),
            array("name_ru"=>"Ревматолог (специалист по аутоиммунным заболеваниям суставов и соединительной ткани),","name_ka"=>"რევმატოლოგი (სახსრებისა და შემაერთებელი ქსოვილის აუტოიმუნური დაავადებების სპეციალისტი),","name_en"=>"Rheumatologist (specialist in autoimmune diseases of joints and connective tissue),"),
            array("name_ru"=>"Дизайнер рекламы","name_ka"=>"რეკლამის დიზაინერი","name_en"=>"Advertising designer"),
            array("name_ru"=>"Релайтер","name_ka"=>"რელაიტერი (რთულ ტექსტებში სიტყვათ ცვლილებების შემდგენი),","name_en"=>"Rewriter (compiler of word changes in complex texts),"),
            array("name_ru"=>"Религиовед","name_ka"=>"რელიგიათმცოდნე","name_en"=>"Religious scholar"),
            array("name_ru"=>"Рентгенолог","name_ka"=>"რენტგენოლოგი","name_en"=>"Radiologist"),
            array("name_ru"=>"Репродуктолог","name_ka"=>"რეპროდუქტოლოგი","name_en"=>"Reproductologist"),
            array("name_ru"=>"Режиссёр","name_ka"=>"რეჟისორი","name_en"=>"director"),
            array("name_ru"=>"Реставратор","name_ka"=>"რესტავრატორი","name_en"=>"Restaurateur"),
            array("name_ru"=>"Ректор","name_ka"=>"რექტორი","name_en"=>"Rector"),
            array("name_ru"=>"Робототехник","name_ka"=>"რობოტიკა","name_en"=>"Robotics"),
            array("name_ru"=>"Продюсер","name_ka"=>"Პროდიუსერი","name_en"=>"Producer"),
            array("name_ru"=>"Копирайтер","name_ka"=>"საავტორო უფლებები","name_en"=>"Copyright"),
            array("name_ru"=>"Борт-радист","name_ka"=>"საბორტო რადიოოპერატორი","name_en"=>"on-board radio operator"),
            array("name_ru"=>"Налоговый инспектор","name_ka"=>"საგადასახადო ინსპექტორი","name_en"=>"Tax inspector"),
            array("name_ru"=>"Страховой агент","name_ka"=>"სადაზღვეო აგენტი","name_en"=>"Insurance agent"),
            array("name_ru"=>"Морской пехотинец","name_ka"=>"საზღვაო ქვეითი","name_en"=>"Marine"),
            array("name_ru"=>"Кредитный консультант","name_ka"=>"საკრედიტო მრჩეველი","name_en"=>"Credit Counselor"),
            array("name_ru"=>"Правовед","name_ka"=>"სამართალმწარმოებელი","name_en"=>"litigator"),
            array("name_ru"=>"Корректировщик","name_ka"=>"სამიზნის მაკორექტირებელი","name_en"=>"Aim corrector"),
            array("name_ru"=>"Промышленный альпинист","name_ka"=>"სამრეწველო ალპინისტი","name_en"=>"Industrial climber"),
            array("name_ru"=>"Промышленный альпинист","name_ka"=>"სამრეწველო მთამსვლელი","name_en"=>"Industrial climber"),
            array("name_ru"=>"Начальник службы","name_ka"=>"სამსახურის უფროსი","name_en"=>"Head of Service"),
            array("name_ru"=>"Военный дознаватель","name_ka"=>"სამხედრო გამომძიებელი","name_en"=>"Military investigator"),
            array("name_ru"=>"Военный переводчик","name_ka"=>"სამხედრო თარჯიმანი","name_en"=>"Military interpreter"),
            array("name_ru"=>"Военный юрист","name_ka"=>"სამხედრო იურისტი","name_en"=>"Military lawyer"),
            array("name_ru"=>"Военный консультант","name_ka"=>"სამხედრო კონსულტანტი","name_en"=>"Military consultant"),
            array("name_ru"=>"Военный судья","name_ka"=>"სამხედრო მოსამართლე","name_en"=>"military judge"),
            array("name_ru"=>"Военнослужащий","name_ka"=>"სამხედრო მოსამსახურე","name_en"=>"Military personnel"),
            array("name_ru"=>"Начальник военного оркестра","name_ka"=>"სამხედრო ორკესტრის ხელმძღვანელი","name_en"=>"Head of the military orchestra"),
            array("name_ru"=>"Военный полицейский","name_ka"=>"სამხედრო პოლიციელი","name_en"=>"military policeman"),
            array("name_ru"=>"Военный прокурор","name_ka"=>"სამხედრო პროკურორი","name_en"=>"Military prosecutor"),
            array("name_ru"=>"Военно-полевой хирург","name_ka"=>"სამხედრო საველე ქირურგი","name_en"=>"Military Field Surgeon"),
            array("name_ru"=>"Военно-полевой хирург","name_ka"=>"სამხედრო-საველე ქირურგი","name_en"=>"Military field surgeon"),
            array("name_ru"=>"Сантехник","name_ka"=>"სანტექნიკи","name_en"=>"plumbing"),
            array("name_ru"=>"Судебный пристав","name_ka"=>"სასამართლო აღმასრულებელი","name_en"=>"Bailiff"),
            array("name_ru"=>"Врач скорой медицинской помощи","name_ka"=>"სასწრაფო სამედიცინო დახმარების ექიმი","name_en"=>"Emergency medical doctor"),
            array("name_ru"=>"Телефонист","name_ka"=>"სატელეფონო ოპერატორი","name_en"=>"Telephone operator"),
            array("name_ru"=>"Маркитант","name_ka"=>"სატლერი","name_en"=>"Sutler"),
            array("name_ru"=>"Маклер биржевой","name_ka"=>"საფონდო ბროკერი","name_en"=>"stock broker"),
            array("name_ru"=>"Экспедитор на дальних поездках","name_ka"=>"საქალაქთაშორისო ექსპედიტორი","name_en"=>"Long distance freight forwarder"),
            array("name_ru"=>"Товаровед","name_ka"=>"საქონელთმცოდნე","name_en"=>"Commodity expert"),
            array("name_ru"=>"Фрезеровщик","name_ka"=>"საღარავი მანქანის ოპერატორი","name_en"=>"Milling machine operator"),
            array("name_ru"=>"Кладовщик","name_ka"=>"საწყობის გამგე","name_en"=>"Warehouse Manager"),
            array("name_ru"=>"Начальник склада","name_ka"=>"საწყობის უფროსი","name_en"=>"Warehouse Manager"),
            array("name_ru"=>"Государственный исполнитель","name_ka"=>"სახელმწიფო აღმასრულებელი","name_en"=>"State executive"),
            array("name_ru"=>"Актёр","name_ka"=>"Მსახიობი","name_en"=>"Beautiful"),
            array("name_ru"=>"Кровельщик","name_ka"=>"სახურავების (გადახურვის), სპეციალისტი","name_en"=>"Roofing specialist"),
            array("name_ru"=>"Воздухоплаватель","name_ka"=>"საჰაერო ხომალდის თანამშრომელი","name_en"=>"Aircraft employee"),
            array("name_ru"=>"Животновод","name_ka"=>"სელექციონერი","name_en"=>"Breeder"),
            array("name_ru"=>"Серпентолог","name_ka"=>"სერპენტოლოგი","name_en"=>"Serpentologist"),
            array("name_ru"=>"Сексолог","name_ka"=>"სექსოლოგი","name_en"=>"sexologist"),
            array("name_ru"=>"Сексопатолог","name_ka"=>"სექსოპათოლოგი","name_en"=>"Sexopathologist"),
            array("name_ru"=>"Пономарь (алтарник),","name_ka"=>"სექსტონი (საკურთხევლის ბიჭი),","name_en"=>"sexton (altar boy),"),
            array("name_ru"=>"Инженер-системотехник","name_ka"=>"სისტემების ინჟინერი","name_en"=>"Systems Engineer"),
            array("name_ru"=>"Системный администратор","name_ka"=>"სისტემური ადმინისტრატორი","name_en"=>"system administrator"),
            array("name_ru"=>"Снайпер","name_ka"=>"სნაიპერი","name_en"=>"Sniper"),
            array("name_ru"=>"Сомелье","name_ka"=>"სომელიე","name_en"=>"Sommelier"),
            array("name_ru"=>"Сомнолог","name_ka"=>"სომნოლოგი (ძილის დარღვევის სპეციალისტი),","name_en"=>"Somnologist (sleep disorder specialist),"),
            array("name_ru"=>"Социолог","name_ka"=>"სოციოლოგი","name_en"=>"Sociologist"),
            array("name_ru"=>"Спортивный врач","name_ka"=>"სპორტის ექიმი","name_en"=>"Sports doctor"),
            array("name_ru"=>"Стилист","name_ka"=>"სტილისტი","name_en"=>"stylist"),
            array("name_ru"=>"Парикмахер","name_ka"=>"სტილისტი/პარიკმახერი","name_en"=>"Stylist/Hairdresser"),
            array("name_ru"=>"Стоматолог (специалист по зубам, не путать с зубным врачом),","name_ka"=>"სტომატოლოგი","name_en"=>"Dentist"),
            array("name_ru"=>"Кинодраматург","name_ka"=>"სცენარისტი","name_en"=>"Screenwriter"),
            array("name_ru"=>"Сценарист","name_ka"=>"სცენარისტი","name_en"=>"Screenwriter"),
            array("name_ru"=>"Тальман","name_ka"=>"ტალმანი","name_en"=>"Tallman"),
            array("name_ru"=>"Танкист","name_ka"=>"ტანკისტი","name_en"=>"Tanker"),
            array("name_ru"=>"Татуировщик","name_ka"=>"ტატუს მხატვარი","name_en"=>"tattoo artist"),
            array("name_ru"=>"Телеграфист","name_ka"=>"ტელეგრაფისტი","name_en"=>"Telegraphist"),
            array("name_ru"=>"Телемастер","name_ka"=>"ტელემაისტერი","name_en"=>"Telemaster"),
            array("name_ru"=>"Тележурналист","name_ka"=>"ტელეჟურნალისტი","name_en"=>"TV journalist"),
            array("name_ru"=>"Териолог","name_ka"=>"ტერიოლოგია (ძუძუმწოვრების შემსწავლელი მეცნიერება),","name_en"=>"Teriology (Mammal Science),"),
            array("name_ru"=>"Тестировщик","name_ka"=>"ტესტერი","name_en"=>"tester"),
            array("name_ru"=>"Техник","name_ka"=>"ტექნიკოსი","name_en"=>"Technician"),
            array("name_ru"=>"Техник","name_ka"=>"ტექნიკოსი","name_en"=>"Technician"),
            array("name_ru"=>"Технолог","name_ka"=>"ტექნოლოგი","name_en"=>"technologist"),
            array("name_ru"=>"Плиточник","name_ka"=>"ტილერი","name_en"=>"Tiller"),
            array("name_ru"=>"Типограф (профессия),","name_ka"=>"ტიპოგრაფი","name_en"=>"Typographer"),
            array("name_ru"=>"Тифлопедагог","name_ka"=>"ტიფლოპედაგოგი","name_en"=>"Typhlopedagogue"),
            array("name_ru"=>"Токарь","name_ka"=>"ტოკარი","name_en"=>"Tokar"),
            array("name_ru"=>"Топограф","name_ka"=>"ტოპოგრაფი","name_en"=>"topographer"),
            array("name_ru"=>"Торседор","name_ka"=>"ტორსედორი","name_en"=>"torcador"),
            array("name_ru"=>"Токсиколог (врач, биолог или химик, специалист в области токсикологии),","name_ka"=>"ტოქსიკოლოგი (ექიმი, ბიოლოგი ან ქიმიკოსი, ტოქსიკოლოგიის დარგის სპეციალისტი),","name_en"=>"Toxicologist (doctor, biologist or chemist, specialist in the field of toxicology),"),
            array("name_ru"=>"Травматолог","name_ka"=>"ტრავმატოლოგი","name_en"=>"Traumatologist"),
            array("name_ru"=>"Трансфузиолог","name_ka"=>"ტრანსფუზიოლოგი (სისხლის პლაზმის ანომალიის სპეციალისტი),","name_en"=>"Transfusiologist (blood plasma anomaly specialist),"),
            array("name_ru"=>"Тракторист","name_ka"=>"ტრაქტორის მძღოლი","name_en"=>"Tractor driver"),
            array("name_ru"=>"Трейдер","name_ka"=>"ტრეიდერი","name_en"=>"trader"),
            array("name_ru"=>"Постановщик трюков","name_ka"=>"ტრიუკების დამდგმელი","name_en"=>"Stunt maker"),
            array("name_ru"=>"Трихолог (специалист по волосам и волосистой части кожи головы),","name_ka"=>"ტრიქოლოგი (თმის და თავზე თმისმაგვარი ქსოვილების სპეციალისტი),","name_en"=>"Trichologist (specialist in hair and hair-like tissues on the head),"),
            array("name_ru"=>"Врач УЗ-диагностики","name_ka"=>"ულტრაბგერითი დიაგნოსტიკის ექიმი","name_en"=>"Doctor of ultrasound diagnostics"),
            array("name_ru"=>"Безработный","name_ka"=>"უმუშევარი","name_en"=>"unemployed"),
            array("name_ru"=>"Уролог (специалист по заболеваниям репродуктивного органа у мужчин),","name_ka"=>"უროლოგი (მამაკაცებში რეპროდუქციული ორგანოების დაავადებების სპეციალისტი),","name_en"=>"Urologist (specialist in diseases of male reproductive organs),"),
            array("name_ru"=>"Инженер по Технике Безопасности","name_ka"=>"უსაფრთხოების ინჟინერი","name_en"=>"Safety Engineer"),
            array("name_ru"=>"Специалист по клеточным технологиям","name_ka"=>"უჯრედული ტექნოლოგიების სპეციალისტი","name_en"=>"Cell technology specialist"),
            array("name_ru"=>"Фармацевт","name_ka"=>"ფარმაცევტი","name_en"=>"Pharmacist"),
            array("name_ru"=>"Фермер","name_ka"=>"ფერმერი","name_en"=>"farmer"),
            array("name_ru"=>"Фельдшер (врач, проводит диагностику, лечение или направляет пациентов к соотв. специалисту),","name_ka"=>"ფერშალი (სპეციალისტი, რომელიც ახდენს მკურნალობის დიაგნოსტიკას ან ამისამართებს პაციენტებს შესაბამის სპეციალისტთან),.","name_en"=>"Fershal (a specialist who diagnoses treatment or refers patients to the appropriate specialist),."),
            array("name_ru"=>"Сапожник","name_ka"=>"ფეხსაცმლის შემკეთებელი","name_en"=>"Shoe repairer"),
            array("name_ru"=>"Флеболог","name_ka"=>"ფიბოლოგი (ქვედა კიდურებზე ვენური დაავადებების სპეციალისტი),","name_en"=>"Phybologist (specialist in venous diseases of the lower limbs),"),
            array("name_ru"=>"Физик","name_ka"=>"ფიზიკოსი","name_en"=>"Physicist"),
            array("name_ru"=>"Физиотерапевт","name_ka"=>"ფიზიოთერაპევტი","name_en"=>"Physiotherapist"),
            array("name_ru"=>"Филолог","name_ka"=>"ფილოლოგი","name_en"=>"Philologist"),
            array("name_ru"=>"Философ","name_ka"=>"ფილოსოფოსი","name_en"=>"philosopher"),
            array("name_ru"=>"Финансист","name_ka"=>"ფინანსისტი","name_en"=>"financier"),
            array("name_ru"=>"Почтальон","name_ka"=>"ფოსტალიონი","name_en"=>"Postman"),
            array("name_ru"=>"Фотомодель","name_ka"=>"ფოტო მოდელი","name_en"=>"Photo model"),
            array("name_ru"=>"Фотограф","name_ka"=>"ფოტოგრაფი","name_en"=>"photographer"),
            array("name_ru"=>"Бортинженер","name_ka"=>"ფრენის ინჟინერი","name_en"=>"flight engineer"),
            array("name_ru"=>"Психиатр (специалист по психическим расстройствам),","name_ka"=>"ფსიქიატრი (ფსიქიკური აშლილობის სპეციალისტი),","name_en"=>"Psychiatrist (specialist in mental disorders),"),
            array("name_ru"=>"Психотерапевт","name_ka"=>"ფსიქოთერაპევტი","name_en"=>"Psychotherapist"),
            array("name_ru"=>"Психолог","name_ka"=>"ფსიქოლოგი","name_en"=>"Psychologist"),
            array("name_ru"=>"Психоневропатолог","name_ka"=>"ფსიქონევროპათოლოგი","name_en"=>"Psychoneuropathologist"),
            array("name_ru"=>"Фтизиатр (специалист по туберкулёзу),","name_ka"=>"ფტიზიატრი (ტუბერკულოზის სპეციალისტი),","name_en"=>"phtisiatrist (tuberculosis specialist),"),
            array("name_ru"=>"Врач функциональной диагностики","name_ka"=>"ფუნქციური დიაგნოსტიკის ექიმი","name_en"=>"Functional diagnostics doctor"),
            array("name_ru"=>"Футуролог","name_ka"=>"ფუტუროლოგია (სხვადასხვა გამოთვლებზე დაყრდნობით მომავლის წინასწარმეტყველება),","name_en"=>"Futurology (prediction of the future based on various calculations),"),
            array("name_ru"=>"Каменотёс","name_ka"=>"ქვაზე მომუშავე","name_en"=>"stone worker"),
            array("name_ru"=>"Химик-технолог","name_ka"=>"ქიმიკოს ტექნოლოგი","name_en"=>"Chemist Technologist"),
            array("name_ru"=>"Химик","name_ka"=>"ქიმიკოსი","name_en"=>"chemist"),
            array("name_ru"=>"Химик-контролер","name_ka"=>"ქიმიკოსი-კონტროლიორი","name_en"=>"Chemist-controller"),
            array("name_ru"=>"Хирург (специалист по методам диагностики и хирургического лечения заболеваний и травм),","name_ka"=>"ქირურგი","name_en"=>"surgeon"),
            array("name_ru"=>"Месильщик","name_ka"=>"ქნედერი","name_en"=>"Kneder"),
            array("name_ru"=>"Оператор коллцентра","name_ka"=>"ქოლ ცენტრის ოპერატორი","name_en"=>"call center operator"),
            array("name_ru"=>"Балетмейстер","name_ka"=>"ქორეოგრაფი","name_en"=>"Choreographer"),
            array("name_ru"=>"Хореограф","name_ka"=>"ქორეოგრაფი","name_en"=>"Choreographer"),
            array("name_ru"=>"Организатор свадеб","name_ka"=>"ქორწილის დამგეგმავი","name_en"=>"A wedding planner"),
            array("name_ru"=>"Священник","name_ka"=>"Მღვდელი","name_en"=>"the priest"),
            array("name_ru"=>"Кнопочник (заклёпочник, мастер-специалист по замене и установке швейной и кожгалантерейной металлофурнитуры),","name_ka"=>"ღილაკების დამამზადებელი (რივეტერი, ოსტატი სამკერვალო და ტყავის ნაწარმის ტექნიკის გამოცვლა-მონტაჟისა),","name_en"=>"Button maker (riveter, master of sewing and leather goods equipment replacement-installation),"),
            array("name_ru"=>"Свинопас","name_ka"=>"ღორის მწყემსი","name_en"=>"Pig shepherd"),
            array("name_ru"=>"Сыровар","name_ka"=>"ყველის მწარმოებელი","name_en"=>"cheese maker"),
            array("name_ru"=>"Сурдопедагог","name_ka"=>"ყრუ-მუნჯთა მასწავლებელი","name_en"=>"Teacher of the Deaf"),
            array("name_ru"=>"Гранатомётчик","name_ka"=>"ყუმბარმტყორცნი","name_en"=>"grenade launcher"),
            array("name_ru"=>"Сварщик","name_ka"=>"შემდუღებელი","name_en"=>"Welder"),
            array("name_ru"=>"Сметчик","name_ka"=>"შემფასებელი (სამშენებლო-სარემონტო სამუძშაოების აღრიცვდა-შეფასება),","name_en"=>"Assessor (assessment of construction and repair works),"),
            array("name_ru"=>"Упаковщик","name_ka"=>"შემფუთავი","name_en"=>"the packer"),
            array("name_ru"=>"Снабженец","name_ka"=>"შესყიდვების მენეჯერი (მომმარაგებელი),","name_en"=>"Purchasing manager (supplier),"),
            array("name_ru"=>"Литейщик","name_ka"=>"ჩამომსხმელი","name_en"=>"the bottler"),
            array("name_ru"=>"Грузчик","name_ka"=>"ჩამტვირთავი","name_en"=>"loader"),
            array("name_ru"=>"Огнемётчик","name_ka"=>"ცეცხლმსროლელი","name_en"=>"Flamethrower"),
            array("name_ru"=>"Артист цирка","name_ka"=>"ცირკის შემსრულებელი","name_en"=>"Circus performer"),
            array("name_ru"=>"Тюремный надзиратель","name_ka"=>"ციხის თანამშრომელი","name_en"=>"Prison employee"),
            array("name_ru"=>"Табунщик","name_ka"=>"ცხენების მწყემსი","name_en"=>"A shepherd of horses"),
            array("name_ru"=>"Коневод","name_ka"=>"ცხენის გამომშენებელი","name_en"=>"Horse breeder"),
            array("name_ru"=>"Специалист по стрижке овец","name_ka"=>"ცხვრის პარსვის სპეციალისტი","name_en"=>"Sheep shearing specialist"),
            array("name_ru"=>"Няня","name_ka"=>"ძიძა","name_en"=>"babysitter"),
            array("name_ru"=>"Подводник","name_ka"=>"წყალქვეშა ნავის თანამშრომელი","name_en"=>"Submarine employee"),
            array("name_ru"=>"Иконописец","name_ka"=>"ხატმწერი","name_en"=>"icon painter"),
            array("name_ru"=>"Искусствовед","name_ka"=>"ხელოვნებათმცოდნე","name_en"=>"Art critic"),
            array("name_ru"=>"Звукорежиссёр","name_ka"=>"ხმის რეჟისორი","name_en"=>"sound director"),
            array("name_ru"=>"Начальник гаупвахты","name_ka"=>"ჰაუპტვახტის უფროსი","name_en"=>"Chief of Hauptwacht"),
            array("name_ru"=>"Гематолог (специалист по крови и органам кроветворения),","name_ka"=>"ჰემატოლოგი (სისხლის შემსწავლელი სპეციალისტი),","name_en"=>"Hematologist (blood specialist),"),
            array("name_ru"=>"Гепатолог (специалист по человеческой печени),","name_ka"=>"ჰეპატოლოგი (ადამიანის ღვიძლის სპეციალისტი),","name_en"=>"Hepatologist (human liver specialist),"),
            array("name_ru"=>"Инженер-гидравлик","name_ka"=>"ჰიდრავლიკური ინჟინერი","name_en"=>"Hydraulic engineer"),
            array("name_ru"=>"Гидролог","name_ka"=>"ჰიდროლოგი","name_en"=>"Hydrologist"),
            array("name_ru"=>"Гирудотерапевт","name_ka"=>"ჰირუდოთერაპია","name_en"=>"Hirudotherapy"),
            array("name_ru"=>"Гомеопат (врач, использующий в качестве лечения другие средства: животные, растительные и минеральные. Лечит не определённые заболевания, а скорее всего́ человека и его иммунную систему),","name_ka"=>"ჰომეოპათი (ექიმი, რომელიც იყენებს სხვა სამკურნალო საშუალებებს: ცხოველები, მცენარეები, მინერალები. ის მკურნალობს არა გარკვეულ დაავადებებს, არამედ ადამიანის იმუნურ სისტემას),","name_en"=>"Homeopath (a doctor who uses other remedies: animals, plants, minerals. He treats not certain diseases, but the human immune system),"),
            array("name_ru"=>"Метрдотель","name_ka"=>"ჰოსტესი","name_en"=>"Hostess"),
        );
        DB::table('professions')->insert($data);
    }
}
