<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('skills')->delete();
        $data = array(
            array("name_ka"=>"1 თვიდან 2 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 2 months","name_ru"=>"Полный уход за ребенком от 1 до 2 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 3 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 3 months","name_ru"=>"Полный уход за ребенком от 1 до 3 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 4 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 4 months","name_ru"=>"Полный уход за ребенком от 1 до 4 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 5 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 5 months","name_ru"=>"Полный уход за ребенком от 1 до 5 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 6 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 6 months","name_ru"=>"Полный уход за ребенком от 1 до 6 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 7 months","name_ru"=>"Полный уход за ребенком от 1 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 8 months","name_ru"=>"Полный уход за ребенком от 1 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 9 months","name_ru"=>"Полный уход за ребенком от 1 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 10 months","name_ru"=>"Полный уход за ребенком от 1 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 to 11 months","name_ru"=>"Полный уход за ребенком от 1 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 3 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 3 months","name_ru"=>"Полный уход за ребенком от 2 до 3 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 4 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 4 months","name_ru"=>"Полный уход за ребенком от 2 до 4 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 5 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 5 months","name_ru"=>"Полный уход за ребенком от 2 до 5 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 6 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 6 months","name_ru"=>"Полный уход за ребенком от 2 до 6 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 7 months","name_ru"=>"Полный уход за ребенком от 2 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 8 months","name_ru"=>"Полный уход за ребенком от 2 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 9 months","name_ru"=>"Полный уход за ребенком от 2 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 10 months","name_ru"=>"Полный уход за ребенком от 2 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 to 11 months","name_ru"=>"Полный уход за ребенком от 2 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 4 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 4 months","name_ru"=>"Полный уход за ребенком от 3 до 4 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 5 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 5 months","name_ru"=>"Полный уход за ребенком от 3 до 5 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 6 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 6 months","name_ru"=>"Полный уход за ребенком от 3 до 6 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 7 months","name_ru"=>"Полный уход за ребенком от 3 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 8 months","name_ru"=>"Полный уход за ребенком от 3 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 9 months","name_ru"=>"Полный уход за ребенком от 3 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 10 months","name_ru"=>"Полный уход за ребенком от 3 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 to 11 months","name_ru"=>"Полный уход за ребенком от 3 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 5 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 5 months","name_ru"=>"Полный уход за ребенком от 4 до 5 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 6 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 6 months","name_ru"=>"Полный уход за ребенком от 4 до 6 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 7 months","name_ru"=>"Полный уход за ребенком от 4 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 8 months","name_ru"=>"Полный уход за ребенком от 4 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 9 months","name_ru"=>"Полный уход за ребенком от 4 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 10 months","name_ru"=>"Полный уход за ребенком от 4 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 to 11 months","name_ru"=>"Полный уход за ребенком от 4 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 6 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 6 months","name_ru"=>"Полный уход за ребенком от 5 до 6 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 7 months","name_ru"=>"Полный уход за ребенком от 5 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 8 months","name_ru"=>"Полный уход за ребенком от 5 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 9 months","name_ru"=>"Полный уход за ребенком от 5 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 10 months","name_ru"=>"Полный уход за ребенком от 5 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 to 11 months","name_ru"=>"Полный уход за ребенком от 5 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 7 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 to 7 months","name_ru"=>"Полный уход за ребенком от 6 до 7 месяцев","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 to 8 months","name_ru"=>"Полный уход за ребенком от 6 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 to 9 months","name_ru"=>"Полный уход за ребенком от 6 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 to 10 months","name_ru"=>"Полный уход за ребенком от 6 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 to 11 months","name_ru"=>"Полный уход за ребенком от 6 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 8 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 to 8 months","name_ru"=>"Полный уход за ребенком от 7 до 8 месяцев","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 to 9 months","name_ru"=>"Полный уход за ребенком от 7 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 to 10 months","name_ru"=>"Полный уход за ребенком от 7 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 to 11 months","name_ru"=>"Полный уход за ребенком от 7 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 9 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 to 9 months","name_ru"=>"Полный уход за ребенком от 8 до 9 месяцев","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 to 10 months","name_ru"=>"Полный уход за ребенком от 8 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 to 11 months","name_ru"=>"Полный уход за ребенком от 8 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 10 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 to 10 months","name_ru"=>"Полный уход за ребенком от 9 до 10 месяцев","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 to 11 months","name_ru"=>"Полный уход за ребенком от 9 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 11 თვემდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 to 11 months","name_ru"=>"Полный уход за ребенком от 10 до 11 месяцев","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 1 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 1 года","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 2 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 2 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 3 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 3 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 4 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 4 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 5 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 5 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 6 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 6 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 7 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 7 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 8 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 8 лет","category_id"=>"1"),
            array("name_ka"=>"1 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 1 month to 9 year","name_ru"=>"Полный уход за ребенком от 1 месяца до 9 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 1 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 2 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 3 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 4 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 5 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 6 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 7 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 8 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"2 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 2 month to 9 year","name_ru"=>"Полный уход за ребенком от 2 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 1 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 2 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 3 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 4 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 5 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 6 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 7 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 8 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"3 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 3 month to 9 year","name_ru"=>"Полный уход за ребенком от 3 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 1 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 2 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 3 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 4 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 5 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 6 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 7 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 8 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"4 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 4 month to 9 year","name_ru"=>"Полный уход за ребенком от 4 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 1 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 2 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 3 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 4 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 5 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 6 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 7 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 8 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"5 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 5 month to 9 year","name_ru"=>"Полный уход за ребенком от 5 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 1 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 2 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 3 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 4 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 5 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 6 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 7 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 8 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"6 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 6 month to 9 year","name_ru"=>"Полный уход за ребенком от 6 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 1 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 2 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 3 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 4 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 5 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 6 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 7 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 8 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"7 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 7 month to 9 year","name_ru"=>"Полный уход за ребенком от 7 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 1 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 2 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 3 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 4 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 5 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 6 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 7 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 8 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"8 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 8 month to 9 year","name_ru"=>"Полный уход за ребенком от 8 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 1 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 2 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 3 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 4 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 5 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 6 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 7 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 8 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"9 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 9 month to 9 year","name_ru"=>"Полный уход за ребенком от 9 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 1 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 1 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 1 года","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 2 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 2 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 3 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 3 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 4 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 4 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 5 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 5 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 6 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 6 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 7 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 7 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 8 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 8 лет","category_id"=>"1"),
            array("name_ka"=>"10 თვიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a baby from 10 month to 9 year","name_ru"=>"Полный уход за ребенком от 10 месяцев до 9 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 2 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 2 years old","name_ru"=>"Полный уход за ребенком от 1 до 2 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 3 years old","name_ru"=>"Полный уход за ребенком от 1 до 3 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 4 years old","name_ru"=>"Полный уход за ребенком от 1 до 4 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 5 years old","name_ru"=>"Полный уход за ребенком от 1 до 5 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 6 years old","name_ru"=>"Полный уход за ребенком от 1 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 7 years old","name_ru"=>"Полный уход за ребенком от 1 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 8 years old","name_ru"=>"Полный уход за ребенком от 1 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"1 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 1 to 9 years old","name_ru"=>"Полный уход за ребенком от 1 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 3 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 3 years old","name_ru"=>"Полный уход за ребенком от 2 до 3 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 4 years old","name_ru"=>"Полный уход за ребенком от 2 до 4 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 5 years old","name_ru"=>"Полный уход за ребенком от 2 до 5 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 6 years old","name_ru"=>"Полный уход за ребенком от 2 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 7 years old","name_ru"=>"Полный уход за ребенком от 2 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 8 years old","name_ru"=>"Полный уход за ребенком от 2 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"2 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 2 to 9 years old","name_ru"=>"Полный уход за ребенком от 2 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 4 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 4 years old","name_ru"=>"Полный уход за ребенком от 3 до 4 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 5 years old","name_ru"=>"Полный уход за ребенком от 3 до 5 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 6 years old","name_ru"=>"Полный уход за ребенком от 3 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 7 years old","name_ru"=>"Полный уход за ребенком от 3 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 8 years old","name_ru"=>"Полный уход за ребенком от 3 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"3 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 3 to 9 years old","name_ru"=>"Полный уход за ребенком от 3 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"4 წლიდან 5 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 4 to 5 years old","name_ru"=>"Полный уход за ребенком от 4 до 5 лет","category_id"=>"1"),
            array("name_ka"=>"4 წლიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 4 to 6 years old","name_ru"=>"Полный уход за ребенком от 4 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"4 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 4 to 7 years old","name_ru"=>"Полный уход за ребенком от 4 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"4 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 4 to 8 years old","name_ru"=>"Полный уход за ребенком от 4 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"4 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 4 to 9 years old","name_ru"=>"Полный уход за ребенком от 4 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"5 წლიდან 6 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 5 to 6 years old","name_ru"=>"Полный уход за ребенком от 5 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"5 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 5 to 7 years old","name_ru"=>"Полный уход за ребенком от 5 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"5 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 5 to 8 years old","name_ru"=>"Полный уход за ребенком от 5 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"5 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 5 to 9 years old","name_ru"=>"Полный уход за ребенком от 5 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"6 წლიდან 7 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 6 to 7 years old","name_ru"=>"Полный уход за ребенком от 6 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"6 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 6 to 8 years old","name_ru"=>"Полный уход за ребенком от 6 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"6 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 6 to 9 years old","name_ru"=>"Полный уход за ребенком от 6 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"7 წლიდან 8 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 7 to 8 years old","name_ru"=>"Полный уход за ребенком от 7 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"7 წლიდან 9 წლამდე ბავშვის სრულყოფილი მოვლა","name_en"=>"Complete care of a child from 7 to 9 years old","name_ru"=>"Полный уход за ребенком от 7 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"2 ბავშვის ერთდროულად მოვლა","name_en"=>"Taking care of 2 children at the same time","name_ru"=>"Уход за 2 детьми одновременно","category_id"=>"1"),
            array("name_ka"=>"3 ბავშვის ერთდროულად მოვლა","name_en"=>"Taking care of 3 children at the same time","name_ru"=>"Уход за 3 детьми одновременно","category_id"=>"1"),
            array("name_ka"=>"4 ბავშვის ერთდროულად მოვლა","name_en"=>"Taking care of 4 children at the same time","name_ru"=>"Уход за 4 детьми одновременно","category_id"=>"1"),
            array("name_ka"=>"ტყუპების სრულყოფილი მოვლა","name_en"=>"Complete care of twins","name_ru"=>"Полный уход за близнецами","category_id"=>"1"),
            array("name_ka"=>"3-დან 4 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 4 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 4 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 5 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 5 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 5 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 6 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 6 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 6 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 7 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 7 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 7 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 8 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 8 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 8 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 9 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 9 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 9 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 10 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 10 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 10 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 11 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 11 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 11 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 12 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 12 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 12 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 13 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 13 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 13 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 14 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 14 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 14 лет","category_id"=>"1"),
            array("name_ka"=>"3-დან 15 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 15 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 15 лет","category_id"=>"1"),
            array("name_ka"=>"70 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 70 sq.m","name_ru"=>"Обустройство квартиры до 70 кв.м","category_id"=>"1"),
            array("name_ka"=>"100 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 100 sq.m","name_ru"=>"Обустройство квартиры до 100 кв.м","category_id"=>"1"),
            array("name_ka"=>"150 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 150 sq.m","name_ru"=>"Обустройство квартиры до 150 кв.м","category_id"=>"1"),
            array("name_ka"=>"200 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 200 sq.m","name_ru"=>"Обустройство квартиры до 200 кв.м.","category_id"=>"1"),
            array("name_ka"=>"250 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 250 sq.m","name_ru"=>"Обустройство квартиры до 250 кв.м","category_id"=>"1"),
            array("name_ka"=>"300 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 300 sq.m","name_ru"=>"Обустройство квартиры до 300 кв.м.","category_id"=>"1"),
            array("name_ka"=>"400 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 400 sq.m","name_ru"=>"Обустройство квартиры до 400 кв.м.","category_id"=>"1"),
            array("name_ka"=>"500 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 500 sq.m","name_ru"=>"Обустройство квартиры до 500 кв.м.","category_id"=>"1"),
            array("name_ka"=>"ოჯახის სარეცხი","name_en"=>"Family laundry","name_ru"=>"Семейная прачечная","category_id"=>"1"),
            array("name_ka"=>"ოჯახის სადილი","name_en"=>"Family dinner","name_ru"=>"Семейный ужин","category_id"=>"1"),
            array("name_ka"=>"ოჯახის უთო","name_en"=>"Family iron","name_ru"=>"Семейный утюг","category_id"=>"1"),
            array("name_ka"=>"ბავშვის განვითარებაზე ზრუნვა","name_en"=>"Taking care of the child's development","name_ru"=>"Забота о развитии ребенка","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ოთახის დალაგება","name_en"=>"Tidying up the child's room","name_ru"=>"Уборка детской комнаты","category_id"=>"1"),
            array("name_ka"=>"ბავშვის სადილის მომზადება","name_en"=>"Preparing the child's dinner","name_ru"=>"Приготовление детского обеда","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ტანსაცმლების გარეცხვა","name_en"=>"Washing baby clothes","name_ru"=>"Стирка детской одежды","category_id"=>"1"),
            array("name_ka"=>"ბავშვი სადაც მოძრაობს მხოლოდ იმ ოთახის გამოწმენდა/დალაგება","name_en"=>"Cleaning/tidying only the room where the child moves","name_ru"=>"Уборка/уборка только комнаты, в которой передвигается ребенок","category_id"=>"1"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_en"=>"Taking the child to school/kindergarten","name_ru"=>"Отвезти ребенка в школу/детский сад","category_id"=>"1"),
            array("name_ka"=>"ძაღლის გასეირნება","name_en"=>"Dog walking","name_ru"=>"Выгул собак","category_id"=>"1"),
            array("name_ka"=>"შინაური ცხოველების/ფრინველების მოვლა","name_en"=>"Pet/bird care","name_ru"=>"Уход за домашними животными/птицами","category_id"=>"1"),
            array("name_ka"=>"ბავშვის საბავშვო ბაღისთვის ან სკოლისთვის მომზადება","name_en"=>"Preparing a child for kindergarten or school","name_ru"=>"Подготовка ребенка к детскому саду или школе","category_id"=>"1"),
            array("name_ka"=>"ბავშვისათვის თვითმომსახურეობის უნარების შესწავლა","name_en"=>"Learning self-service skills for children","name_ru"=>"Обучение детей навыкам самообслуживания.","category_id"=>"1"),
            array("name_ka"=>"ბავშვის ჰიგიენური პროცედურების ჩატარება","name_en"=>"Conducting child hygiene procedures","name_ru"=>"Проведение детских гигиенических процедур","category_id"=>"1"),
            array("name_ka"=>"მხოლოდ საკუთარ ოჯახში","name_en"=>"Only in your own family","name_ru"=>"Только в своей семье","category_id"=>"1"),
            array("name_ka"=>"შშმ პირის სრულყოფილი მოვლა","name_en"=>"Complete care of a disabled person","name_ru"=>"Полный уход за инвалидом","category_id"=>"1"),
            array("name_ka"=>"მწოლიარე მამაკაცის მოვლა","name_en"=>"Caring for a recumbent man","name_ru"=>"Уход за лежачим мужчиной","category_id"=>"2"),
            array("name_ka"=>"არამწოლიარე მამაკაცის მოვლა","name_en"=>"Care of the non-recumbent man","name_ru"=>"Уход за не лежачим мужчиной","category_id"=>"2"),
            array("name_ka"=>"მწოლიარე ქალბატონის მოვლა","name_en"=>"Care of the bedridden lady","name_ru"=>"Уход за лежачей дамой","category_id"=>"2"),
            array("name_ka"=>"არამწოლიარე ქალბატონის მოვლა","name_en"=>"Care of the non-recumbent lady","name_ru"=>"Уход за не лежачей дамой","category_id"=>"2"),
            array("name_ka"=>"ნაინსულტარი მამაკაცის მოვლა","name_en"=>"Caring for an insutian man","name_ru"=>"Уход за инсутианским мужчиной","category_id"=>"2"),
            array("name_ka"=>"ნაინსულტარი ქალბატონის მოვლა","name_en"=>"Caring for an insutian lady","name_ru"=>"Уход за инсутианской дамой","category_id"=>"2"),
            array("name_ka"=>"ზონდიანი პაციენტის მოვლა","name_en"=>"Care of the probe patient","name_ru"=>"Уход за пациентом с зондом","category_id"=>"2"),
            array("name_ka"=>"ტრახეასტომიანი პაციენტის მოვლა","name_en"=>"Care of a patient with a tracheostomy","name_ru"=>"Уход за больным с трахеостомой","category_id"=>"2"),
            array("name_ka"=>"მოტეხილობებით პაციენტის მოვლა","name_en"=>"Care of patients with fractures","name_ru"=>"Уход за больными с переломами","category_id"=>"2"),
            array("name_ka"=>"ავტოსაგზაო შემთხვევით დაზიანებული პაციენტის მოვლა","name_en"=>"Caring for a patient injured in a traffic accident","name_ru"=>"Уход за больным, пострадавшим в дорожно-транспортном происшествии","category_id"=>"2"),
            array("name_ka"=>"კათეტერიან პაციენტთან","name_en"=>"with a patient with a catheter","name_ru"=>"с пациентом с катетером","category_id"=>"2"),
            array("name_ka"=>"მენჯ-ბარძაყ ენდოპროტეზირებული პაციენტის მოვლა","name_en"=>"Care of the hip and hip endoprosthesis patient","name_ru"=>"Уход за больным тазобедренным суставом и эндопротезом тазобедренного сустава","category_id"=>"2"),
            array("name_ka"=>"ალცჰაიმერიანი პაციენტის მოვლა","name_en"=>"Alzheimer's patient care","name_ru"=>"уход за пациентами с болезнью Альцгеймера","category_id"=>"2"),
            array("name_ka"=>"ფსიქიური აშლილობის ნიშნების მქონე პაციენტის მოვლა","name_en"=>"Care of the patient with signs of mental disorder","name_ru"=>"Уход за больным с признаками психического расстройства","category_id"=>"2"),
            array("name_ka"=>"მძიმეწონიანი პაციენტის მოვლა","name_en"=>"Care of the heavy patient","name_ru"=>"Уход за тяжелым пациентом","category_id"=>"2"),
            array("name_ka"=>"მხოლოდ საკუთარ ოჯახში","name_en"=>"Only in your own family","name_ru"=>"Только в своей семье","category_id"=>"2"),
            array("name_ka"=>"სანიტარულ-ჰიგიენური პროცედურები","name_en"=>"sanitary-hygienic procedures","name_ru"=>"санитарно-гигиенические процедуры","category_id"=>"2"),
            array("name_ka"=>"ბანაობაში დახმარება","name_en"=>"Help with bathing","name_ru"=>"Помощь с купанием","category_id"=>"2"),
            array("name_ka"=>"სუდნოზე დასმა","name_en"=>"Putting on the boat","name_ru"=>"Посадка на лодку","category_id"=>"2"),
            array("name_ka"=>"საპირფარეშომდე მიცილება","name_en"=>"Escorting to the restroom","name_ru"=>"Сопровождение в туалет","category_id"=>"2"),
            array("name_ka"=>"პამპერსების გამოცვლა","name_en"=>"Changing diapers","name_ru"=>"Смена подгузников","category_id"=>"2"),
            array("name_ka"=>"პაციენტის კვება, მისთვის საკვების მომზადება","name_en"=>"Feeding the patient, preparing food for him","name_ru"=>"Кормление больного, приготовление ему пищи","category_id"=>"2"),
            array("name_ka"=>"მაღაზიაში პროდუქტების შეძენა","name_en"=>"Purchase products in the store","name_ru"=>"Покупка продуктов в магазине","category_id"=>"2"),
            array("name_ka"=>"ექიმის დანიშნული წამლების მიღებაზე კონტროლი","name_en"=>"Control over taking drugs prescribed by the doctor","name_ru"=>"Контроль за приемом препаратов, назначенных врачом","category_id"=>"2"),
            array("name_ka"=>"ნაწოლების დამუშავება და მისი პროფილაქტიკა","name_en"=>"Treatment of bedsores and its prevention","name_ru"=>"Лечение пролежней и их профилактика","category_id"=>"2"),
            array("name_ka"=>"სიცხის გაზომვა","name_en"=>"Heat measurement","name_ru"=>"Измерение тепла","category_id"=>"2"),
            array("name_ka"=>"წნევის გაზომვა","name_en"=>"Pressure Measurement","name_ru"=>"Измерение давления","category_id"=>"2"),
            array("name_ka"=>"პაციენტის ჰაერზე გასეირნებები","name_en"=>"Patient air walks","name_ru"=>"Воздушные прогулки пациента","category_id"=>"2"),
            array("name_ka"=>"პაციენტის ფსიქოლოგიური მხარდაჭერა","name_en"=>"Psychological support of the patient","name_ru"=>"Психологическая поддержка пациента","category_id"=>"2"),
            array("name_ka"=>"პაციენტის ოთახის დალაგება","name_en"=>"Tidying up the patient's room","name_ru"=>"Уборка комнаты пациента","category_id"=>"2"),
            array("name_ka"=>"აფთიაქიდან წამლების ამოტანა","name_en"=>"Taking out medicines from the pharmacy","name_ru"=>"Получение лекарств из аптеки","category_id"=>"2"),
            array("name_ka"=>"სკლეროზიანი ქალბატონის მოვლა","name_en"=>"Care of a woman with multiple sclerosis","name_ru"=>"Уход за женщиной с рассеянным склерозом","category_id"=>"2"),
            array("name_ka"=>"სკლეროზიანი მამაკაცის მოვლა","name_en"=>"Care of a man with multiple sclerosis","name_ru"=>"Уход за мужчиной с рассеянным склерозом","category_id"=>"2"),
            array("name_ka"=>"პარკინსონიანი პაციენტის მოვლა","name_en"=>"Care of the patient with Parkinson's disease","name_ru"=>"Уход за больным с болезнью Паркинсона","category_id"=>"2"),
            array("name_ka"=>"დიაბეტიანი პაციენტის მოვლა","name_en"=>"Care of the diabetic patient","name_ru"=>"Уход за больным диабетом","category_id"=>"2"),
            array("name_ka"=>"ასთმიანი პაციენტის მოვლა","name_en"=>"Care of the asthmatic patient","name_ru"=>"Уход за больным астмой","category_id"=>"2"),
            array("name_ka"=>"შემიძლია ინსულინის ნემსის გაკეთება","name_en"=>"I can do an insulin needle","name_ru"=>"Я могу сделать инсулиновую иглу","category_id"=>"2"),
            array("name_ka"=>"შემიძლია გადასხმების გაკეთება","name_en"=>"I can do transfusions","name_ru"=>"Я могу делать переливания","category_id"=>"2"),
            array("name_ka"=>"ონკოლგიური პაციენტის მოვლა","name_en"=>"Oncological patient care","name_ru"=>"Уход за онкологическими больными","category_id"=>"2"),
            array("name_ka"=>"შშმ პირის სრულყოფილი მოვლა","name_en"=>"Complete care of a disabled person","name_ru"=>"Полный уход за инвалидом","category_id"=>"2"),
            array("name_ka"=>"დიალეზიან პაციენტთან","name_en"=>"with a dialysis patient","name_ru"=>"с диализным пациентом","category_id"=>"2"),
            array("name_ka"=>"3-დან 4 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 4 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 4 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 5 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 5 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 5 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 6 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 6 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 6 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 7 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 7 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 7 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 8 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 8 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 8 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 9 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 9 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 9 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 10 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 10 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 10 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 11 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 11 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 11 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 12 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 12 years","name_ru"=>"Гувернантка для ребенка (детей), в возрасте от 3 до 12 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 13 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 13 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 13 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 14 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess of child(ren), aged 3 to 14 years","name_ru"=>"Гувернантка ребенка (детей), в возрасте от 3 до 14 лет","category_id"=>"3"),
            array("name_ka"=>"3-დან 15 წლამდე ასაკის ბავშვის(ების), გუვერნანტი","name_en"=>"Governess for child(ren), aged 3 to 15 years","name_ru"=>"Гувернантка для ребенка(детей), в возрасте от 3 до 15 лет","category_id"=>"3"),
            array("name_ka"=>"ბავშვის განვითარებაზე ზრუნვა","name_en"=>"Taking care of the child's development","name_ru"=>"Забота о развитии ребенка","category_id"=>"3"),
            array("name_ka"=>"ბავშვის ოთახის დალაგება","name_en"=>"Tidying up the child's room","name_ru"=>"Уборка детской комнаты","category_id"=>"3"),
            array("name_ka"=>"ბავშვის სადილის მომზადება","name_en"=>"Preparing the child's dinner","name_ru"=>"Приготовление детского обеда","category_id"=>"3"),
            array("name_ka"=>"ბავშვის ტანსაცმლების გარეცხვა","name_en"=>"Washing baby clothes","name_ru"=>"Стирка детской одежды","category_id"=>"3"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_en"=>"Taking the child to school/kindergarten","name_ru"=>"Отвезти ребенка в школу/детский сад","category_id"=>"3"),
            array("name_ka"=>"ბავშვის საბავშვო ბაღისთვის ან სკოლისთვის მომზადება","name_en"=>"Preparing a child for kindergarten or school","name_ru"=>"Подготовка ребенка к детскому саду или школе","category_id"=>"3"),
            array("name_ka"=>"ბავშვისათვის თვითმომსახურეობის უნარების შესწავლა","name_en"=>"Learning self-service skills for children","name_ru"=>"Обучение детей навыкам самообслуживания.","category_id"=>"3"),
            array("name_ka"=>"მხოლოდ საკუთარ ოჯახში","name_en"=>"Only in your own family","name_ru"=>"Только в своей семье","category_id"=>"3"),
            array("name_ka"=>"სადარბაზოს კიბის უჯრედების დალაგება","name_en"=>"Sorting the cells of the entrance staircase","name_ru"=>"Сортировка ячеек входной лестницы","category_id"=>"4"),
            array("name_ka"=>"საკლასო ოთახებისა და კორიდორის დალაგება","name_en"=>"Tidying up classrooms and corridors","name_ru"=>"Уборка классных комнат и коридоров","category_id"=>"4"),
            array("name_ka"=>"ბაღის ოთახებისა და კორიდორის დალაგება","name_en"=>"Tidying up the garden rooms and the corridor","name_ru"=>"Уборка садовых комнат и коридора","category_id"=>"4"),
            array("name_ka"=>"სპორტდარბაზის დალაგება","name_en"=>"Tidying up the gym","name_ru"=>"Уборка спортзала","category_id"=>"4"),
            array("name_ka"=>"კვების ობიექტების დალაგება","name_en"=>"Arrangement of catering facilities","name_ru"=>"Обустройство мест общественного питания","category_id"=>"4"),
            array("name_ka"=>"შუშების გაწმენდა","name_en"=>"Cleaning the windows","name_ru"=>"Мойка окон","category_id"=>"4"),
            array("name_ka"=>"ფარდების ჩამოხსნა/გარეცხვა/დაკიდება","name_en"=>"Removing/washing/hanging curtains","name_ru"=>"Снятие/стирка/развешивание штор","category_id"=>"4"),
            array("name_ka"=>"ნარჩენების შეგროვება გადაყრა","name_en"=>"Waste collection and disposal","name_ru"=>"Сбор и утилизация отходов","category_id"=>"4"),
            array("name_ka"=>"ოფისების დალაგება","name_en"=>"Tidying up offices","name_ru"=>"Уборка офисов","category_id"=>"4"),
            array("name_ka"=>"ბინების დალაგება","name_en"=>"arranging apartments","name_ru"=>"обустройство квартир","category_id"=>"4"),
            array("name_ka"=>"სანიტარულ-ჰიგიენური ნორმების დაცვა: სამუშაო ადგილის, სამზარეულო მოწყობილობების სუფთა მდგომარეობაში შენახვა.","name_en"=>"Compliance with sanitary-hygienic norms: keeping the workplace, kitchen equipment in a clean state.","name_ru"=>"Соблюдение санитарно-гигиенических норм: содержание рабочего места, кухонного инвентаря в чистоте.","category_id"=>"5"),
            array("name_ka"=>"საჭირო პროდუქტების რეგულარულად შეძენა","name_en"=>"Regular purchase of necessary products","name_ru"=>"Регулярная покупка необходимых продуктов","category_id"=>"5"),
            array("name_ka"=>"კალკულაცია","name_en"=>"Calculation","name_ru"=>"Расчет","category_id"=>"5"),
            array("name_ka"=>"ოჯახის წევრებისა და მათი ხშირი სტუმრების გემოვნების გათვალისწინება, ინდივიდუალური მიდგომა ამ საკითხისადმი.","name_en"=>"Taking into account the tastes of family members and their frequent guests, an individual approach to this issue.","name_ru"=>"Учет вкусов членов семьи и их частых гостей, индивидуальный подход к этому вопросу.","category_id"=>"5"),
            array("name_ka"=>"სუფრასთან მიტანამდე კერძის გაფორმება, ასევე სუფრის გაფორმება.","name_en"=>"Decoration of the dish before serving, as well as decoration of the table.","name_ru"=>"Украшение блюда перед подачей, а также украшение стола.","category_id"=>"5"),
            array("name_ka"=>"სამუშაო ადგილის ჰიგიენურ მდგომარეობაში შენახვა.","name_en"=>"Keeping the workplace in a hygienic condition.","name_ru"=>"Поддержание рабочего места в санитарно-гигиеническом состоянии.","category_id"=>"5"),
            array("name_ka"=>"თევზეული კერძების მომზადება","name_en"=>"Preparation of fish dishes","name_ru"=>"Приготовление рыбных блюд","category_id"=>"5"),
            array("name_ka"=>"მან-ბურღულეულისაგან კერძების მომზადება","name_en"=>"Preparation of dishes from man-cereals","name_ru"=>"Приготовление блюд из манных круп","category_id"=>"5"),
            array("name_ka"=>"მაკარონის კერძების მომზადება","name_en"=>"Preparation of pasta dishes","name_ru"=>"Приготовление блюд из макарон","category_id"=>"5"),
            array("name_ka"=>"დიაბეტური საკვების მომზადება","name_en"=>"Preparation of diabetic food","name_ru"=>"Приготовление диабетической пищи","category_id"=>"5"),
            array("name_ka"=>"ქართული ცივი და ცხელი კერძების მომზადება","name_en"=>"Preparation of hot and cold Georgian dishes","name_ru"=>"Приготовление горячих и холодных грузинских блюд","category_id"=>"5"),
            array("name_ka"=>"თურქული ენის რეპეტიტორად","name_en"=>"Turkish language tutor","name_ru"=>"репетитор по турецкому языку","category_id"=>"5"),
            array("name_ka"=>"ქართული ენის რეპეტიტორად","name_en"=>"As a tutor of the Georgian language","name_ru"=>"Как репетитор грузинского языка","category_id"=>"5"),
            array("name_ka"=>"აბიტურიენტების რეპეტიტორად","name_en"=>"as a tutor for entrants","name_ru"=>"как репетитор для абитуриентов","category_id"=>"5"),
            array("name_ka"=>"უნარების რეპეტიტორად","name_en"=>"as a skills tutor","name_ru"=>"как репетитор по навыкам","category_id"=>"5"),
            array("name_ka"=>"მგზავრთა გადაყვანა","name_en"=>"Transportation of passengers","name_ru"=>"Перевозка пассажиров","category_id"=>"6"),
            array("name_ka"=>"დამკვეთის მიერ დათქმულ დროს მანქანის დროული მიყვანა ადგილზე","name_en"=>"Timely delivery of the car to the place at the time agreed by the customer","name_ru"=>"Своевременная подача автомобиля на место в согласованное с заказчиком время","category_id"=>"6"),
            array("name_ka"=>"ავტომობილის მუდამ სუფთა და გამართულ მდგომარეობაში შენახვა","name_en"=>"Keeping the vehicle always clean and in good condition","name_ru"=>"Поддержание автомобиля всегда в чистоте и исправном состоянии","category_id"=>"6"),
            array("name_ka"=>"ავტომობილის ტექნიკური მომსახურეობა (გარეცხვა, საწვავითა და ზეთით გამართვა და სხვა),","name_en"=>"Vehicle maintenance (washing, oiling, etc.),","name_ru"=>"Техническое обслуживание автомобиля (мойка, смазка и т.д.),","category_id"=>"6"),
            array("name_ka"=>"ელემენტარული სარემონტო სამუშაოების ჩატარება (თვლების გამოცვლა, აკუმულატორის გამოცვლა დ.ა.შ),","name_en"=>"Carrying out elementary repair work (wheel replacement, battery replacement, etc.),","name_ru"=>"Проведение элементарных ремонтных работ (замена колеса, замена аккумулятора и т.д.),","category_id"=>"6"),
            array("name_ka"=>"გადადგილებისას მგზავრთა უსაფრთხოებასა და კომფორტულობაზე ზრუნვა","name_en"=>"Taking care of the safety and comfort of the passengers during the transfer","name_ru"=>"Забота о безопасности и комфорте пассажиров во время перевозки","category_id"=>"6"),
            array("name_ka"=>"დამქირავებლის დავალებების შესრულება, დაკავშირებული მის ოჯახის წევრთან მიმართებაში, ან სხვა პირადი თხოვნებიდან გამომდინარე.","name_en"=>"Fulfilling the tasks of the tenant, related to his family member, or based on other personal requests.","name_ru"=>"Выполнение задач арендатора, связанных с членом его семьи, или на основании других личных пожеланий.","category_id"=>"6"),
            array("name_ka"=>"არასამუშაო საათებში (ღამით), ავტომობილის დამკვეთის მიერ მითითებულ ადგილას შენახვა.","name_en"=>"Storage of the vehicle in non-working hours (at night), in the place specified by the customer.","name_ru"=>"Хранение автомобиля в нерабочее время (ночью), в месте, указанном заказчиком.","category_id"=>"6"),
            array("name_ka"=>"დისტრიბუციის წარმოება","name_en"=>"Production of distribution","name_ru"=>"Производство дистрибуции","category_id"=>"6"),
            array("name_ka"=>"დამქირავებლის სამსახურში მიყვანა და წამოყვანა","name_en"=>"Bringing and picking up the tenant to work","name_ru"=>"Доставка и встреча арендатора с работы","category_id"=>"6"),
            array("name_ka"=>"კომპანიის თანამშრომლების სამსახურში მიყვანა/წამოყვანა","name_en"=>"Bringing company employees to work","name_ru"=>"Привлечение сотрудников компании к работе","category_id"=>"6"),
            array("name_ka"=>"70 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 70 sq.m","name_ru"=>"Обустройство квартиры до 70 кв.м","category_id"=>"7"),
            array("name_ka"=>"100 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 100 sq.m","name_ru"=>"Обустройство квартиры до 100 кв.м","category_id"=>"7"),
            array("name_ka"=>"150 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 150 sq. m","name_ru"=>"Обустройство квартиры до 150 кв.м","category_id"=>"7"),
            array("name_ka"=>"200 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 200 sq.m","name_ru"=>"Обустройство квартиры до 200 кв.м.","category_id"=>"7"),
            array("name_ka"=>"250 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 250 sq.m","name_ru"=>"Обустройство квартиры до 250 кв.м","category_id"=>"7"),
            array("name_ka"=>"300 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 300 sq. m","name_ru"=>"Обустройство квартиры до 300 кв.м","category_id"=>"7"),
            array("name_ka"=>"400 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 400 sq.m","name_ru"=>"Обустройство квартиры до 400 кв.м.","category_id"=>"7"),
            array("name_ka"=>"500 კვ-მდე ბინის დალაგება","name_en"=>"Arrangement of an apartment up to 500 sq.m","name_ru"=>"Обустройство квартиры до 500 кв.м.","category_id"=>"7"),
            array("name_ka"=>"ოჯახის სარეცხი","name_en"=>"Family laundry","name_ru"=>"Семейная прачечная","category_id"=>"7"),
            array("name_ka"=>"ოჯახის სადილი","name_en"=>"family dinner","name_ru"=>"семейный ужин","category_id"=>"7"),
            array("name_ka"=>"ოჯახის უთო","name_en"=>"Family iron","name_ru"=>"Семейный утюг","category_id"=>"7"),
            array("name_ka"=>"ბავშვის ოთახის დალაგება","name_en"=>"Tidying up the child's room","name_ru"=>"Уборка детской комнаты","category_id"=>"7"),
            array("name_ka"=>"ბავშვის სადილის მომზადება","name_en"=>"Preparing the child's dinner","name_ru"=>"Приготовление детского обеда","category_id"=>"7"),
            array("name_ka"=>"ბავშვის ტანსაცმლების გარეცხვა","name_en"=>"Washing baby clothes","name_ru"=>"Стирка детской одежды","category_id"=>"7"),
            array("name_ka"=>"ბავშვის სკოლაში/ბაღში წაყვანა/გამოყვანა","name_en"=>"Taking the child to school/kindergarten","name_ru"=>"Отвезти ребенка в школу/детский сад","category_id"=>"7"),
            array("name_ka"=>"ძაღლის გასეირნება","name_en"=>"dog walking","name_ru"=>"выгул собак","category_id"=>"7"),
            array("name_ka"=>"შინაური ცხოველების/ფრინველების მოვლა","name_en"=>"Pet/bird care","name_ru"=>"Уход за домашними животными/птицами","category_id"=>"7"),
            array("name_ka"=>"ეზოს მოწესრიგება","name_en"=>"tidying up the yard","name_ru"=>"уборка двора","category_id"=>"7"),
            array("name_ka"=>"მხოლოდ საკუთარ ოჯახში","name_en"=>"Only in your own family","name_ru"=>"Только в своей семье","category_id"=>"7"),
            array("name_ka"=>"დაწყებითების რეპეტიტორად","name_en"=>"as a primary school tutor","name_ru"=>"как репетитор начальных классов","category_id"=>"8"),
            array("name_ka"=>"მე-VII-XI კლასის ჩათვლით საგნების რეპეტიტორად","name_en"=>"As a tutor of subjects including VII-XI class","name_ru"=>"В качестве репетитора предметов, в том числе VII-XI классов","category_id"=>"8"),
            array("name_ka"=>"ქიმიის რეპეტიტორად","name_en"=>"as a chemistry tutor","name_ru"=>"как репетитор по химии","category_id"=>"8"),
            array("name_ka"=>"ფიზიკის რეპეტიტორად","name_en"=>"as a physics tutor","name_ru"=>"как репетитор по физике","category_id"=>"8"),
            array("name_ka"=>"მათემატიკის რეპეტიტორად","name_en"=>"as a math tutor","name_ru"=>"как репетитор по математике","category_id"=>"8"),
            array("name_ka"=>"ისტორიის რეპეტიტორად","name_en"=>"as a history tutor","name_ru"=>"как репетитор по истории","category_id"=>"8"),
            array("name_ka"=>"გეოგრაფიის რეპეტიტორად","name_en"=>"as a geography tutor","name_ru"=>"как репетитор по географии","category_id"=>"8"),
            array("name_ka"=>"ინგლისური ენის რეპეტიტორად","name_en"=>"as an English language tutor","name_ru"=>"как репетитор английского языка","category_id"=>"8"),
            array("name_ka"=>"რუსული ენის რეპეტიტორად","name_en"=>"as a Russian language tutor","name_ru"=>"как репетитор по русскому языку","category_id"=>"8"),
            array("name_ka"=>"გერმანული ენის რეპეტიტორად","name_en"=>"as a German language tutor","name_ru"=>"как репетитор немецкого языка","category_id"=>"8"),
            array("name_ka"=>"ფრანგული ენის რეპეტიტორად","name_en"=>"as a French language tutor","name_ru"=>"как репетитор французского языка","category_id"=>"8"),
            array("name_ka"=>"თურქული ენის რეპეტიტორად","name_en"=>"Turkish language tutor","name_ru"=>"репетитор по турецкому языку","category_id"=>"8"),
            array("name_ka"=>"ქართული ენის რეპეტიტორად","name_en"=>"As a tutor of the Georgian language","name_ru"=>"Как репетитор грузинского языка","category_id"=>"8"),
            array("name_ka"=>"აბიტურიენტების რეპეტიტორად","name_en"=>"as a tutor for entrants","name_ru"=>"как репетитор для абитуриентов","category_id"=>"8"),
            array("name_ka"=>"უნარების რეპეტიტორად","name_en"=>"as a skills tutor","name_ru"=>"как репетитор по навыкам","category_id"=>"8"),
            array("name_ka"=>"2-3 წლის ასაკის I-ჯგუფის ბავშვებთან","name_en"=>"With children of the I-group aged 2-3 years","name_ru"=>"С детьми I группы 2-3 лет","category_id"=>"9"),
            array("name_ka"=>"3-5 წლის ასაკის II-ჯგუფის ბავშვებთან","name_en"=>"With children of the I-group aged 3-5 years","name_ru"=>"С детьми II группы 3-5 лет","category_id"=>"9"),
            array("name_ka"=>"5-6 წლის ასაკის III-ჯგუფის ბავშვებთან","name_en"=>"With children of the I-group aged 5-6 years","name_ru"=>"С детьми III группы 5-6 лет","category_id"=>"9"),
        );
        DB::table('skills')->insert($data);
    }
}
