<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SpecialtySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('specialties')->delete();
        $specialty = array(
            array("name_ru"=>"Агроинженерия","name_ka"=>"აგროინჟინერია","name_en"=>"Agroengineering"),
            array("name_ru"=>"Агрономия","name_ka"=>"აგრონომია","name_en"=>"Agronomy"),
            array("name_ru"=>"Авиастроение","name_ka"=>"ავიასაინჟინრო","name_en"=>"Aviation engineering"),
            array("name_ru"=>"Антропология и этнология","name_ka"=>"ანთროპოლოგია და ეთნოლოგია","name_en"=>"Anthropology and Ethnology"),
            array("name_ru"=>"Архитектура","name_ka"=>"არქიტექტურა","name_en"=>"architecture"),
            array("name_ru"=>"Дизайн архитектурной среды","name_ka"=>"არქიტექტურული დიზაინი","name_en"=>"Architectural design"),
            array("name_ru"=>"Реконструкция и реставрация архитектурного наследия","name_ka"=>"არქიტექტურული მემკვიდრეობის აღდგენა-რეკონსტრუქცია","name_en"=>"Restoration-reconstruction of architectural heritage"),
            array("name_ru"=>"Востоковедение и африканистика","name_ka"=>"აღმოსავლეთმცოდნეობა და აფრიკანიზმი","name_en"=>"Orientalism and Africanism"),
            array("name_ru"=>"Организация работы с молодежью","name_ka"=>"ახალგაზრდებთან მუშაობის ორგანიზება","name_en"=>"Organization of work with young people"),
            array("name_ru"=>"Баллистика и гидроаэродинамика","name_ka"=>"ბალისტიკური და ჰიდროაეროდინამიკა","name_en"=>"Ballistic and hydro-aerodynamics"),
            array("name_ru"=>"Библиотечно-информационная деятельность","name_ka"=>"ბიბლიოთეკა და ინფორმაციული საქმიანობა","name_en"=>"Library and information activities"),
            array("name_ru"=>"Бизнес-информатика","name_ka"=>"ბიზნეს ინფორმატიკა","name_en"=>"Business informatics"),
            array("name_ru"=>"Биология","name_ka"=>"ბიოლოგია","name_en"=>"Biology"),
            array("name_ru"=>"Биотехнология","name_ka"=>"ბიოტექნოლოგია","name_en"=>"Biotechnology"),
            array("name_ru"=>"Биотехнические системы и технологии","name_ka"=>"ბიოტექნოლოგიური სისტემა და ტექნოლოგია","name_en"=>"Biotechnological system and technology"),
            array("name_ru"=>"Ядерная энергетика и теплофизика","name_ka"=>"ბირთვული ენერგეტიკა და თერმოფიზიკა","name_en"=>"Nuclear energy and thermophysics"),
            array("name_ru"=>"Ядерные физика и технологии","name_ka"=>"ბირთვული ფიზიკა და ტექნოლოგიები","name_en"=>"Nuclear Physics and Technologies"),
            array("name_ru"=>"Издательское дело","name_ka"=>"გამომცემლობითი საქმიანობა","name_en"=>"Publishing activity"),
            array("name_ru"=>"Прикладная этика","name_ka"=>"გამოყენებითი ეთიკა","name_en"=>"Applied ethics"),
            array("name_ru"=>"Прикладная информатика","name_ka"=>"გამოყენებითი ინფორმატიკა","name_en"=>"Applied informatics"),
            array("name_ru"=>"Прикладная математика","name_ka"=>"გამოყენებითი მათემატიკა","name_en"=>"Applied Mathematics"),
            array("name_ru"=>"Прикладная математика и информатика","name_ka"=>"გამოყენებითი მათემატიკა და ინფორმატიკა","name_en"=>"Applied mathematics and informatics"),
            array("name_ru"=>"Прикладная механика","name_ka"=>"გამოყენებითი მექანიკა","name_en"=>"applied mechanics"),
            array("name_ru"=>"Прикладные математика и физика","name_ka"=>"გამოყენებითი ფიზიკა-მათემატიკა","name_en"=>"Applied physics and mathematics"),
            array("name_ru"=>"Прикладная гидрометеорология","name_ka"=>"გამოყენებითი ჰიდრომეტეოროლოგია","name_en"=>"Applied hydrometeorology"),
            array("name_ru"=>"Природообустройство и водопользование","name_ka"=>"გარემოსდაცვითი ინჟინერია და წყლის გამოყენება","name_en"=>"Environmental engineering and water use"),
            array("name_ru"=>"Кораблестроение, океанотехника и системотехника объектов морской инфраструктуры","name_ka"=>"გემთმშენებლობა, ოკეანის ტექნოლოგია და საზღვაო ინფრასტრუქტურის ობიექტების სისტემების ინჟინერია","name_en"=>"Shipbuilding, ocean technology and systems engineering of marine infrastructure facilities"),
            array("name_ru"=>"География","name_ka"=>"გეოგრაფია","name_en"=>"Geography"),
            array("name_ru"=>"Геодезия и дистанционное зондирование","name_ka"=>"გეოდეზია და დისტანციური ზონდირება","name_en"=>"Geodesy and remote sensing"),
            array("name_ru"=>"Геология","name_ka"=>"გეოლოგია","name_en"=>"Geology"),
            array("name_ru"=>"Декоративно-прикладное искусство и народные промыслы","name_ka"=>"დეკორატიულ-გამოყენებითი ხელოვნება და ხალხური რეწვა","name_en"=>"decorative-applied art and folk craft"),
            array("name_ru"=>"Дизайн","name_ka"=>"დიზაინი","name_en"=>"design"),
            array("name_ru"=>"Дирижирование","name_ka"=>"დირიჟორი","name_en"=>"conductor"),
            array("name_ru"=>"Драматургия","name_ka"=>"დრამატურგია","name_en"=>"Dramaturgy"),
            array("name_ru"=>"Экология и природопользование","name_ka"=>"ეკოლოგია და ბუნებითსარგებლობა","name_en"=>"Ecology and use of nature"),
            array("name_ru"=>"Экономика","name_ka"=>"ეკონომიკა","name_en"=>"economic"),
            array("name_ru"=>"Электроэнергетика и электротехника","name_ka"=>"ელექტროენერგეტიკა და ელექტროტექნიკა","name_en"=>"Electric power and electrical engineering"),
            array("name_ru"=>"Электроника и наноэлектроника","name_ka"=>"ელექტრონიკა და ნანო-ელექტრონიკა","name_en"=>"Electronics and nano-electronics"),
            array("name_ru"=>"Конструирование и технология электронных средств","name_ka"=>"ელექტრონული ხელსაწყოების კონსტრუქცია და ტექნოლოგია","name_en"=>"Construction and technology of electronic devices"),
            array("name_ru"=>"Энергетическое машиностроение","name_ka"=>"ენერგეტიკული მანქანათმშენებლობა","name_en"=>"Energy engineering"),
            array("name_ru"=>"Энерго- и ресурсосберегающие процессы в химической технологии, нефтехимии и биотехнологии","name_ka"=>"ენერგიისა და რესურსების დაზოგვის პროცესები ქიმიურ ტექნოლოგიაში, ნავთობქიმიასა და ბიოტექნოლოგიაში","name_en"=>"Energy and resource saving processes in chemical technology, petrochemicals and biotechnology"),
            array("name_ru"=>"Ветеринарно-санитарная экспертиза","name_ka"=>"ვეტერინარული სანიტარული ექსპერტიზა","name_en"=>"Veterinary sanitary examination"),
            array("name_ru"=>"Вокальное искусство","name_ka"=>"ვოკალური ხელოვნება","name_en"=>"Vocal art"),
            array("name_ru"=>"Режиссура театрализованных представлений и праздников","name_ka"=>"თეატრალური წარმოდგენების და ფესტივალების რეჟისურა","name_en"=>"Directing of theatrical performances and festivals"),
            array("name_ru"=>"Театральное искусство","name_ka"=>"თეატრალური ხელოვნება","name_en"=>"Theatrical art"),
            array("name_ru"=>"Театроведение","name_ka"=>"თეატრთმცოდნეობა","name_en"=>"theater studies"),
            array("name_ru"=>"Теология","name_ka"=>"თეოლოგია","name_en"=>"theology"),
            array("name_ru"=>"Теория и история искусств","name_ka"=>"თეორია და ხელოვნების ისტორია","name_en"=>"Theory and Art History"),
            array("name_ru"=>"Инноватика","name_ka"=>"ინოვაციური მეთოდიკა","name_en"=>"Innovative methodology"),
            array("name_ru"=>"Управление интеллектуальной собственностью","name_ka"=>"ინტელექტუალური საკუთრების მართვა","name_en"=>"Intellectual property management"),
            array("name_ru"=>"Инфокоммуникационные технологии и системы связи","name_ka"=>"ინფოკომუნიკაციური ტექნოლოგია და საკომუნიკაციო სისტემები","name_en"=>"Information communication technology and communication systems"),
            array("name_ru"=>"Информатика и вычислительная техника","name_ka"=>"ინფორმატიკა და გამოთვლითი ტექნიკა","name_en"=>"Informatics and computer technology"),
            array("name_ru"=>"Информационная безопасность","name_ka"=>"ინფორმაციული უსაფრთხოება","name_en"=>"Information security"),
            array("name_ru"=>"История","name_ka"=>"ისტორია","name_en"=>"History"),
            array("name_ru"=>"Юриспруденция","name_ka"=>"იურისპუდენცია","name_en"=>"Jurisprudence"),
            array("name_ru"=>"Картография и геоинформатика","name_ka"=>"კარტოგრაფია და გეოინფორმატიკა","name_en"=>"Cartography and geoinformatics"),
            array("name_ru"=>"Технология продукции и организация общественного питания","name_ka"=>"კვების ტექნოლოგია და საზ.კვების ორგანიზაცია/უზრუნველყოფა","name_en"=>"Food technology and catering organization/provision"),
            array("name_ru"=>"Конфликтология","name_ka"=>"კონფლიქტოლოგია","name_en"=>"Conflictology"),
            array("name_ru"=>"Искусство костюма и текстиля","name_ka"=>"კოსტუმი და ტექსტილის ხელოვნება","name_en"=>"Costume and Textile Art"),
            array("name_ru"=>"Культурология","name_ka"=>"კულტუროლოგია","name_en"=>"culturology"),
            array("name_ru"=>"Лазерная техника и лазерные технологии","name_ka"=>"ლაზერული ტექნიკა და ლაზერული ტექნოლოგია","name_en"=>"Laser technique and laser technology"),
            array("name_ru"=>"Ландшафтная архитектура","name_ka"=>"ლანდშაფტის არქიტექტურა","name_en"=>"Landscape architecture"),
            array("name_ru"=>"Лингвистика","name_ka"=>"ლინგვისტიკა","name_en"=>"Linguistics"),
            array("name_ru"=>"Математика","name_ka"=>"მათემატიკა","name_en"=>"mathematics"),
            array("name_ru"=>"Математика и компьютерные науки","name_ka"=>"მათემატიკა და კომპიუტერული მეცნიერება","name_en"=>"Mathematics and Computer Science"),
            array("name_ru"=>"Машиностроение","name_ka"=>"მანქანათმშენებლობა","name_en"=>"Machine building"),
            array("name_ru"=>"Конструкторско-технологическое обеспечение машиностроительных производств","name_ka"=>"მანქანათმშენებლობის საქმეში დიზაინურ-ტექნოლოგიური მხარდაჭერა","name_en"=>"Design-technological support in machine building"),
            array("name_ru"=>"Технология художественной обработки материалов","name_ka"=>"მასალების მხატვრული დამუშავების ტექნოლოგია","name_en"=>"Technology of artistic processing of materials"),
            array("name_ru"=>"Наукоемкие технологии и экономика инноваций","name_ka"=>"მაღალი ტექნოლოგიისა და ინოვაციის ეკონომიკა","name_en"=>"Economy of high technology and innovation"),
            array("name_ru"=>"Организация и управление наукоемкими производствами","name_ka"=>"მაღალტექნოლოგიური ინდუსტრიების ორგანიზება და მართვა","name_en"=>"Organization and management of high-tech industries"),
            array("name_ru"=>"Высокотехнологические плазменные и энергетические установки","name_ka"=>"მაღალტექნოლოგიური პლაზმური და ელექტროდანადგარები","name_en"=>"High-tech plasma and electrical devices"),
            array("name_ru"=>"Садоводство","name_ka"=>"მებაღეობა","name_en"=>"gardening"),
            array("name_ru"=>"Медиакоммуникации","name_ka"=>"მედია-კომუნიკაცია","name_en"=>"media-communication"),
            array("name_ru"=>"Мехатроника и робототехника","name_ka"=>"მეკატრონიკა და რობოტიკა","name_en"=>"Mechatronics and robotics"),
            array("name_ru"=>"Менеджмент","name_ka"=>"მენეჯმენტი","name_en"=>"managment"),
            array("name_ru"=>"Металлургия","name_ka"=>"მეტალურგია","name_en"=>"Metallurgy"),
            array("name_ru"=>"Механика и математическое моделирование","name_ka"=>"მექანიკა და მათემატიკური მოდელირება","name_en"=>"Mechanics and mathematical modeling"),
            array("name_ru"=>"Зоотехния","name_ka"=>"მეცხოველეობა","name_en"=>"animal husbandry"),
            array("name_ru"=>"Музыкознание и музыкально-прикладное искусство","name_ka"=>"მისიკათმცოდნეობა და მუსიკის გამოყენებითი ხელოვნება","name_en"=>"Musicology and applied art of music"),
            array("name_ru"=>"Землеустройство и кадастры","name_ka"=>"მიწათმოწყობა და კადასტრი","name_en"=>"Land management and cadastre"),
            array("name_ru"=>"Сервис","name_ka"=>"მომსახურება","name_en"=>"service"),
            array("name_ru"=>"Системы управления движением и навигация","name_ka"=>"მოძრაობის კონტროლისა და ნავიგაციის სისტემები","name_en"=>"Traffic control and navigation systems"),
            array("name_ru"=>"Технология изделий легкой промышленности","name_ka"=>"მსუბუქი მრეწველობის ნაწარმის ტექნოლოგია","name_en"=>"Technology of light industry products"),
            array("name_ru"=>"Конструирование изделий легкой промышленности","name_ka"=>"მსუბუქი წარმოების ინდუსტრიის პროდუქციის დიზაინი","name_en"=>"Product design for the light manufacturing industry"),
            array("name_ru"=>"Музеология и охрана объектов культурного и природного наследия","name_ka"=>"მუზეოლოგია და კულტურული, ბუნებრივი მემკვიდრეობის ძეგლების დაცვა","name_en"=>"Museology and protection of cultural and natural heritage monuments"),
            array("name_ru"=>"Музыкально-инструментальное искусство","name_ka"=>"მუსიკალურ-ინსტრუმენტული ხელოვნება","name_en"=>"Musical-instrumental art"),
            array("name_ru"=>"Строительство","name_ka"=>"მშენებლობა","name_en"=>"construction"),
            array("name_ru"=>"Продукты питания из растительного сырья","name_ka"=>"მცენარეული მასალების საკვები პროდუქტი","name_en"=>"A food product of plant materials"),
            array("name_ru"=>"Нефтегазовое дело","name_ka"=>"ნავთობისა და გაზის საქმე","name_en"=>"Oil and gas business"),
            array("name_ru"=>"Наноинженерия","name_ka"=>"ნანოინჟინერია","name_en"=>"Nanoengineering"),
            array("name_ru"=>"Наноматериалы","name_ka"=>"ნანომასალები","name_en"=>"Nanomaterials"),
            array("name_ru"=>"Наносистемы и наноматериалы","name_ka"=>"ნანოსისტემები და ნანომასალები","name_en"=>"Nanosystems and nanomaterials"),
            array("name_ru"=>"Нанотехнологии и микросистемная техника","name_ka"=>"ნანოტექნოლოგი და მიკროსისტემის ტექნოლოგია","name_en"=>"Nanotechnology and microsystem technology"),
            array("name_ru"=>"Почвоведение","name_ka"=>"ნიადაგთმცოდნეობა","name_en"=>"Soil science"),
            array("name_ru"=>"Оптотехника","name_ka"=>"ოპტიკური ტექნიკა","name_en"=>"optical technique"),
            array("name_ru"=>"Педагогическое образование","name_ka"=>"პედაგოგიური განათლება","name_en"=>"pedagogical education"),
            array("name_ru"=>"Управление персоналом","name_ka"=>"პერსონალის მართვა","name_en"=>"personnel management"),
            array("name_ru"=>"Технология полиграфического и упаковочного производства","name_ka"=>"პოლიგრაფიულ და შეფუთვის წარმოების ტექნოლოგია","name_en"=>"Printing and packaging production technology"),
            array("name_ru"=>"Политология","name_ka"=>"პოლიტოლოგია","name_en"=>"political science"),
            array("name_ru"=>"Программная инженерия","name_ka"=>"პროგრამული უზრუნველყოფის ინჟინერია","name_en"=>"Software engineering"),
            array("name_ru"=>"Профессиональное обучение (по отраслям),","name_ka"=>"პროფესიონალური სწავლებანი (ინდუსტრიის მიხედვით),","name_en"=>"Professional training (by industry),"),
            array("name_ru"=>"Журналистика","name_ka"=>"ჟურნალისტიკა","name_en"=>"Journalism"),
            array("name_ru"=>"Радиотехника","name_ka"=>"რადიოჟინერია","name_en"=>"radio engineering"),
            array("name_ru"=>"Радиофизика","name_ka"=>"რადიოფიზიკა","name_en"=>"Radiophysics"),
            array("name_ru"=>"Реклама и связи с общественностью","name_ka"=>"რეკლამა და საზოგადოებასთან ურთიერთობა","name_en"=>"Advertising and public relations"),
            array("name_ru"=>"Рекреация и спортивно-оздоровительный туризм","name_ka"=>"რეკრეაცია და სპორტულ-გამაჯანსაღებელი ტურიზმი","name_en"=>"Recreation and sports-health tourism"),
            array("name_ru"=>"Религиоведение","name_ka"=>"რელიგიათმცოდნეობა","name_en"=>"Religious studies"),
            array("name_ru"=>"Реставрация","name_ka"=>"რესტავრაცია","name_en"=>"Restoration"),
            array("name_ru"=>"Техническая эксплуатация авиационных электросистем и пилотажно-навигационных комплексов","name_ka"=>"საავიაციო ელექტრ-სისტემების და ფრენის ნავიგაციის კომპლექსის ტექნიკური ექსპლოატაცია","name_en"=>"Technical operation of aviation electrical systems and flight navigation complex"),
            array("name_ru"=>"Документоведение и архивоведение","name_ka"=>"საარქივო საქმე და დოკუმენტაცია","name_en"=>"Archival case and documentation"),
            array("name_ru"=>"Жилищное хозяйство и коммунальная инфраструктура","name_ka"=>"საბინაო და კომუნალური ინფრასტრუქტურა","name_en"=>"Housing and communal infrastructure"),
            array("name_ru"=>"Зарубежное регионоведение","name_ka"=>"საგარეო რეგიონთმცოდნეობა (საგარეო რეგიონალური კვლევები),","name_en"=>"Foreign Regional Studies (Foreign Regional Studies),"),
            array("name_ru"=>"Международные отношения","name_ka"=>"საერთაშორისო ურთიერთობები","name_en"=>"International relations"),
            array("name_ru"=>"Музыкальное искусство эстрады","name_ka"=>"საესტრადო- მუსიკალური ხელოვნება","name_en"=>"Pop-musical art"),
            array("name_ru"=>"Сестринское дело","name_ka"=>"საექთნო საქმე","name_en"=>"Nursing work"),
            array("name_ru"=>"Торговое дело","name_ka"=>"სავაჭრო საქმე","name_en"=>"trade case"),
            array("name_ru"=>"Публичная политика и социальные науки","name_ka"=>"საზოგადოებრივი პოლიტიკა და სოციალური მეცნიერებანი","name_en"=>"Public policy and social sciences"),
            array("name_ru"=>"Общественное здравоохранение","name_ka"=>"საზოგადოებრივი ჯანდაცვა","name_en"=>"public health"),
            array("name_ru"=>"Корабельное вооружение","name_ka"=>"საზღვაო შეიარაღება","name_en"=>"naval armament"),
            array("name_ru"=>"Информационные системы и технологии","name_ka"=>"საინფორმაციო სისტემები და ტექნოლოგიები","name_en"=>"Information systems and technologies"),
            array("name_ru"=>"Математическое обеспечение и администрирование информационных систем","name_ka"=>"საინფორმაციო სისტემების მათემატიკური უზრუნველყოფა და ადმინისტრირება","name_en"=>"Mathematical assurance and administration of information systems"),
            array("name_ru"=>"Холодильная, криогенная техника и системы жизнеобеспечения","name_ka"=>"სამაცივრე, კრიოგენული მოწყობილობები და სხვა საყოფაცხოვრებო სისტემები","name_en"=>"Refrigerator, cryogenic equipment and other household systems"),
            array("name_ru"=>"Промышленное рыболовство","name_ka"=>"სამრეწველო თევზჭერა","name_en"=>"industrial fishing"),
            array("name_ru"=>"Промышленная фармация","name_ka"=>"სამრეწველო ფარმაცია","name_en"=>"Industrial pharmacy"),
            array("name_ru"=>"Управление воинскими частями и соединениями","name_ka"=>"სამხედრო ნაწილებისა და ფორმირებების მართვა","name_en"=>"Management of military units and formations"),
            array("name_ru"=>"Ракетные комплексы и космонавтика","name_ka"=>"სარაკეტო კომპლექსები და კოსმონავტიკა","name_en"=>"Missile complexes and cosmonautics"),
            array("name_ru"=>"Технология производства и переработки сельскохозяйственной продукции","name_ka"=>"სასოფლო-სამეურნეო დანიშნულების პროდუქციის წარმოება-გადამუშავება","name_en"=>"Production and processing of agricultural products"),
            array("name_ru"=>"Гостиничное дело","name_ka"=>"სასტუმროს საქმე","name_en"=>"The hotel case"),
            array("name_ru"=>"Технология транспортных процессов","name_ka"=>"სატრანსპორტო პროცესების ტექნოლოგია","name_en"=>"Technology of transport processes"),
            array("name_ru"=>"Эксплуатация транспортно-технологических машин и комплексов","name_ka"=>"სატრანსპორტო-ტექნოლოგიური დანადგარების და კომპლექსების ექსპლუატაცია","name_en"=>"Operation of transport-technological installations and complexes"),
            array("name_ru"=>"Лесное дело","name_ka"=>"სატყეო საქმე","name_en"=>"forestry work"),
            array("name_ru"=>"Техническая эксплуатация летательных аппаратов и двигателей","name_ka"=>"საფრენი აპარატებისა და ძრავების ტექნიკური ექსპლოატაცია","name_en"=>"Technical operation of aircraft and engines"),
            array("name_ru"=>"Двигатели летательных аппаратов","name_ka"=>"საფრენი აპარატის ძრავები","name_en"=>"Aircraft engines"),
            array("name_ru"=>"Регионоведение России","name_ka"=>"საქართველოს მხარეთმცოდნეობა","name_en"=>"Regional knowledge of Georgia"),
            array("name_ru"=>"Товароведение","name_ka"=>"საქონელთმცოდნეობა","name_en"=>"commodity science"),
            array("name_ru"=>"Материаловедение и технологии материалов","name_ka"=>"საქონელთმცოდნეობა და მასალების ტექნოლოგია","name_en"=>"Commodity science and materials technology"),
            array("name_ru"=>"Государственный аудит","name_ka"=>"სახელმწიფო აუდიტი","name_en"=>"State audit"),
            array("name_ru"=>"Государственное и муниципальное управление","name_ka"=>"სახელმწიფო და მუნიციპალური მმართველობა","name_en"=>"State and municipal governance"),
            array("name_ru"=>"Изящные искусства","name_ka"=>"სახვითი ხელოვნება","name_en"=>"Visual Art"),
            array("name_ru"=>"Наземные транспортно-технологические комплексы","name_ka"=>"სახმელეთო ტრანსპორტი და ტექნოლოგიური კომპლექსები","name_en"=>"Land transport and technological complexes"),
            array("name_ru"=>"Аэронавигация","name_ka"=>"საჰაერო ნავიგაცია","name_en"=>"Air navigation"),
            array("name_ru"=>"Эксплуатация аэропортов и обеспечение полетов воздушных судов","name_ka"=>"საჰაერო ხომალდების ფრენის უზრუნველყოფა და აეროპორტის ექსპლოატაცია","name_en"=>"Ensuring the flight of aircraft and operation of the airport"),
            array("name_ru"=>"Теплоэнергетика и теплотехника","name_ka"=>"სითბური ენერგეტიკა და სითბური ტექნოლოგიები","name_en"=>"Thermal energy and thermal technologies"),
            array("name_ru"=>"Системный анализ и управление","name_ka"=>"სისტემური ანალიზი და მართვა","name_en"=>"System analysis and management"),
            array("name_ru"=>"Агрохимия и агропочвоведение","name_ka"=>"სოფლის მეურნეობის ქიმია და ნიადაგის მეცნიერება","name_en"=>"Agricultural Chemistry and Soil Science"),
            array("name_ru"=>"Социальная работа","name_ka"=>"სოციალური მუშაობა","name_en"=>"social work"),
            array("name_ru"=>"Социально-культурная деятельность","name_ka"=>"სოციალურ-კულტურული საქმიანობა","name_en"=>"socio-cultural activities"),
            array("name_ru"=>"Социология","name_ka"=>"სოციოლოგია","name_en"=>"Sociology"),
            array("name_ru"=>"Технология художественного оформления спектакля","name_ka"=>"სპექტაკლების მხატვრული გაფორმების ტექნოლოგია","name_en"=>"The technology of artistic decoration of performances"),
            array("name_ru"=>"Высокотехнологичные производства пищевых продуктов функционального и специализированного назначения                                     ფუნქციური და სპეციალიზებული მიზნებისათვის მაღალტექნოლოგიური საკვების წარმოება","name_ka"=>"სპეციალიზირებულ-ფუნქციონალური დანიშნულების საკვები პროდუქტების მაღალტექნოლოგიური წარმოება","name_en"=>"High-tech production of specialized-functional food products"),
            array("name_ru"=>"Специальное (дефектологическое), образование","name_ka"=>"სპეციალური (დეფექტოლოგიური), განათლება","name_en"=>"Special (defective), education"),
            array("name_ru"=>"Спорт","name_ka"=>"სპორტი","name_en"=>"sports"),
            array("name_ru"=>"Стандартизация и метрология","name_ka"=>"სტანდარტიზაცია და მეტროლოგია","name_en"=>"Standardization and metrology"),
            array("name_ru"=>"Статистика","name_ka"=>"სტატისტიკა","name_en"=>"Statistics"),
            array("name_ru"=>"Телевидение","name_ka"=>"ტელევიზია","name_en"=>"television"),
            array("name_ru"=>"Управление в технических системах","name_ka"=>"ტექნიკური სისტემების მმართველობა","name_en"=>"Management of technical systems"),
            array("name_ru"=>"Техническая физика","name_ka"=>"ტექნიკური ფიზიკა","name_en"=>"Technical physics"),
            array("name_ru"=>"Технологические машины и оборудование","name_ka"=>"ტექნოლოგიური მანქანები და მოწყობილობანი","name_en"=>"Technological machines and devices"),
            array("name_ru"=>"Автоматизация технологических процессов и производств","name_ka"=>"ტექნოლოგიური პროცესების ავტომატიზაცია და წარმოება","name_en"=>"Automation of technological processes and production"),
            array("name_ru"=>"Техносферная безопасность","name_ka"=>"ტექნოსფეროს უსაფრთხოება","name_en"=>"Technosphere Security"),
            array("name_ru"=>"Технология и проектирование текстильных изделий","name_ka"=>"ტექსტილური ნაწარმის ტექნოლოგია-პროექტირება","name_en"=>"Technology-design of textile products"),
            array("name_ru"=>"Туризм","name_ka"=>"ტურიზმი","name_en"=>"tourism"),
            array("name_ru"=>"Физика","name_ka"=>"ფიზიკა","name_en"=>"physics"),
            array("name_ru"=>"Физическая культура","name_ka"=>"ფიზიკური კულტურა","name_en"=>"physical culture"),
            array("name_ru"=>"Филология","name_ka"=>"ფილოლოგია","name_en"=>"Philology"),
            array("name_ru"=>"Философия","name_ka"=>"ფილოსოფია","name_en"=>"philosophy"),
            array("name_ru"=>"Финансы и кредит","name_ka"=>"ფინანსები და კრედიტები","name_en"=>"Finances and credits"),
            array("name_ru"=>"Фотоника и оптоинформатика","name_ka"=>"ფოტონიკა და ოპტოინფორმატიკა","name_en"=>"Photonics and optoinformatics"),
            array("name_ru"=>"Психология","name_ka"=>"ფსიქოლოგია","name_en"=>"psychology"),
            array("name_ru"=>"Психолого-педагогическое образование","name_ka"=>"ფსიქოლოგიურ-პედაგოგიური განათლება","name_en"=>"Psychological-pedagogical education"),
            array("name_ru"=>"Фундаментальная и прикладная лингвистика","name_ka"=>"ფუნდამენტური და გამოყენებითი ენათმეცნიერება","name_en"=>"Fundamental and applied linguistics"),
            array("name_ru"=>"Фундаментальные информатика и информационные технологии","name_ka"=>"ფუნდამენტური ინფორმატიკა და საინფორმაციო ტექნოლოგიები","name_en"=>"Fundamental informatics and information technologies"),
            array("name_ru"=>"Градостроительство","name_ka"=>"ქალაქგეგმარება","name_en"=>"urban planning"),
            array("name_ru"=>"Химия","name_ka"=>"ქიმია","name_en"=>"chemistry"),
            array("name_ru"=>"Химия, физика и механика материалов","name_ka"=>"ქიმია, ფიზიკა და მასალების მექანიკა","name_en"=>"Chemistry, physics and mechanics of materials"),
            array("name_ru"=>"Химическая технология","name_ka"=>"ქიმიური ტექნოლოგია","name_en"=>"Chemical technology"),
            array("name_ru"=>"Хореографическое исполнительство","name_ka"=>"ქორეოგრაფიული წარმოდგენა","name_en"=>"Choreographic performance"),
            array("name_ru"=>"Хореографическое искусство","name_ka"=>"ქორეოგრაფიული ხელოვნება","name_en"=>"Choreographic art"),
            array("name_ru"=>"Продукты питания животного происхождения","name_ka"=>"ცხოველური წარმოშობის საკვები პროდუქტები","name_en"=>"Food products of animal origin"),
            array("name_ru"=>"Водные биоресурсы и аквакультура","name_ka"=>"წყლის ბიორესურსები და აკვაკულტურა","name_en"=>"Aquatic Bioresources and Aquaculture"),
            array("name_ru"=>"Управление водным транспортом и гидрографическое обеспечение судоходства","name_ka"=>"წყლის ტრანსპორტის მართვა და წყალნავიგაციის ჰიდროგრაფიული უზრუნველყოფა","name_en"=>"Management of water transport and hydrographic provision of water navigation"),
            array("name_ru"=>"Искусство народного пения","name_ka"=>"ხალხური სიმღერების ხელოვნება","name_en"=>"The art of folk songs"),
            array("name_ru"=>"Народная художественная культура","name_ka"=>"ხალხურ-მხატვრული კულტურა","name_en"=>"folk-artistic culture"),
            array("name_ru"=>"Управление качеством","name_ka"=>"ხარისხის მართვა","name_en"=>"quality management"),
            array("name_ru"=>"Искусство","name_ka"=>"ხელოვნება","name_en"=>"art"),
            array("name_ru"=>"Искусства и гуманитарные науки","name_ka"=>"ხელოვნება და ჰუმანიტარული მეცნიერება","name_en"=>"Arts and Humanities"),
            array("name_ru"=>"История искусств","name_ka"=>"ხელოვნების ისტორია","name_en"=>"History of art"),
            array("name_ru"=>"Приборостроение","name_ka"=>"ხელსაწყოთმშენებლობა","name_en"=>"tool making"),
            array("name_ru"=>"Технология лесозаготовительных и деревоперерабатывающих производств","name_ka"=>"ხე-ტყის გადამამუშავებელი საწარმოს ტექნოლოგია","name_en"=>"Technology of wood processing enterprise"),
            array("name_ru"=>"Физическая культура для лиц с отклонениями в состоянии здоровья (адаптивная физическая культура),","name_ka"=>"ჯანმრთელობის პრობლემების მქონე ადამიანების ფიზკულტურა (ადაპტური ფიზიკური განათლება),","name_en"=>"Physical education of people with health problems (adaptive physical education),"),
            array("name_ru"=>"Гидромелиорация","name_ka"=>"ჰიდრომელიორაცია","name_en"=>"hydromelioration"),
            array("name_ru"=>"Гидрометеорология","name_ka"=>"ჰიდრომეტეოროლოგია","name_en"=>"Hydrometeorology"),
            array("name_ru"=>"Интеллектуальные системы в гуманитарной сфере","name_ka"=>"ჰუმანიტარული სფეროს ინტელექტუალური სისტემები","name_en"=>"Intelligent systems of humanitarian sphere"),
        );
        DB::table('specialties')->insert($specialty);
    }
}
