<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class WhoNeedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('for_who_needs')->delete();
        $data = array(
            array("name_ka"=>"ახალშობილი გოგონა","name_en"=>"newborn girl","name_ru"=>"новорожденная девочка","category_id"=>"1"),
            array("name_ka"=>"ახალშობილი ვაჟი","name_en"=>"newborn son","name_ru"=>"новорожденный мальчик","category_id"=>"1"),
            array("name_ka"=>"ახალშობილი ტყუპი გოგონები","name_en"=>"Newborn twin girls","name_ru"=>"Новорожденные двойняшки девочки","category_id"=>"1"),
            array("name_ka"=>"ახალშობილი ტყუპი ვაჟები","name_en"=>"Newborn twin boys","name_ru"=>"Новорожденные близнецы мальчики","category_id"=>"1"),
            array("name_ka"=>"ახალშობილი ტყუპი ქალ-ვაჟი","name_en"=>"Newborn twin girl-boy","name_ru"=>"Новорожденные близнецы мальчик и девочка","category_id"=>"1"),
            array("name_ka"=>"1 თვის გოგონა","name_en"=>"1 month old girl","name_ru"=>"1 месяц девочка","category_id"=>"1"),
            array("name_ka"=>"1 თვის ვაჟი","name_en"=>"1 month old son","name_ru"=>"1 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"2 თვის გოგონა","name_en"=>"2 month old girl","name_ru"=>"2-х месячная девочка","category_id"=>"1"),
            array("name_ka"=>"2 თვის ვაჟი","name_en"=>"2 month old son","name_ru"=>"2-х месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"3 თვის გოგონა","name_en"=>"3 months old girl","name_ru"=>"3-х месячная девочка","category_id"=>"1"),
            array("name_ka"=>"3 თვის ვაჟი","name_en"=>"3 month old son","name_ru"=>"3-х месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"4 თვის გოგონა","name_en"=>"4 month old girl","name_ru"=>"4 месячная девочка","category_id"=>"1"),
            array("name_ka"=>"4 თვის ვაჟი","name_en"=>"4 month old son","name_ru"=>"4 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"5 თვის გოგონა","name_en"=>"5 month old girl","name_ru"=>"5 месячная девочка","category_id"=>"1"),
            array("name_ka"=>"5 თვის ვაჟი","name_en"=>"5 month old son","name_ru"=>"5 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"6 თვის გოგონა","name_en"=>"6 months old girl","name_ru"=>"6 месяцев девочка","category_id"=>"1"),
            array("name_ka"=>"6 თვის ვაჟი","name_en"=>"6 month old son","name_ru"=>"6 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"7 თვის გოგონა","name_en"=>"7 months old girl","name_ru"=>"7 месяцев девочка","category_id"=>"1"),
            array("name_ka"=>"7 თვის ვაჟი","name_en"=>"7 month old son","name_ru"=>"7 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"8 თვის გოგონა","name_en"=>"8 month old girl","name_ru"=>"8 месячная девочка","category_id"=>"1"),
            array("name_ka"=>"8 თვის ვაჟი","name_en"=>"8 month old son","name_ru"=>"8 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"9 თვის გოგონა","name_en"=>"9 months old girl","name_ru"=>"9 месячная девочка","category_id"=>"1"),
            array("name_ka"=>"9 თვის ვაჟი","name_en"=>"9 month old son","name_ru"=>"9 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"10 თვის გოგონა","name_en"=>"10 month old girl","name_ru"=>"10 месяцев девочка ","category_id"=>"1"),
            array("name_ka"=>"10 თვის ვაჟი","name_en"=>"10 month old son","name_ru"=>"10 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"11 თვის გოგონა","name_en"=>"11 month old girl","name_ru"=>"11 месячная девочка","category_id"=>"1"),
            array("name_ka"=>"11 თვის ვაჟი","name_en"=>"11 month old son","name_ru"=>"11 месячный мальчик","category_id"=>"1"),
            array("name_ka"=>"1 წლის გოგონა","name_en"=>"1 year old girl","name_ru"=>"1 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"1 წლის ვაჟი","name_en"=>"1 year old son","name_ru"=>"1 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"2 წლის გოგონა","name_en"=>"2 year old girl","name_ru"=>"2-х летняя девочка","category_id"=>"1"),
            array("name_ka"=>"2 წლის ვაჟი","name_en"=>"2 year old son","name_ru"=>"2-х летний мальчик","category_id"=>"1"),
            array("name_ka"=>"3 წლის გოგონა","name_en"=>"3 year old girl","name_ru"=>"3-х летняя девочка","category_id"=>"1"),
            array("name_ka"=>"3 წლის ვაჟი","name_en"=>"3 year old son","name_ru"=>"3-х летний мальчик","category_id"=>"1"),
            array("name_ka"=>"4 წლის გოგონა","name_en"=>"4 year old girl","name_ru"=>"4 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"4 წლის ვაჟი","name_en"=>"4 year old son","name_ru"=>"4 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"5 წლის გოგონა","name_en"=>"5 year old girl","name_ru"=>"5 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"5 წლის ვაჟი","name_en"=>"5 year old son","name_ru"=>"5 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"6 წლის გოგონა","name_en"=>"6 year old girl","name_ru"=>"6 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"6 წლის ვაჟი","name_en"=>"6 year old son","name_ru"=>"6 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"7 წლის გოგონა","name_en"=>"7 year-old girl","name_ru"=>"7 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"7 წლის ვაჟი","name_en"=>"7 year old son","name_ru"=>"7 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"8 წლის გოგონა","name_en"=>"8 year-old girl","name_ru"=>"8 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"8 წლის ვაჟი","name_en"=>"8 year old son","name_ru"=>"8 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"9 წლის გოგონა","name_en"=>"9 year-old girl","name_ru"=>"9 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"9 წლის ვაჟი","name_en"=>"9 year old son","name_ru"=>"9 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"10 წლის გოგონა","name_en"=>"10 year-old girl","name_ru"=>"10 летняя девочка","category_id"=>"1"),
            array("name_ka"=>"10 წლის ვაჟი","name_en"=>"10 year old son","name_ru"=>"10 летний мальчик","category_id"=>"1"),
            array("name_ka"=>"1 თვის ტყუპი გოგონები","name_en"=>"1 month old twin girls","name_ru"=>"1 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"1 თვის ტყუპი ვაჟები","name_en"=>"1 month old twin boys","name_ru"=>"1 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"2 თვის ტყუპი გოგონები","name_en"=>"2 month old twin girls","name_ru"=>"2-х месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"2 თვის ტყუპი ვაჟები","name_en"=>"2 month old twin boys","name_ru"=>"2-х месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"3 თვის ტყუპი გოგონები","name_en"=>"3 month old twin girls","name_ru"=>"3-х месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"3 თვის ტყუპი ვაჟები","name_en"=>"3 month old twin boys","name_ru"=>"3-х месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"4 თვის ტყუპი გოგონები","name_en"=>"4 month old twin girls","name_ru"=>"4-х месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"4 თვის ტყუპი ვაჟები","name_en"=>"4 month old twin boys","name_ru"=>"4-х месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"5 თვის ტყუპი გოგონები","name_en"=>"5 month old twin girls","name_ru"=>"5 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"5 თვის ტყუპი ვაჟები","name_en"=>"5 month old twin boys","name_ru"=>"5 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"6 თვის ტყუპი გოგონები","name_en"=>"6 month old twin girls","name_ru"=>"6 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"6 თვის ტყუპი ვაჟები","name_en"=>"6 month old twin boys","name_ru"=>"6 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"7 თვის ტყუპი გოგონები","name_en"=>"7 month old twin girls","name_ru"=>"7 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"7 თვის ტყუპი ვაჟები","name_en"=>"7 month old twin boys","name_ru"=>"7 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"8 თვის ტყუპი გოგონები","name_en"=>"8 month old twin girls","name_ru"=>"8 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"8 თვის ტყუპი ვაჟები","name_en"=>"8 month old twin boys","name_ru"=>"8 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"9 თვის ტყუპი გოგონები","name_en"=>"9 month old twin girls","name_ru"=>"9 месячные Девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"9 თვის ტყუპი ვაჟები","name_en"=>"9 month old twin boys","name_ru"=>"9 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"10 თვის ტყუპი გოგონები","name_en"=>"10 month old twin girls","name_ru"=>"10 месячные Девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"10 თვის ტყუპი ვაჟები","name_en"=>"10 month old twin boys","name_ru"=>"10 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"11 თვის ტყუპი გოგონები","name_en"=>"11 month old twin girls","name_ru"=>"11 месячные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"11 თვის ტყუპი ვაჟები","name_en"=>"11 month old twin boys","name_ru"=>"11 месячные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"1 წლის ტყუპი გოგონები","name_en"=>"1 year old twin girls","name_ru"=>"1 летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"1 წლის ტყუპი ვაჟები","name_en"=>"1 year old twin boys","name_ru"=>"1 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"2 წლის ტყუპი გოგონები","name_en"=>"2 year old twin girls","name_ru"=>"2-х летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"2 წლის ტყუპი ვაჟები","name_en"=>"2 year old twin boys","name_ru"=>"2-х летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"3 წლის ტყუპი გოგონები","name_en"=>"3 year old twin girls","name_ru"=>"3-х летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"3 წლის ტყუპი ვაჟები","name_en"=>"3 year old twin boys","name_ru"=>"3-х летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"4 წლის ტყუპი გოგონები","name_en"=>"4 year old twin girls","name_ru"=>"4-х летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"4 წლის ტყუპი ვაჟები","name_en"=>"4 year old twin boys","name_ru"=>"4-х летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"5 წლის ტყუპი გოგონები","name_en"=>"5 year old twin girls","name_ru"=>"5 летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"5 წლის ტყუპი ვაჟები","name_en"=>"5 year old twin sons","name_ru"=>"5 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"6 წლის ტყუპი გოგონები","name_en"=>"6 year old twin girls","name_ru"=>"6 летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"6 წლის ტყუპი ვაჟები","name_en"=>"6 year old twin sons","name_ru"=>"6 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"7 წლის ტყუპი გოგონები","name_en"=>"7 year old twin girls","name_ru"=>"7 летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"7 წლის ტყუპი ვაჟები","name_en"=>"7 year old twin sons","name_ru"=>"7 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"8 წლის ტყუპი გოგონები","name_en"=>"8 year old twin girls","name_ru"=>"8 летные девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"8 წლის ტყუპი ვაჟები","name_en"=>"8 year old twin sons","name_ru"=>"8 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"9 წლის ტყუპი გოგონები","name_en"=>"9 year old twin girls","name_ru"=>"9 летные Девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"9 წლის ტყუპი ვაჟები","name_en"=>"9 year old twin sons","name_ru"=>"9 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"10 წლის ტყუპი გოგონები","name_en"=>"10 year old twin girls","name_ru"=>"10 летные Девочки-двойняшки","category_id"=>"1"),
            array("name_ka"=>"10 წლის ტყუპი ვაჟები","name_en"=>"10-year-old twin sons","name_ru"=>"10 летные мальчики близнецы","category_id"=>"1"),
            array("name_ka"=>"1 თვის ტყუპი ქალ-ვაჟი","name_en"=>"1 month-old twin boys and girls","name_ru"=>"1 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"2 თვის ტყუპი ქალ-ვაჟი","name_en"=>"2 month-old twin boys and girls","name_ru"=>"2-х месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"3 თვის ტყუპი ქალ-ვაჟი","name_en"=>"3 month-old twin boys and girls","name_ru"=>"3-х месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"4 თვის ტყუპი ქალ-ვაჟი","name_en"=>"4 month-old twin boys and girls","name_ru"=>"4-х месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"5 თვის ტყუპი ქალ-ვაჟი","name_en"=>"5 month-old twin boys and girls","name_ru"=>"5 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"6 თვის ტყუპი ქალ-ვაჟი","name_en"=>"6 month-old twin boys and girls","name_ru"=>"6 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"7 თვის ტყუპი ქალ-ვაჟი","name_en"=>"7 month-old twin boys and girls","name_ru"=>"7 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"8 თვის ტყუპი ქალ-ვაჟი","name_en"=>"8 month-old twin boys and girls","name_ru"=>"8 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"9 თვის ტყუპი ქალ-ვაჟი","name_en"=>"9 month-old twin boys and girls","name_ru"=>"9 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"10 თვის ტყუპი ქალ-ვაჟი","name_en"=>"10 month-old twin boys and girls","name_ru"=>"10 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"11 თვის ტყუპი ქალ-ვაჟი","name_en"=>"11 month-old twin boys and girls","name_ru"=>"11 месячные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"1 წლის ტყუპი ქალ-ვაჟი","name_en"=>"1 year-old twin boys and girls","name_ru"=>"1 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"2 წლის ტყუპი ქალ-ვაჟი","name_en"=>"2 year-old twin boys and girls","name_ru"=>"2 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"3 წლის ტყუპი ქალ-ვაჟი","name_en"=>"3 year-old twin boys and girls","name_ru"=>"3 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"4 წლის ტყუპი ქალ-ვაჟი","name_en"=>"4 year-old twin boys and girls","name_ru"=>"4 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"5 წლის ტყუპი ქალ-ვაჟი","name_en"=>"5 year-old twin boys and girls","name_ru"=>"5 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"6 წლის ტყუპი ქალ-ვაჟი","name_en"=>"6 year-old twin boys and girls","name_ru"=>"6 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"7 წლის ტყუპი ქალ-ვაჟი","name_en"=>"7 year-old twin boys and girls","name_ru"=>"7 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"8 წლის ტყუპი ქალ-ვაჟი","name_en"=>"8 year-old twin boys and girls","name_ru"=>"8 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"9 წლის ტყუპი ქალ-ვაჟი","name_en"=>"9 year-old twin boys and girls","name_ru"=>"9 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"10 წლის ტყუპი ქალ-ვაჟი","name_en"=>"10 year-old twin boys and girls","name_ru"=>"10 летные близнецы мальчики и девочка","category_id"=>"1"),
            array("name_ka"=>"1 თვის შშმ გოგონა","name_en"=>"1 month-old disabled girl","name_ru"=>"1 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"1 თვის შშმ ვაჟი","name_en"=>"1 month-old disabled son","name_ru"=>"1 месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"2 თვის შშმ გოგონა","name_en"=>"2 month-old disabled girl","name_ru"=>"2-х месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"2 თვის შშმ ვაჟი","name_en"=>"2 month-old disabled son","name_ru"=>"2-х месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"3 თვის შშმ გოგონა","name_en"=>"3 month-old disabled girl","name_ru"=>"3-х месячная девочкас ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"3 თვის შშმ ვაჟი","name_en"=>"3 month-old disabled son","name_ru"=>"3-х месячный мальчикс ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"4 თვის შშმ გოგონა","name_en"=>"4 month-old disabled girl","name_ru"=>"4-х месячная девочкас ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"4 თვის შშმ ვაჟი","name_en"=>"4 month-old disabled son","name_ru"=>"4-х месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"5 თვის შშმ გოგონა","name_en"=>"5 month-old disabled girl","name_ru"=>"5 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"5 თვის შშმ ვაჟი","name_en"=>"5 month-old disabled son","name_ru"=>"5 месячный мальчикс ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"6 თვის შშმ გოგონა","name_en"=>"6 month-old disabled girl","name_ru"=>"6 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"6 თვის შშმ ვაჟი","name_en"=>"6 month-old disabled son","name_ru"=>"6 месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"7 თვის შშმ გოგონა","name_en"=>"7 month-old disabled girl","name_ru"=>"7 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"7 თვის შშმ ვაჟი","name_en"=>"7 month-old disabled son","name_ru"=>"7 месячный мальчикс ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"8 თვის შშმ გოგონა","name_en"=>"8 month-old disabled girl","name_ru"=>"8 месячная девочкас ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"8 თვის შშმ ვაჟი","name_en"=>"8 month-old disabled son","name_ru"=>"8 месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"9 თვის შშმ გოგონა","name_en"=>"9 month-old disabled girl","name_ru"=>"9 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"9 თვის შშმ ვაჟი","name_en"=>"9 month-old disabled son","name_ru"=>"9 месячный мальчикс ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"10 თვის შშმ გოგონა","name_en"=>"10 month-old disabled girl","name_ru"=>"10 месячная девочкас ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"10 თვის შშმ ვაჟი","name_en"=>"10 month-old disabled son","name_ru"=>"10 месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"11 თვის შშმ გოგონა","name_en"=>"11 month-old disabled girl","name_ru"=>"11 месячная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"11 თვის შშმ ვაჟი","name_en"=>"11 month-old disabled son","name_ru"=>"11 месячный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"1 წლის შშმ გოგონა","name_en"=>"1 year-old disabled girl","name_ru"=>"1 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"1 წლის შშმ ვაჟი","name_en"=>"1 year-old disabled son","name_ru"=>"1 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"2 წლის შშმ გოგონა","name_en"=>"2 year-old disabled girl","name_ru"=>"2-х летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"2 წლის შშმ ვაჟი","name_en"=>"2 year-old disabled son","name_ru"=>"2-х летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"3 წლის შშმ გოგონა","name_en"=>"3 year-old disabled girl","name_ru"=>"3-х летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"3 წლის შშმ ვაჟი","name_en"=>"3 year-old disabled son","name_ru"=>"3-х летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"4 წლის შშმ გოგონა","name_en"=>"4 year-old disabled girl","name_ru"=>"4-х летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"4 წლის შშმ ვაჟი","name_en"=>"4 year-old disabled son","name_ru"=>"4-х летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"5 წლის შშმ გოგონა","name_en"=>"5 year-old disabled girl","name_ru"=>"5 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"5 წლის შშმ ვაჟი","name_en"=>"5 year-old disabled son","name_ru"=>"5 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"6 წლის შშმ გოგონა","name_en"=>"6 year-old disabled girl","name_ru"=>"6 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"6 წლის შშმ ვაჟი","name_en"=>"6 year-old disabled son","name_ru"=>"6 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"7 წლის შშმ გოგონა","name_en"=>"7 year-old disabled girl","name_ru"=>"7 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"7 წლის შშმ ვაჟი","name_en"=>"7 year-old disabled son","name_ru"=>"7 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"8 წლის შშმ გოგონა","name_en"=>"8 year-old disabled girl","name_ru"=>"8 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"8 წლის შშმ ვაჟი","name_en"=>"8 year-old disabled son","name_ru"=>"8 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"9 წლის შშმ გოგონა","name_en"=>"9 year-old disabled girl","name_ru"=>"9 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"9 წლის შშმ ვაჟი","name_en"=>"9 year-old disabled son","name_ru"=>"9 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"10 წლის შშმ გოგონა","name_en"=>"10 year-old disabled girl","name_ru"=>"10 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"10 წლის შშმ ვაჟი","name_en"=>"10 year-old disabled son","name_ru"=>"10 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"11 წლის შშმ გოგონა","name_en"=>"11 year-old disabled girl","name_ru"=>"11 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"11 წლის შშმ ვაჟი","name_en"=>"11 year-old disabled son","name_ru"=>"11 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"12 წლის შშმ გოგონა","name_en"=>"12 year-old disabled girl","name_ru"=>"12 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"12 წლის შშმ ვაჟი","name_en"=>"12 year-old disabled son","name_ru"=>"12 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"13 წლის შშმ გოგონა","name_en"=>"13 year-old disabled girl","name_ru"=>"13 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"13 წლის შშმ ვაჟი","name_en"=>"13 year-old disabled son","name_ru"=>"13 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"14 წლის შშმ გოგონა","name_en"=>"14 year-old disabled girl","name_ru"=>"14 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"14 წლის შშმ ვაჟი","name_en"=>"14 year-old disabled son","name_ru"=>"14 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"15 წლის შშმ გოგონა","name_en"=>"15 year-old disabled girl","name_ru"=>"15 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"15 წლის შშმ ვაჟი","name_en"=>"15 year-old disabled son","name_ru"=>"15 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"16 წლის შშმ გოგონა","name_en"=>"16 year-old disabled girl","name_ru"=>"16 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"16 წლის შშმ ვაჟი","name_en"=>"16 year-old disabled son","name_ru"=>"16 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"17 წლის შშმ გოგონა","name_en"=>"17 year-old disabled girl","name_ru"=>"17 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"17 წლის შშმ ვაჟი","name_en"=>"17 year-old disabled son","name_ru"=>"17 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"18 წლის შშმ გოგონა","name_en"=>"18 year-old disabled girl","name_ru"=>"18 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"18 წლის შშმ ვაჟი","name_en"=>"18 year-old disabled son","name_ru"=>"18 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"19 წლის შშმ გოგონა","name_en"=>"19 year-old disabled girl","name_ru"=>"19 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"19 წლის შშმ ვაჟი","name_en"=>"19 year-old disabled son","name_ru"=>"19 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"20 წლის შშმ გოგონა","name_en"=>"20 year-old disabled girl","name_ru"=>"20 летная девочка с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"20 წლის შშმ ვაჟი","name_en"=>"20 year-old disabled son","name_ru"=>"20 летный мальчик с ограниченными возможностями","category_id"=>"1"),
            array("name_ka"=>"3 წლის გოგონა","name_en"=>"3 year old girl","name_ru"=>"3 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"3 წლის ვაჟი","name_en"=>"3 year old son","name_ru"=>"3 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"4 წლის გოგონა","name_en"=>"4 year old girl","name_ru"=>"4 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"4 წლის ვაჟი","name_en"=>"4 year old son","name_ru"=>"4 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"5 წლის გოგონა","name_en"=>"5 year old girl","name_ru"=>"5 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"5 წლის ვაჟი","name_en"=>"5 year old son","name_ru"=>"5 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"6 წლის გოგონა","name_en"=>"6 year old girl","name_ru"=>"6 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"6 წლის ვაჟი","name_en"=>"6 year old son","name_ru"=>"6 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"7 წლის გოგონა","name_en"=>"7 year old girl","name_ru"=>"7 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"7 წლის ვაჟი","name_en"=>"7 year old son","name_ru"=>"7 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"8 წლის გოგონა","name_en"=>"8 year old girl","name_ru"=>"8 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"8 წლის ვაჟი","name_en"=>"8 year old son","name_ru"=>"8 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"9 წლის გოგონა","name_en"=>"9 year old girl","name_ru"=>"9 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"9 წლის ვაჟი","name_en"=>"9 year old son","name_ru"=>"9 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"10 წლის გოგონა","name_en"=>"10 year old girl","name_ru"=>"10 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"10 წლის ვაჟი","name_en"=>"10 year old son","name_ru"=>"10 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"11 წლის გოგონა","name_en"=>"11 year old girl","name_ru"=>"11 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"11 წლის ვაჟი","name_en"=>"11 year old son","name_ru"=>"11 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"12 წლის გოგონა","name_en"=>"12 year old girl","name_ru"=>"12 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"12 წლის ვაჟი","name_en"=>"12 year old son","name_ru"=>"12 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"13 წლის გოგონა","name_en"=>"13 year old girl","name_ru"=>"13 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"13 წლის ვაჟი","name_en"=>"13 year old son","name_ru"=>"13 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"14 წლის გოგონა","name_en"=>"14 year old girl","name_ru"=>"14 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"14 წლის ვაჟი","name_en"=>"14 year old son","name_ru"=>"14 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"15 წლის გოგონა","name_en"=>"15 year old girl","name_ru"=>"15 летняя девочка","category_id"=>"2"),
            array("name_ka"=>"15 წლის ვაჟი","name_en"=>"15 year old son","name_ru"=>"15 летний мальчик","category_id"=>"2"),
            array("name_ka"=>"I-კლასის  მოსწავლისათვის","name_en"=>"Для I-ого классника","name_ru"=>"For I-class student","category_id"=>"3"),
            array("name_ka"=>"II-კლასის  მოსწავლისათვის","name_en"=>"Для II-ого классника","name_ru"=>"For the II-grade student","category_id"=>"3"),
            array("name_ka"=>"III-კლასის  მოსწავლისათვის","name_en"=>"Для III-ого классника","name_ru"=>"For the III-grade student","category_id"=>"3"),
            array("name_ka"=>"IV-კლასის  მოსწავლისათვის","name_en"=>"Для IV-ого классника","name_ru"=>"For the IV-grade student","category_id"=>"3"),
            array("name_ka"=>"V-კლასის  მოსწავლისათვის","name_en"=>"Для V-ого классника","name_ru"=>"For V-class student","category_id"=>"3"),
            array("name_ka"=>"VI-კლასის  მოსწავლისათვის","name_en"=>"Для VI-ого классника","name_ru"=>"For VI-grade student","category_id"=>"3"),
            array("name_ka"=>"VII-კლასის  მოსწავლისათვის","name_en"=>"Для VII-ого классника","name_ru"=>"For VII-grade student","category_id"=>"3"),
            array("name_ka"=>"VIII-კლასის  მოსწავლისათვის","name_en"=>"Для VIII классника","name_ru"=>"For VIII-grade student","category_id"=>"3"),
            array("name_ka"=>"IX-კლასის  მოსწავლისათვის","name_en"=>"Для IX классника","name_ru"=>"For IX-grade student","category_id"=>"3"),
            array("name_ka"=>"X-კლასის  მოსწავლისათვის","name_en"=>"Для X классника","name_ru"=>"For X-class student","category_id"=>"3"),
            array("name_ka"=>"XI-კლასის  მოსწავლისათვის","name_en"=>"Для XI-ого классника","name_ru"=>"For students of class XI","category_id"=>"3"),
            array("name_ka"=>"XII-კლასის  მოსწავლისათვის","name_en"=>"Для XII классника","name_ru"=>"For students of class XII","category_id"=>"3"),
            array("name_ka"=>"აბიტურიენტისათვის","name_en"=>"для абитуриента","name_ru"=>"for the entrant","category_id"=>"3"),
            array("name_ka"=>"70 კვ.მ-მდე ბინაში","name_en"=>"up to 70 sq.m. in an apartment","name_ru"=>"до 70 кв.м в квартире","category_id"=>"4"),
            array("name_ka"=>"100 კვ.მ-მდე ბინაში","name_en"=>"up to 100 sq.m. in an apartment","name_ru"=>"до 100 кв.м в квартире","category_id"=>"4"),
            array("name_ka"=>"150 კვ.მ-მდე ბინაში","name_en"=>"up to 150 sq.m. in an apartment","name_ru"=>"до 150 кв.м в квартире","category_id"=>"4"),
            array("name_ka"=>"200 კვ.მ-მდე ბინაში","name_en"=>"up to 200 sq.m. in an apartment","name_ru"=>"до 200 кв.м в квартире","category_id"=>"4"),
            array("name_ka"=>"300 კვ.მ-მდე სახლში","name_en"=>"Up to 300 sq.m. in the house","name_ru"=>"До 300 кв.м в доме","category_id"=>"4"),
            array("name_ka"=>"400 კვ.მ-მდე სახლში","name_en"=>"Up to 400 sq.m. in the house","name_ru"=>"До 400 кв.м в доме","category_id"=>"4"),
            array("name_ka"=>"500 კვ.მ-მდე სახლში","name_en"=>"Up to 500 sq.m. in the house","name_ru"=>"До 500 кв.м в доме","category_id"=>"4"),
            array("name_ka"=>"20 წლის ქალბატონი","name_en"=>"20 years old Mrs","name_ru"=>"20 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"20 წლის მამაკაცი","name_en"=>"20 years old male","name_ru"=>"20 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"21 წლის ქალბატონი","name_en"=>"21 years old Mrs","name_ru"=>"21 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"21 წლის მამაკაცი","name_en"=>"21 years old male","name_ru"=>"21 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"22 წლის ქალბატონი","name_en"=>"22 years old Mrs","name_ru"=>"22 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"22 წლის მამაკაცი","name_en"=>"22 years old male","name_ru"=>"22 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"23 წლის ქალბატონი","name_en"=>"23 years old Mrs","name_ru"=>"23 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"23 წლის მამაკაცი","name_en"=>"23 years old male","name_ru"=>"23 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"24 წლის ქალბატონი","name_en"=>"24 years old Mrs","name_ru"=>"24 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"24 წლის მამაკაცი","name_en"=>"24 years old male","name_ru"=>"24 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"25 წლის ქალბატონი","name_en"=>"25 years old Mrs","name_ru"=>"25 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"25 წლის მამაკაცი","name_en"=>"25 years old male","name_ru"=>"25 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"26 წლის ქალბატონი","name_en"=>"26 years old Mrs","name_ru"=>"26 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"26 წლის მამაკაცი","name_en"=>"26 years old male","name_ru"=>"26 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"27 წლის ქალბატონი","name_en"=>"27 years old Mrs","name_ru"=>"27 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"27 წლის მამაკაცი","name_en"=>"27 years old male","name_ru"=>"27 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"28 წლის ქალბატონი","name_en"=>"28 years old Mrs","name_ru"=>"28 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"28 წლის მამაკაცი","name_en"=>"28 years old male","name_ru"=>"28 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"29 წლის ქალბატონი","name_en"=>"29 years old Mrs","name_ru"=>"29 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"29 წლის მამაკაცი","name_en"=>"29 years old male","name_ru"=>"29 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"30 წლის ქალბატონი","name_en"=>"30 years old Mrs","name_ru"=>"30 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"30 წლის მამაკაცი","name_en"=>"30 years old male","name_ru"=>"30 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"31 წლის ქალბატონი","name_en"=>"31 years old Mrs","name_ru"=>"31 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"31 წლის მამაკაცი","name_en"=>"31 years old male","name_ru"=>"31 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"32 წლის ქალბატონი","name_en"=>"32 years old Mrs","name_ru"=>"32 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"32 წლის მამაკაცი","name_en"=>"32 years old male","name_ru"=>"32 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"33 წლის ქალბატონი","name_en"=>"33 years old Mrs","name_ru"=>"33 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"33 წლის მამაკაცი","name_en"=>"33 years old male","name_ru"=>"33 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"34 წლის ქალბატონი","name_en"=>"34 years old Mrs","name_ru"=>"34 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"34 წლის მამაკაცი","name_en"=>"34 years old male","name_ru"=>"34 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"35 წლის ქალბატონი","name_en"=>"35 years old Mrs","name_ru"=>"35 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"35 წლის მამაკაცი","name_en"=>"35 years old male","name_ru"=>"35 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"36 წლის ქალბატონი","name_en"=>"36 years old Mrs","name_ru"=>"36 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"36 წლის მამაკაცი","name_en"=>"35 years old male","name_ru"=>"36 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"37 წლის ქალბატონი","name_en"=>"37 years old Mrs","name_ru"=>"37 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"37 წლის მამაკაცი","name_en"=>"37 years old male","name_ru"=>"37 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"38 წლის ქალბატონი","name_en"=>"38 years old Mrs","name_ru"=>"38 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"38 წლის მამაკაცი","name_en"=>"38 years old male","name_ru"=>"38 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"39 წლის ქალბატონი","name_en"=>"39 years old Mrs","name_ru"=>"39 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"39 წლის მამაკაცი","name_en"=>"39 years old male","name_ru"=>"39 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"40 წლის ქალბატონი","name_en"=>"40 years old Mrs","name_ru"=>"40 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"40 წლის მამაკაცი","name_en"=>"40 years old male","name_ru"=>"40 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"41 წლის ქალბატონი","name_en"=>"41 years old Mrs","name_ru"=>"41 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"41 წლის მამაკაცი","name_en"=>"41 years old male","name_ru"=>"41 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"42 წლის ქალბატონი","name_en"=>"42 years old Mrs","name_ru"=>"42 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"42 წლის მამაკაცი","name_en"=>"42 years old male","name_ru"=>"42 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"43 წლის ქალბატონი","name_en"=>"43 years old Mrs","name_ru"=>"43 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"43 წლის მამაკაცი","name_en"=>"43 years old male","name_ru"=>"43 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"44 წლის ქალბატონი","name_en"=>"44 years old Mrs","name_ru"=>"44 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"44 წლის მამაკაცი","name_en"=>"44 years old male","name_ru"=>"44 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"45 წლის ქალბატონი","name_en"=>"45 years old Mrs","name_ru"=>"45 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"45 წლის მამაკაცი","name_en"=>"45 years old male","name_ru"=>"45 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"46 წლის ქალბატონი","name_en"=>"46 years old Mrs","name_ru"=>"46 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"46 წლის მამაკაცი","name_en"=>"46 years old male","name_ru"=>"46 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"47 წლის ქალბატონი","name_en"=>"47 years old Mrs","name_ru"=>"47 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"47 წლის მამაკაცი","name_en"=>"47 years old male","name_ru"=>"47 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"48 წლის ქალბატონი","name_en"=>"48 years old Mrs","name_ru"=>"48 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"48 წლის მამაკაცი","name_en"=>"48 years old male","name_ru"=>"48 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"49 წლის ქალბატონი","name_en"=>"49 years old Mrs","name_ru"=>"49 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"49 წლის მამაკაცი","name_en"=>"49 years old male","name_ru"=>"49 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"50 წლის ქალბატონი","name_en"=>"50 years old Mrs","name_ru"=>"50 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"50 წლის მამაკაცი","name_en"=>"50 years old male","name_ru"=>"50 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"51 წლის ქალბატონი","name_en"=>"51 years old Mrs","name_ru"=>"51 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"51 წლის მამაკაცი","name_en"=>"51 years old male","name_ru"=>"51 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"52 წლის ქალბატონი","name_en"=>"52 years old Mrs","name_ru"=>"52 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"52 წლის მამაკაცი","name_en"=>"52 years old male","name_ru"=>"52 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"53 წლის ქალბატონი","name_en"=>"53 years old Mrs","name_ru"=>"53 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"53 წლის მამაკაცი","name_en"=>"53 years old male","name_ru"=>"53 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"54 წლის ქალბატონი","name_en"=>"54 years old Mrs","name_ru"=>"54 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"54 წლის მამაკაცი","name_en"=>"54 years old male","name_ru"=>"54 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"55 წლის ქალბატონი","name_en"=>"55 years old Mrs","name_ru"=>"55 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"55 წლის მამაკაცი","name_en"=>"55 years old male","name_ru"=>"55 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"56 წლის ქალბატონი","name_en"=>"56 years old Mrs","name_ru"=>"56 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"56 წლის მამაკაცი","name_en"=>"56 years old male","name_ru"=>"56 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"57 წლის ქალბატონი","name_en"=>"57 years old Mrs","name_ru"=>"57 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"57 წლის მამაკაცი","name_en"=>"57 years old male","name_ru"=>"57 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"58 წლის ქალბატონი","name_en"=>"58 years old Mrs","name_ru"=>"58 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"58 წლის მამაკაცი","name_en"=>"58 years old male","name_ru"=>"58 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"59 წლის ქალბატონი","name_en"=>"59 years old Mrs","name_ru"=>"59 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"59 წლის მამაკაცი","name_en"=>"59 years old male","name_ru"=>"59 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"60 წლის ქალბატონი","name_en"=>"60 years old Mrs","name_ru"=>"60 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"60 წლის მამაკაცი","name_en"=>"60 years old male","name_ru"=>"60 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"61 წლის ქალბატონი","name_en"=>"61 years old Mrs","name_ru"=>"61 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"61 წლის მამაკაცი","name_en"=>"61 years old male","name_ru"=>"61 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"62 წლის ქალბატონი","name_en"=>"62 years old Mrs","name_ru"=>"62 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"62 წლის მამაკაცი","name_en"=>"62 years old male","name_ru"=>"62 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"63 წლის ქალბატონი","name_en"=>"63 years old Mrs","name_ru"=>"63 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"63 წლის მამაკაცი","name_en"=>"63 years old male","name_ru"=>"63 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"64 წლის ქალბატონი","name_en"=>"64 years old Mrs","name_ru"=>"64 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"64 წლის მამაკაცი","name_en"=>"64 years old male","name_ru"=>"64 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"65 წლის ქალბატონი","name_en"=>"65 years old Mrs","name_ru"=>"65 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"65 წლის მამაკაცი","name_en"=>"65 years old male","name_ru"=>"65 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"66 წლის ქალბატონი","name_en"=>"66 years old Mrs","name_ru"=>"66 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"66 წლის მამაკაცი","name_en"=>"66 years old male","name_ru"=>"66 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"67 წლის ქალბატონი","name_en"=>"67 years old Mrs","name_ru"=>"67 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"67 წლის მამაკაცი","name_en"=>"67 years old male","name_ru"=>"67 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"68 წლის ქალბატონი","name_en"=>"68 years old Mrs","name_ru"=>"68 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"68 წლის მამაკაცი","name_en"=>"68 years old male","name_ru"=>"68 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"69 წლის ქალბატონი","name_en"=>"69 years old Mrs","name_ru"=>"69 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"69 წლის მამაკაცი","name_en"=>"69 years old male","name_ru"=>"69 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"70 წლის ქალბატონი","name_en"=>"70 years old Mrs","name_ru"=>"70 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"70 წლის მამაკაცი","name_en"=>"70 years old male","name_ru"=>"70 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"71 წლის ქალბატონი","name_en"=>"71 years old Mrs","name_ru"=>"71 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"71 წლის მამაკაცი","name_en"=>"71 years old male","name_ru"=>"71 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"72 წლის ქალბატონი","name_en"=>"72 years old Mrs","name_ru"=>"72 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"72 წლის მამაკაცი","name_en"=>"72 years old male","name_ru"=>"72 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"73 წლის ქალბატონი","name_en"=>"73 years old Mrs","name_ru"=>"73 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"73 წლის მამაკაცი","name_en"=>"73 years old male","name_ru"=>"73 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"74 წლის ქალბატონი","name_en"=>"74 years old Mrs","name_ru"=>"74 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"74 წლის მამაკაცი","name_en"=>"74 years old male","name_ru"=>"74 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"75 წლის ქალბატონი","name_en"=>"75 years old Mrs","name_ru"=>"75 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"75 წლის მამაკაცი","name_en"=>"75 years old male","name_ru"=>"75 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"76 წლის ქალბატონი","name_en"=>"76 years old Mrs","name_ru"=>"76 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"76 წლის მამაკაცი","name_en"=>"76 years old male","name_ru"=>"76 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"77 წლის ქალბატონი","name_en"=>"77 years old Mrs","name_ru"=>"77 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"77 წლის მამაკაცი","name_en"=>"77 years old male","name_ru"=>"77 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"78 წლის ქალბატონი","name_en"=>"78 years old Mrs","name_ru"=>"78 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"78 წლის მამაკაცი","name_en"=>"78 years old male","name_ru"=>"78 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"79 წლის ქალბატონი","name_en"=>"79 years old Mrs","name_ru"=>"79 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"79 წლის მამაკაცი","name_en"=>"79 years old male","name_ru"=>"79 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"80 წლის ქალბატონი","name_en"=>"80 years old Mrs","name_ru"=>"80 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"80 წლის მამაკაცი","name_en"=>"80 years old male","name_ru"=>"80 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"81 წლის ქალბატონი","name_en"=>"81 years old Mrs","name_ru"=>"81 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"81 წლის მამაკაცი","name_en"=>"81 years old male","name_ru"=>"81 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"82 წლის ქალბატონი","name_en"=>"82 years old Mrs","name_ru"=>"82 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"82 წლის მამაკაცი","name_en"=>"82 years old male","name_ru"=>"82 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"83 წლის ქალბატონი","name_en"=>"83 years old Mrs","name_ru"=>"83 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"83 წლის მამაკაცი","name_en"=>"83 years old male","name_ru"=>"83 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"84 წლის ქალბატონი","name_en"=>"84 years old Mrs","name_ru"=>"84 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"84 წლის მამაკაცი","name_en"=>"84 years old male","name_ru"=>"84 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"85 წლის ქალბატონი","name_en"=>"85 years old Mrs","name_ru"=>"85 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"85 წლის მამაკაცი","name_en"=>"85 years old male","name_ru"=>"85 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"86 წლის ქალბატონი","name_en"=>"86 years old Mrs","name_ru"=>"86 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"86 წლის მამაკაცი","name_en"=>"86 years old male","name_ru"=>"86 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"87 წლის ქალბატონი","name_en"=>"87 years old Mrs","name_ru"=>"87 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"87 წლის მამაკაცი","name_en"=>"87 years old male","name_ru"=>"87 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"88 წლის ქალბატონი","name_en"=>"88 years old Mrs","name_ru"=>"88 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"88 წლის მამაკაცი","name_en"=>"88 years old male","name_ru"=>"88 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"89 წლის ქალბატონი","name_en"=>"89 years old Mrs","name_ru"=>"89 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"89 წლის მამაკაცი","name_en"=>"89 years old male","name_ru"=>"89 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"90 წლის ქალბატონი","name_en"=>"90 years old Mrs","name_ru"=>"90 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"90 წლის მამაკაცი","name_en"=>"90 years old male","name_ru"=>"90 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"91 წლის ქალბატონი","name_en"=>"91 years old Mrs","name_ru"=>"91 год Женшчина","category_id"=>"5"),
            array("name_ka"=>"91 წლის მამაკაცი","name_en"=>"91 years old male","name_ru"=>"91 год Мужчина","category_id"=>"5"),
            array("name_ka"=>"92 წლის ქალბატონი","name_en"=>"92 years old Mrs","name_ru"=>"92 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"92 წლის მამაკაცი","name_en"=>"92 years old male","name_ru"=>"92 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"93 წლის ქალბატონი","name_en"=>"93 years old Mrs","name_ru"=>"93 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"93 წლის მამაკაცი","name_en"=>"93 years old male","name_ru"=>"93 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"94 წლის ქალბატონი","name_en"=>"94 years old Mrs","name_ru"=>"94 года Женшчина","category_id"=>"5"),
            array("name_ka"=>"94 წლის მამაკაცი","name_en"=>"94 years old male","name_ru"=>"94 года Мужчина","category_id"=>"5"),
            array("name_ka"=>"95 წლის ქალბატონი","name_en"=>"95 years old Mrs","name_ru"=>"95 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"95 წლის მამაკაცი","name_en"=>"95 years old male","name_ru"=>"95 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"96 წლის ქალბატონი","name_en"=>"96 years old Mrs","name_ru"=>"96 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"96 წლის მამაკაცი","name_en"=>"96 years old male","name_ru"=>"96 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"97 წლის ქალბატონი","name_en"=>"97 years old Mrs","name_ru"=>"97 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"97 წლის მამაკაცი","name_en"=>"97 years old male","name_ru"=>"97 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"98 წლის ქალბატონი","name_en"=>"98 years old Mrs","name_ru"=>"98 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"98 წლის მამაკაცი","name_en"=>"98 years old male","name_ru"=>"98 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"99 წლის ქალბატონი","name_en"=>"99 years old Mrs","name_ru"=>"99 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"99 წლის მამაკაცი","name_en"=>"99 years old male","name_ru"=>"99 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"100 წლის ქალბატონი","name_en"=>"100 years old Mrs","name_ru"=>"100 лет Женшчина","category_id"=>"5"),
            array("name_ka"=>"100 წლის მამაკაცი","name_en"=>"100 years old male","name_ru"=>"100 лет Мужчина","category_id"=>"5"),
            array("name_ka"=>"ოჯახში","name_en"=>"in the family","name_ru"=>"в семье","category_id"=>"6"),
            array("name_ka"=>"დაწესებულებაში","name_en"=>"in the institution","name_ru"=>"в учреждении","category_id"=>"6"),
            array("name_ka"=>"სადარბაზო","name_en"=>"Hallway","name_ru"=>"для подьезда","category_id"=>"6"),
            array("name_ka"=>"ოჯახში","name_en"=>"in the family","name_ru"=>"в семье","category_id"=>"7"),
            array("name_ka"=>"ორგანიზაციაში","name_en"=>"in the organization","name_ru"=>"в организации","category_id"=>"7"),
            array("name_ka"=>"2-3 წლის ასაკის I-ჯგუფის ბავშვებთან","name_en"=>"With children of the I-group aged 2-3 years","name_ru"=>"для детей I группы 2-3 лет","category_id"=>"8"),
            array("name_ka"=>"4-5 წლის ასაკის II-ჯგუფის ბავშვებთან","name_en"=>"With children of the II-group aged 4-5 years","name_ru"=>"для детей II группы 4-5 лет.","category_id"=>"8"),
            array("name_ka"=>"5-6 წლის ასაკის III-ჯგუფის ბავშვებთან","name_en"=>"with III-group children aged 5-6 years","name_ru"=>"для детей III группы в возрасте 5-6 лет","category_id"=>"8"),
            array("name_ka"=>"ოჯახში","name_en"=>"in the family","name_ru"=>"в семье","category_id"=>"9"),
            array("name_ka"=>"ობიექტზე","name_en"=>"on the object","name_ru"=>"на объекте","category_id"=>"9"),
        );
        DB::table('for_who_needs')->insert($data);
    }
}
